### PR TITLE
Optimize png image with zopflipng lossless compression

### PR DESCRIPTION
**Pull request by PeterDaveHello**
#### Summary
Recompress the PNG images losslessly via Google's [zopflipng](http://github.com/google/zopfli) to reduce the application size without losing quality!

The parameters used in this optimization were: `zopflipng --iterations=600 --keepchunks=iCCP --lossy_transparent --splitting=3` 

Ref: https://github.com/mattermost/mattermost-mobile/pull/2682

21 images optimized as below:
```
 docs/20160922_mattermost_desktop.png               | Bin 102186 -> 81471 bytes
 resources/osx/DMG_BG.png                           | Bin 10615 -> 3004 bytes
 src/assets/appicon.png                             | Bin 127062 -> 98944 bytes
 src/assets/linux/dark/MenuIconMentionTemplate.png  | Bin 2426 -> 1165 bytes
 src/assets/linux/dark/MenuIconTemplate.png         | Bin 2386 -> 1137 bytes
 src/assets/linux/dark/MenuIconUnreadTemplate.png   | Bin 2287 -> 1086 bytes
 src/assets/linux/light/MenuIconMentionTemplate.png | Bin 1282 -> 872 bytes
 src/assets/linux/light/MenuIconTemplate.png        | Bin 836 -> 544 bytes
 src/assets/linux/light/MenuIconUnreadTemplate.png  | Bin 1376 -> 1052 bytes
 src/assets/osx/ClickedMenuIcon.png                 | Bin 440 -> 332 bytes
 src/assets/osx/ClickedMenuIcon@2x.png              | Bin 913 -> 598 bytes
 src/assets/osx/ClickedMenuIconMention.png          | Bin 520 -> 345 bytes
 src/assets/osx/ClickedMenuIconMention@2x.png       | Bin 1081 -> 688 bytes
 src/assets/osx/ClickedMenuIconUnread.png           | Bin 480 -> 335 bytes
 src/assets/osx/ClickedMenuIconUnread@2x.png        | Bin 1023 -> 684 bytes
 src/assets/osx/MenuIcon.png                        | Bin 487 -> 344 bytes
 src/assets/osx/MenuIcon@2x.png                     | Bin 1002 -> 719 bytes
 src/assets/osx/MenuIconMention.png                 | Bin 522 -> 342 bytes
 src/assets/osx/MenuIconMention@2x.png              | Bin 1086 -> 766 bytes
 src/assets/osx/MenuIconUnread.png                  | Bin 497 -> 344 bytes
 src/assets/osx/MenuIconUnread@2x.png               | Bin 1067 -> 760 bytes
```

### CODE REVIEW

**Comment by jasonblais** [comment]
cc: @deanwhillier if you have a chance to review this PR?

**Comment by hanzei** [comment]
@esethna Could you give this a quick review?

**Comment by hanzei** [comment]
@esethna Gentle reminder about this PR

**Comment by jasonblais** [comment]
@asaadmahmood wondering if you'd be open to help review, since it looks like you reviewed the related mobile PR?

**Comment by jasonblais** [comment]
@deanwhillier this one should be good to merge

**Pull request merged**
