### PR TITLE
add a menu to open dev tools for current webview

### PR DESCRIPTION
**Pull request by manland**
Before submitting, please confirm you've
 - [X] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [X] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [X] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

Add a menu to open dev tools for current webview 

**Issue link**

https://github.com/mattermost/mattermost-server/issues/10131

**Test Cases**

**Additional Notes**

mattermost-desktop-console

### CODE REVIEW

**Comment by manland** [comment]
Hi @yuya-oc and @esethna any news about this PR ?

**Comment by wget** [comment]
Ok for me but please rerun jenkins tests.

**Comment by manland** [comment]
@wget thanks for your review. I have relaunch jenkins but the link is broken!?

**Comment by yuya-oc** [comment]
Thanks @manland, it would be very helpful feature for us!

**Comment by wget** [comment]
Merged.

@manland The link is not broken. If you see a 404, this means you have no right to access the internal Mattermost Jenkins instance. (I still don't have the rights my self. Have been investigating with carlos our devops, but we are running into issues with our SAML authentication solution).

**Comment by manland** [comment]
@wget thanks for explanations, if tests are ok, I am ok :D

**Pull request merged**
