### PR TITLE
[WIP] Add team switch shortcut

### PR DESCRIPTION
**Pull request by MartinDelille**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [ ] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

This is a rough work in progress aiming to add a shortcut for team switch

**Issue link**

https://github.com/mattermost/desktop/issues/850

**Test Cases**

1. Connect to a mattermost instance where you belong to two teams
1. Press Cmd/Ctrl+1 to switch to team 1
1. Press Cmd/Ctrl+2 to switch to team 2
1. Press Cmd/Ctrl+3 to switch to team 3

**Additional Notes**

As I said, this is very early in the development but pushing this PR will help me discussed with advanced electron developer (I'm just a newbie in this area).

Currently the teams are added statically (three team numbered from 1 to 3) but I would like it to be dynamic and correctly named.

### CODE REVIEW

**Comment by yuya-oc** [comment]
Hi @MartinDelille, thanks for your interests!

The desktop app already has shortcuts `Cmd/Ctrl+{1~9}` to switch servers. Just curious, how will you arrange them? And if possible, I suggest to implement this kind of shortcut in webapp. Users can switch teams also on web browsers.

**Comment by MartinDelille** [comment]
@yuya-oc you're right. I could replace the Cmd/Ctrl+{1~9} by Cmd/Ctrl + Shift +{1~9}.

I will look at the server code.

**Comment by amaiorano** [comment]
What happened to this? Such a useful feature!

**Comment by MartinDelille** [comment]
This is a work that has to be done on the server code since the desktop project is only an electron container.

I don't have the competence for that yet.

**Comment by amaiorano** [comment]
Ah right, I understand. Well, maybe when I have some time I'll take a look. Maybe I'm wrong, but I figure it will be mostly about doing as is already done for channel change shortcuts.

**Pull request closed without merging**
