### PR TITLE
test: Undo in the menu bar

### PR DESCRIPTION
**Pull request by codedsun**
#### Summary

test: Undo in the menu bar

#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1896

#### Checklist

- [x ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by codedsun** [comment]
@devinbinnie For undo do we have some other command than ctrl+z ?

**Comment by devinbinnie** [comment]
@codedsun That works, you can also press Alt and use the arrow keys to navigate the menu (on Windows/Linux only)

**Comment by codedsun** [comment]
@devinbinnie But the test seems to be failing for the same :(

**Comment by codedsun** [comment]
@devinbinnie Looks like robotjs library has some issue with key taps. The code seems to look fine what are your thoughts?

**Comment by codedsun** [comment]
@devinbinnie The issue here https://github.com/octalmage/robotjs/issues/530.

**Comment by devinbinnie** [comment]
@codedsun Sorry, what's the issue you're having?
You can use Playwright to type in the string you want to use (if you want) and you should be able to do `robot.keyTap('z', ['control']);` to undo.

Which part isn't working?

**Comment by codedsun** [comment]
@devinbinnie The undo is not working. I have typed the string the undo command should just revert the string but it doesnt works

**Comment by devinbinnie** [comment]
@codedsun If you need to do it from the menu you can test it out yourself using the app before you run the E2E test. I'm sure that's something you can figure out ;)

**Comment by codedsun** [comment]
@devinbinnie The problem is I am on mac system :(

**Comment by codedsun** [comment]
@devinbinnie There is some problem with robotjs keytap, the same combination when done manually works on desktop app works.

**Comment by devinbinnie** [comment]
@codedsun I've fixed up the test, apparently the window was not correctly in focus which is why it wasn't received RobotJS events correctly. So I've use an alternative method via clicking the 3-dot menu first and then using the keyboard to navigate it.

I've also made some other small changes. I'll let you have a look first.

**Comment by codedsun** [comment]
@devinbinnie Can you let me know how did you debugged ? Like how did you came to know this?

**Review by devinbinnie — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Pull request merged**
