### PR TITLE
Latest react bootstrap

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Use `propTypes` in react components and upgrade react-bootstrap from 0.29.x to 0.30.x
In this change, all react components are divided into separated .jsx files for future refactoring.

Tested on Windows 10 and Linux Mint 18 Cinnamon

**Issue link**
#319 

**Test Cases**
Use the application. All UI features should not be changed.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/94#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Just two minor issues on Windows 10, otherwise looks good

----

1 - After toggling console developer tools, active tab has a yellow halo behind it, which disappears after a few seconds

Repro:
 - Go to **View > Toggle Developer Tools** or hit `CTRL + SHIFT + I` on your keyboard
 - Repeat to close developer tools

Observed:

image

----

2 - Mouse cursor is in "Link Select" mode instead of "Normal Select" mode in the "Cannot connect to Mattermost" page

Repro:
 - Disconnect your Internet
 - Open the Mattermost app

Observed:
image

Expected:
image

**Comment by yuya-oc** [comment]
Thank you for testing. I also tested two issues.

> 1 - After toggling console developer tools, active tab has a yellow halo behind it, which disappears after a few seconds

The yellow halo doesn't disappear after a few sec, and it reproduced on 3.4.1 release on Windows 10. So I added an event handler to suppress it, however the halo appears for only a moment.
https://circleci.com/gh/yuya-oc/desktop/98#artifacts

On macOS, the issue didn't reproduce.

> 2 - Mouse cursor is in "Link Select" mode instead of "Normal Select" mode in the "Cannot connect to Mattermost" page

Not reproduced on Windows 10 and macOS.

**Comment by jasonblais** [comment]
Tested:

1 - The halo is barely noticeable, so I think this is good

2 - Couldn't reproduce either..might have been a temporary glitch on my end.

Sign off on Windows. Thanks @yuya-oc!

**Comment by yangchen1** [comment]
Looks great on Mac. The windows bugs didn't repro. :) 👍

**Pull request merged**
