### PR TITLE
[MM-40051] MM-T4385 select tab from menu

### PR DESCRIPTION
**Pull request by shadowshot-x**
#### Summary

Added Simple tests for Tab change detection. 

#### Ticket Link

Fixes https://github.com/mattermost/desktop/issues/1917

#### Checklist

- [x] Added End to end tests (required for all new features)
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on:  macOS Big Sur Version 11.4

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by devinbinnie — CHANGES_REQUESTED** [review]
@shadowshot-x Thanks for the PR!

Unfortunately this approach is not what is required for this test. You will need to use RobotJS to navigate the application menu (hence why you need to navigate to Window first) and select the tabs from there. There are examples of RobotJS you can use in the codebase.

**Comment by shadowshot-x** [comment]
Sure @devinbinnie. I will check this.

**Review by devinbinnie — APPROVED** [review]
Thanks @shadowshot-x, this is looking good now!

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Thanks for the PR, @shadowshot-x!

**Pull request merged**
