### PR TITLE
remove global shortcuts

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

On linux, other apps can't react to shortcuts because matttermost desktop is capturing them as a global shortcut.

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [ ] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [ ] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by mgdelacroix — APPROVED** [review]
LGTM! :+1:

**Comment by devinbinnie** [comment]
@mgdelacroix Can you grab the linux build off of this PR (once it's ready) and check if your problem is resolved?

**Comment by mgdelacroix** [comment]
@devinbinnie confirmed that it does solve the issue, I can use shortcuts like `ALT+F` and `ALT+W` again while Mattermost is open! Thanks guys for working on this!! <3

@Willyfrog

**Review by mgdelacroix — APPROVED** [review]

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
