### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade dependencies.

After this PR, we will get ready to switch back to npm.

**Issue link**
#898 

**Test Cases**
- Apps should normally work.
- "Save Image" context menu should work.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/1187#artifacts

### CODE REVIEW

**Comment by yuya-oc** [comment]
Looks good to me.

- Windows 10 Pro 64-bit (zip, exe)
- macOS 10.14.1 (zip, dmg)

**Comment by yuya-oc** [comment]
Rebased against the latest master branch.

Artifacts: https://circleci.com/gh/yuya-oc/desktop/1211#artifacts

**Comment by yuya-oc** [comment]
Added Electron v4. As far as reading the release notes, I could not find critical changes for us (However v5 will break the app due to default webPreferences values).
https://electronjs.org/releases#4.0.0

Artifacts: https://circleci.com/gh/yuya-oc/desktop/1215#artifacts

**Comment by wget** [comment]
Build success on Windows 10 Pro x64 1809 dev machine.

The build succeded on AppVeyor as well **BUT** only one test is failing. Could we please fix this before merging this pull request?

Here are the failing logs for the tests on AppVeyor: https://ci.appveyor.com/project/wget/mattermost-desktop/builds/21360791

**Comment by yuya-oc** [comment]
@wget Updated the branch. What about this?

For blurry rendering, I think it's known issue (#560, https://github.com/electron/electron/issues/10025). The reason is that Electron's webview unexpectedly uses grayscale antialiasing. It looks like blurry.

**Comment by wget** [comment]
@yuya-oc Everything worked like expected. The migration from yarn to npm went smoothly. All tests passed.

Artefacts: https://ci.appveyor.com/project/wget/mattermost-desktop/builds/21505020

It's finally time to merge!

**Pull request merged**
