### PR TITLE
Add support for sound notifications on Windows 7 and 8

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Add support for sound notifications on Windows 7 and 8.

`src/assets/ding.mp3` is derived from [platform repository](https://github.com/mattermost/platform/blob/v3.7.3/webapp/images/ding.mp3).

`url-loader` is added to devDependencies of `package.json`.

**Issue link**
#467 

**Test Cases**
Post a message from another user. Expected behavior is below.

- When notification sound is enabled in webapp settings:
  - Windows 7 and 8: Hear a sound, `ding.mp3`
  - Others: No extra sounds.
- When notification sound is disabled in webapp settings:
  - All: No sounds.

Tested on macOS, Windows 7 and 10.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/211#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Tested on Windows 10: sound notification settings work as before, no change.

I'll ask one of our team members who has Windows 7 to help test.

**Comment by lindy65** [comment]
Tested on Windows 7: 

When notification sound is enabled in webapp settings, I hear a sound (ding.mp3)

When notification sound is disabled in webapp settings, I don't hear any sounds.

**Comment by jasonblais** [comment]
Thanks @lindy65! @yuya-oc this one is good to merge

**Comment by yuya-oc** [comment]
Thanks all!

**Pull request merged**
