### PR TITLE
[MM-45409] Restrict auto-update functionality specifically to the NSIS installer and AppImage

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
The MSI installer and some others are still including the update functionality. This should really be limited to the NSIS and AppImage installer only, so I've forced that to happen here.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45409
Closes https://github.com/mattermost/desktop/issues/2175

#### Release Note
```release-note
Disable auto-update functionality explicitly for all but the Windows EXE installer and the Linux AppImage
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by rtfm98** [comment]
Hey there,

do you already know in which release this commit will be included and when? Because that would solve the problem described in #2250 (as we use the msi installer at work and unsuccessfully tried to disable the auto-updater via group policies).

**Comment by cwarnermm** [comment]
@devinbinnie - In the [product documentation](https://docs.mattermost.com/install/desktop-app-install.html), automatic desktop app updates are supported only for Windows and the iOS app installed from the App Store.

The **Generic Linux** tab documentation states that: "Automatic app updates aren’t supported. You must update your app manually." Is this statement incorrect based on the changes applied in this PR?

**Comment by devinbinnie** [comment]
@cwarnermm Yeah that's incorrect. Automatic updates are supported on Linux either via the AppImage, or using the APT repository.

**Comment by cwarnermm** [comment]
Thanks, @devinbinnie! I'll correct this documentation.

2 more follow up questions:
- Are the docs also incorrect in stating that "A **beta** AppImage distribution of a compressed tarball is available."? Is it still in beta?
- Should the **Ubuntu/Debian** tab be updated to clarify that **both** a .deb package and an APT repository is available for Debian 9 and for Ubuntu releases 18.04 LTS or later?

**Pull request merged**
