### PR TITLE
Add it-IT as spellchecker

### PR DESCRIPTION
**Pull request by JtheBAB**
This pull request adds it-IT as available spellchecker within the DesktopApp.

Needs prior #938 to merge.

### CODE REVIEW

**Comment by wget** [comment]
As [discussed](https://community.mattermost.com/core/pl/kt98u458zigfzrcd85b76h9kac), we will be using `electron-spellchecker` instead. We need to get the new CI merged first.

If this PR needs to get merged, #938 needs to be merged first.

**Comment by esethna** [comment]
@wget @JtheBAB are these PRs still valid if we are moving to electron-spellchecker?

**Comment by JtheBAB** [comment]
No. This is for the current spellchecker.

**Comment by JtheBAB** [comment]
@esethna

As there is a 4.2.1, you could add this.

**Comment by hanzei** [comment]
@wget @svelle @deanwhillier Is this PR still valid?

**Comment by svelle** [comment]
> @wget @svelle @deanwhillier Is this PR still valid?

technically yes since we do not have a set date for when the electron-spellchecker PR is done. Right now it builds but still has some errors that happen in the UI (at least for me) so until those are fixed this pr might by valid. I'd be pro merging (after the circleci errors are fixed) since it brings minimal changes to the code base but is helpful to users who might want to use Italian or (in the other PR) Polish spellchecking.

**Comment by esethna** [comment]
Adding the "Pending" label as we are coming back to this PR in the very near future: https://github.com/mattermost/desktop/pull/948

**Comment by deanwhillier** [comment]
Going to close this one in favour of #1139 as the changes are the same, but the other one is made on top of more recent code that has the updated CircleCI code. @JtheBAB, appreciate your contribution, apologies this took so long to get to!

**Pull request closed without merging**
