### PR TITLE
 [MM-37198] enable global sandboxing to increase security (cherry-pick #1667)

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Conversion to JS & Cherry-pick of #1667 into release 4.7

#### Ticket Link

[MM-37198](https://mattermost.atlassian.net/browse/MM-37198)

#### Device Information

This PR was tested on: macos bigsur & windows 10

#### Release Note
```release-note
global sandbox enabled
```

### CODE REVIEW

**Review by srkgupta — APPROVED** [review]
Tested the changes and the security issue is working fine now. Thanks @Willyfrog. LGTM

**Comment by devinbinnie** [comment]
@Willyfrog There's a couple lint issues on this cherry-pick, we should get those fixed up.

**Comment by Willyfrog** [comment]
> @Willyfrog There's a couple lint issues on this cherry-pick, we should get those fixed up.

that's weird, it shouldn't compile, but it was obviously a non-intended character... I wonder how that happened 🤷

**Comment by Willyfrog** [comment]
@devinbinnie fixed, thanks for the heads up

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
