### PR TITLE
Refactor main window code

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Refactor main window code.

Now the main window is managed by `src/main/mainWindow.js`.

**Issue link**
N/A

**Test Cases**
All cases.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/195#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc can you help clarify which areas should be tested? Would the following be sufficient?
 - help menu bar
 - Settings page (both server management and app options)

**Comment by yuya-oc** [comment]
Sorry, the description was not good. Need to test the following.

- Close/Minimize the window
- Start on Login
- Tray icon menu

**Comment by jasonblais** [comment]
Works on Windows 👍

**Comment by jasonblais** [comment]
@jnugh Would you be able to help with Linux testing when you get the chance? I'll see if I can find someone on our team to test Mac, which only involves closing/minimizing the app.

**Comment by jnugh** [comment]
Tested the following:
- Settings work (can change options, add remove servers)
- Can switch Servers using the Server Tabs
- Can post to each server (Mattermost renders)
- Can add Servers using the + button

Anything else?
Looks good to me :+1:

**Comment by jasonblais** [comment]
Thanks @jnugh! Much appreciated!

Can you also try that these actions work:
- Close/Minimize the window
- Start on Login
- Tray icon menu

**Comment by jnugh** [comment]
All those (+ minimize to tray on close) work flawlessly :+1:!

**Comment by jasonblais** [comment]
This one is good to merge as well @yuya-oc

**Comment by jasonblais** [comment]
Forgot to post testing results for Mac: no issues found

- Minimized, sent DM from another user, saw number badge in dock as expected, and clicking dock icon restored app to desktop
- Closed window with red X (with existing unreads), saw unread badge stay visible in dock as expected, and clicking dock icon restored app to desktop
- Right-click dock icon options all work as expected:
  - Options > Keep in Dock on: Icon stays in dock after quitting app, Keep in Dock off: Icon disappears from dock after quitting app
  - Options > Open at Login opens app after restarting machine and logging in
  - Options > Show in Finder displays the Finder folder where the app lives
  - Quit closes app
  - Hide hides the app window
  - Show All Windows (after Hide) displays hidden window, which can be clicked to be restored

**Comment by yuya-oc** [comment]
Thanks for detailed reports!

**Pull request merged**
