### PR TITLE
Show URL when hovering over links

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Show URL when the mouse cursor is hovering over links.

Tested on Windows 10.

**Issue link**
#276

**Test Cases**
In webview, move the mouse cursor onto links such as URL.

**Additional Notes**
Artifacts: https://circleci.com/gh/yuya-oc/desktop/97#artifacts

`npm run lint:js` is failing, but it's not related to this change.

### CODE REVIEW

**Comment by jasonblais** [comment]
Works really great apart from small nits (on Windows 10). I didn't realize this PR would be this large, big thanks for the work here @yuya-oc! 

License for the `react-addons-css-transition-group` package also looks good.

1 - Propose updating the URL visual to match the Chrome browser a little more closely:
  - have the border a little darker so you can see it more clearly
  - increase the height a little so there's more white space below and above the URL link

Below is an example of what it looks like on the desktop, and on the browser.

image
*Above: Browser*

image
*Above: Desktop -- hard to see the border + not much white space below and above the link*

2 - Truncate long URLs based on window size, so that the URL popup only takes one line of space

image
*Above: Browser*

image
*Above: Desktop -- URL wraps around more than one line instead of truncating*

3 - If you hover over multiple links in succession, the URL popup disappears for a moment.

I've illustrated the behaviour between the browser and desktop below:

image

4 - Looks like the build is failing, maybe due to code formatting?

image

**Comment by yuya-oc** [comment]
Thank you for detailed feedback! The branch is based on #371, so the changes would be reduced after it's merged.

https://circleci.com/gh/yuya-oc/desktop/99#artifacts

For 1) and 2), I updated the appearance. Please check. For 3), I added 500ms delay before starting disappearing. It might not be perfect, but it should be improved.

About 4), yes, it's only for code formatting. And the file, `src/main.js` is not changed in this PR. So I think it doesn't matter in this PR.

**Comment by jasonblais** [comment]
This is excellent, really nice work!!

Love it, tested on Windows 10

**Comment by jasonblais** [comment]
Sorry, @yuya-oc, I noticed one thing with further testing:

1) Search "hello" in https://pre-release.mattermost.com
2) For any of the search results, click "Jump"
3) Scroll to the bottom of the archived view
4) Attempt to click "Click here to jump to recent messages"

Observed: Since the URL popup appears on hover, I'm unable to click the link because the popup gets in front of it

image

image

Expected: 

1) The link is still clickable even though the popup is in front of the link (similar to web browser behaviour)

2) If the popup appears in front of the link, the popup should appear on the bottom RIGHT corner of the window, not left. 

Note: If the link is long, (2) wouldn't really solve the problem..but is also common behaviour for web browsers.

image

**Comment by jasonblais** [comment]
I think for the 3.5 release, implementing the first expected result would be sufficient (having the link clickable despite having the popup in front).

We can decide later whether we want to implement the second expected result.

**Comment by yuya-oc** [comment]
Updated for the first: https://circleci.com/gh/yuya-oc/desktop/100#artifacts

@jasonblais Sure, I'm agree to that.

**Comment by jasonblais** [comment]
Fantastic! Thank you, works great.

@yangchen1, have you had a chance to test this on Mac platform yet?

**Comment by yangchen1** [comment]
Looks really great, +1! This is really nice.

**Pull request merged**
