### PR TITLE
[MM-43656] Flush cookies to disk on finishing custom login

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
OneLogin's 'Remember me' feature wasn't working, and I think the issue was that we weren't saving cookies to disk until after the user blurs the app (or closes it).

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43656

```release-note
Fixed an issue where OneLogin users wouldn't have their credentials remembered.
```

### CODE REVIEW

**Comment by amyblais** [comment]
@devinbinnie Is this planned for v5.1, or do we remove the milestone from the ticket/PR?

**Comment by devinbinnie** [comment]
@amyblais It can wait until the next release, it's not super urgent.

**Review by m1lt0n — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @devinbinnie
Tested on macOS - works great, I didn't know I needed this 🙂 
On Win 10 - At login, app opens on Playbooks each time. Not on Playbooks tab, Channels tab in focus with Playbooks product shown on product switcher.
Haven't checked Ubunto yet, that's next - will comment shortly 
Screenshot 2023-02-01 140334

**Comment by devinbinnie** [comment]
> Thanks @devinbinnie Tested on macOS - works great, I didn't know I needed this 🙂 On Win 10 - At login, app opens on Playbooks each time. Not on Playbooks tab, Channels tab in focus with Playbooks product shown on product switcher. Haven't checked Ubunto yet, that's next - will comment shortly Screenshot 2023-02-01 140334

Looks like a separate issue. If you are able to reproduce can you file a ticket for us and we'll have a look? :)
As long as the usernames are being remembered correctly we should be okay to approve this :)

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
