### PR TITLE
[MM-17251] Change to using ‘postMessage’ for desktop presence detection

### PR DESCRIPTION
**Pull request by deanwhillier**
#### Summary
As a result of a security update to the Desktop app (context isolation), the Desktop <-> Webapp communication for presence detection broke. This PR changes the communication mechanism to use postMessage in order to get Desktop <-> Webapp communication working again.

#### Issue link
https://mattermost.atlassian.net/browse/MM-17251

#### Related Pull Requests
Webapp: https://github.com/mattermost/mattermost-webapp/pull/3548

### CODE REVIEW

**Comment by lindalumitchell** [comment]
Are there description and test steps that can be added to the ticket for this one?

**Comment by enahum** [comment]
Basically the idea here is to have the status changing when the user is away or present, this was already done but a secfix broke this, this PR is intended to fix it back to how it was.

☝️As far as I can tell

**Comment by deanwhillier** [comment]
@lindalumitchel, the description and test steps from the [original PR](https://github.com/mattermost/desktop/pull/993) can be used for this one. I’ll add to the ticket as well.

**Comment by lindalumitchell** [comment]
Thanks @enahum and @deanwhillier! I tried to remove the QA label, but it looks like I don't have permission in this repo to add/remove labels, so for now can you please remove QA Review label for me, and then for future, does anyone know who I should ask to get permission in this repo to remove those labels myself?

**Comment by deanwhillier** [comment]
Added pipeline fixes from @Willyfrog, tests are now running again and passing!

**Pull request merged**
