### PR TITLE
Update Display Name for MSI

### PR DESCRIPTION
**Pull request by JtheBAB**
#### Summary
Update Display Name to Mattermost Desktop to reflect the real name. Sorry don't know where to change the exe builder :/

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
Thanks @JtheBAB, I'm not sure this one is necessary though. I think the app name (at least on Windows) is still Mattermost.

**Comment by JtheBAB** [comment]
I find it just strange as everywhere it is Mattermost Desktop. But there not. But up to you guys :)

**Review by wget — APPROVED** [review]
I'm upvoting this I may work on a server msi installer later on an this would help avoid confusion between the server and desktop parts in display names from the app uninstall windows feature. I'm also preparing the work towards WiX v4.

**Comment by wget** [comment]
@devinbinnie Feel free to give approval so that I can merge :)

**Comment by devinbinnie** [comment]
@wget Before I approve, and forgive my ignorance because I'm not super familiar with MSI building myself other than what I've had to work with, but is there any risk in changing the name here? Does that change the name of any shortcuts? Would notifications be affected (since Windows bases their existence off of some ID)?

**Comment by wget** [comment]
@devinbinnie I don't pretend to know everything about msi myself either, but what matters most (:yum: ) is the `Product Id` and `UpgradeCode` attribute, not the `name` :) In the past, that name was usually changed depending on the version used to make it look different in the Add/Remove program control panel element.
So yes, the Name doesn't matter here. That name was important for Chocolatey for example when we hadn't any msi installer yet, chcolatey relied on it to grab the Uninstall string from the registry. Now with msi installer, they use the ID.

I checked by myself and an upgrade process is working flawlessly between a 5.2.2 and a 5.3.0-develop (with the new name).

Before:
Screenshot_20230120_204333
After:
Screenshot_20230120_212156

In the installer GUI (the name is also changed everywhere else, but I'm not gonna do screenshots for all of them :P ):
Screenshot_20230120_212126

**Review by devinbinnie — APPROVED** [review]

**Comment by devinbinnie** [comment]
Seems like this is something everyone wants, so I shall approve and merge. Thanks @JtheBAB and @wget :)

**Pull request merged**
