### PR TITLE
Rename electron-mattermost to Mattermost at implementation

### PR DESCRIPTION
**Pull request by yuya-oc**
This PR rename the application at implementation.

* npm package name (package.json: name) is "mattermost-desktop"
* display name (package.json: productName) is "Mattermost"

As the result, configuration directory will be different from `electron-mattermost`. To take over the configuration, users have to copy `config.json`. When releasing the next version, we must announce this point.

### CODE REVIEW

**Comment by yuya-oc** [comment]
CircleCI will pass after merging.

**Comment by it33** [comment]
@crspeller, just wondering if you had any feedback?

@yuya-oc, FYI, @crspeller leads build for the Mattermost server and I thought he might be a good person to share any feedback on naming.

**Comment by crspeller** [comment]
@yuya-oc Looks good!  The official binaries for Mattermost have the version number in them now:  https://releases.mattermost.com/2.1.0/mattermost-team-2.1.0-linux-amd64.tar.gz Maybe we should put the mattermost-desktop version number in the same place? 

ex: `mattermost-desktop-1.0.7-linux-amd64.tar.gz`

**Comment by yuya-oc** [comment]
@crspeller Yes, the version number should be included. At d824ba8e2e88d50b806cac21abb72530a9ef6682, it will be like `mattermost-desktop-v1.0.7-linux-x64.tar.gz` (electron-mattermost already uses this style). So "v" is the difference and it's just named by git-tag. Which is better?

**Comment by yuya-oc** [comment]
This will close #77.

**Comment by crspeller** [comment]
We drop the `v` from our builds so we should drop it here as well.

**Comment by yuya-oc** [comment]
Thanks, I will drop `v`.

**Pull request merged**
