### PR TITLE
Use different colors for unread/mentioned in windows task bar. 

### PR DESCRIPTION
**Pull request by Razzeee**
Like we do for tray icons.

As it's very confusing for windows users, why the trayicon can have a different colored dot, then the taskbar icon.
I also tried to mimic the black boarder around the dot.

One thing that's not matching is the color. Should I use the color you use in the taskbar dots or the material colors, like you used for the red before?

### CODE REVIEW

**Comment by yuya-oc** [comment]
Originally, there are no tray icon and the feature is brought from OS X badge. So there is red circle only. But the tray icon is too small to indicate number, so I used two different colors.

> One thing that's not matching is the color. Should I use the color you use in the taskbar dots or the material colors, like you used for the red before?
Sorry for my poor understanding about English, what answer do you expect? Just in my first impression, cyan is too light and the black border makes mismatching.


If there is screenshot, it's very helpful to discuss because everyone can know the result.

**Comment by yuya-oc** [comment]
Before: before

After: after

**Comment by Razzeee** [comment]
The trayicon color dots are:
```
#FF154E red
#00E4FA blue/green
```
Versus task bar color dots:
```
#FF1744 Material Red A400
#00e5ff Material Cyan A400
```

I think we should align those to one another, but which is the "correct" one?

I don't get the mismatching part about the border :) As in I don't understand what your trying to say.

**Comment by yuya-oc** [comment]
Thank you for description, and it's interesting. First, material color is correct. The border is just for coloring, so I think that it's not matter at this PR.

JFYI, material colors are used for tray icon. So I think I could not understand what you said.



```
0, 229, 255 -> #00e5ff: Cyan A400
```

**Comment by Razzeee** [comment]
Your absolutely right. Paint.net says the same for me. Yesterday when I did this, I had no pc with a colorpicker and used some browser plugin, that now appears to be quiet crappy :D

So we're fine color wise.

**Comment by yuya-oc** [comment]
Thank you!

**Comment by Razzeee** [comment]
What exactly would I do to the color?

**Comment by yuya-oc** [comment]
In my thought, border line might be fine by using daker color (A700?).

If you clould, please try other colors for badges. There are no reason to use Cyan.
When you change the color from cyan, you don't have to change the tray icons. They will be modified to solve other issues.

**Pull request merged**
