### PR TITLE
Limit navigation to origins which is outside of servers

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Limit navigation flows to untrusted origins, which is outside of servers.

Once an origin is allowed, it's assumed as a trusted origin until the application finishes.

**Issue link**
https://mattermost.atlassian.net/browse/PLT-7457

**Test Cases**
1. Register a normal website as a server URL.
2. Click a link to another website in the tab.
3. A dialog should appear.
4. When clicking 'No', the page will not navigate.
5. When clicking 'Yes', the page will navigate to the URL.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/414#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks! Send you a brief note at https://pre-release.mattermost.com

**Comment by jasonblais** [comment]
Hey @yuya-oc, sorry for the delay on this.

Sent you another note on pre-release and added notes on this Google slide: https://docs.google.com/presentation/d/1uyIQxcscGzKcXPHUMMb3Rg7Loxld1ztmOE7t4d0z_nA/edit#slide=id.g28d3453657_0_16

I think we're close after whitelisting the GitLab/Google/Office/SAML redirect URLs, and updating the design of the dialog. Great work on this!

**Comment by jasonblais** [comment]
@yuya-oc Propose minor changes to the dialog

image

1) Title: Mattermost
2) Text: `Do you continue` --> `Do you want to continue?`
3) As discussed, use `GET /config/client API` call to pull the pre-configured redirect URLs (and trusted domains) so that this dialog doesn't show up during SSO sign in flow for GitLab/Office365/Google/SAML. The mobile apps get the server config whenever you perform any request to the server and the header in the response has a different value for `X-Version-Id` than the last request. Not sure if something like this could be considered for the desktop app, instead of updating at X-minute intervals?

**Comment by yuya-oc** [comment]
3 is possible. Response headers can be inspected.

Please let me confirm. Is the config for trusted origins already available in mattermost-server?

**Comment by jasonblais** [comment]
@yuya-oc They should be. For instance, the admins set the `AuthEndpoint`, `TokenEndpoint` and `UserApiEndpoint` via https://github.com/mattermost/mattermost-server/blob/master/config/default.json#L197, which should contain all the relevant URLs for GitLab SSO. Similarly for others.

**Comment by jasonblais** [comment]
^I can of course test for these cases.

**Comment by yuya-oc** [comment]
Updated. https://circleci.com/gh/yuya-oc/desktop/465#artifacts

Need to prepare appropriate server, so I haven't tested in detail.

**Comment by jasonblais** [comment]
Testing now. Will test with GitLab/SAML/Google/Office365 SSO.

**Comment by jasonblais** [comment]
Some potential bugs:

A:
1) Set https://ci-windows-mysql.mattermost.com as the server URL
2) Click "GitLab" to sign in with GitLab SSO
Observed: Gives a warning that I'm navigating to https://ci-windows-mysql.mattermost.com
image
3) Clicking "Yes" goes through the sign in flow without issues. Note that there was a significant lag between clicking "Yes" and until I was redirected to the GitLab login page. Not sure if there's anything we can do to improve performance?

B: Signing into GitLab gives another warning
image

C:
1) Set https://ci-linux-mysql.mattermost.com as the server URL
2) Click "OneLogin" to sign in with SAML SSO (via OneLogin)
Observed: Gives a warning that I'm navigating to https://mattermost-dev.onelogin.com. Note that `https://mattermost-dev.onelogin.com/trust/saml2/.......` is the `IdPUrl` in `SamlSettings` in `config.json`.
image

D: 
1) Set https://ci-linux-mysql.mattermost.com as the server URL
2) Click "Google Apps" to sign in with Google SSO
Observed: Gives a warning that I'm navigating to https://accounts.google.com. Note that `https://accounts.google.com/...` is the `AuthEndpoint` in `GoogleSettings` in `config.json`.
image

E:
1) Set https://ci-linux-postgres.mattermost.com as the server URL
2) Click "Office365" to sign in with Office365 SSO
Observed: Gives a warning that I'm navigating to https://login.live.com. Note that this is not in config.json, so we may need to whitelist that URL (?)
image

----

On another note for design:

Any way we can add equal whitespace left of `Mattermost` title as there is to the right of the "x". Or are we restricted by the Electron design.

image

**Comment by yuya-oc** [comment]
I found some problem in the servers and Electron.

1. https://ci-linux-mysql.mattermost.com/ returns the header as `x-version-id` instead of `X-Version-Id`. So the feature did not work correctly. (pre-release.mattermost.com uses `X-Version-Id`). It's fixable by assuming multiple cases in the desktop app. (Trying `X-Version-Id`, `x-version-id`, `X-Version-ID` and `X-VERSION-ID`)

2. `/api/v4/config/client?format=old` doesn't contain neither of `AuthEndpoint`, `TokenEndpoint`, `UserApiEndpoint`. So the app can't know trusted URLs. And I couldn't find other parameters which I can use.

3. I seems that Electron doesn't emit `will-navigate` event when the next navigation is a redirect. So the app would not show warning when clicking the login buttons because they redirects to their own login page from mattermost servers)
    1. Click Login with GitLab.
    2. Navigates to `/oauth/gitlab/login`. It's same server, so the dialog should not appear.
    3. Redirects to `https://gitlab.com/oauth/authorize`. It's a redirect, so Electron doesn't emit the event.
    4. Finally, the user doesn't see any dialog until GitLab is opened.
    5. However, if trusted origins are correctly managed, I think it's not a important problem.

For questions:

A-3: Basically there is nothing we can do. Perhaps it's improved by changing algorithm to store/search trusted origins.

Design: It's restricted by Electron. I feel it's a little wrong, too. However to solve that, we need to investigate Electron's implementation.

**Comment by yuya-oc** [comment]
@jasonblais I fixed the case of `X-Version-Id`. Would you try this build to clarify remaining problem? https://circleci.com/gh/yuya-oc/desktop/474#artifacts

**Comment by jasonblais** [comment]
FYI @yuya-oc, have asked our QA team members to help test this on Mac and Windows. Have listed test cases below so they're all in one place.

Test builds:
 - Windows: [.../mattermost-setup-3.7.1-win64.exe](https://474-67276967-gh.circle-artifacts.com/0/tmp/circle-artifacts.P1RW72M/mattermost-setup-3.7.1-win64.exe)
 - Mac: [.../mattermost-desktop-3.7.1-mac.tar.gz](https://474-67276967-gh.circle-artifacts.com/0/tmp/circle-artifacts.P1RW72M/mattermost-desktop-3.7.1-mac.tar.gz)

TEST CASE 1:

1. Add a server with a URL that points to a normal website such as https://about.mattermost.com
2. Click somewhere in the page that redirects you to another website, e.g. https://docs.mattermost.com
Expected: Dialog appears with text `The application is navigating to {URL}. Do you want to continue`. 
 - When clicking 'No', the page stays where you are.
 - When clicking 'Yes', the page will navigate to the new URL.

TEST CASE 2: 

1. Set https://ci-windows-mysql.mattermost.com as the server URL.
2. Sign in with GitLab. 
Expected: During the sign in flow, there shouldn't be a dialog asking if you want to navigate to another URL. The flow should occur without interruptions.

TEST CASE 3: 

1. Set https://ci-linux-mysql.mattermost.com/ as the server URL.
2. Sign in with SAML (OneLogin). 
3. Sign in with Google SSO.
Expected: During the sign in flow, there shouldn't be a dialog asking if you want to navigate to another URL. The flow should occur without interruptions.

TEST CASE 4: 

1. Set https://ci-linux-postgres.mattermost.com/ as the server URL.
2. Sign in with SAML (ADFS). 
3. Sign in with Office 365.
Expected: During the sign in flow, there shouldn't be a dialog asking if you want to navigate to another URL. The flow should occur without interruptions.

TEST CASE 5:

1. Set https://rctesting.reddogsofwar.com/login as the server URL.
2. Sign in with SAML (Okta)
Expected: During the sign in flow, there shouldn't be a dialog asking if you want to navigate to another URL. The flow should occur without interruptions.

**Comment by yuya-oc** [comment]
Rebased: https://circleci.com/gh/yuya-oc/desktop/497#artifacts

Thanks @jasonblais, it looks good to me.

**Comment by lindy65** [comment]
@jasonblais 
I tested on the Winows build on Windows 7

TEST CASE 1: Passed according to expected behaviour.

TEST CASE 2: GitLab - Failed - a dialog asking if you want to navigate to another URL pops up (but I am able to log in thereafter)

TEST CASE 3.2: SAML/OneLogin - Failed - a dialog asking if you want to navigate to another URL pops up (but I am able to log in thereafter)

TEST CASE 3.3 - Google - Failed - a dialog asking if you want to navigate to another URL pops up (but I am able to log in thereafter)

TEST CASE 4.2 - SAML (ADFS) - Connection error (even although I am connected to the internet)

image


TEST CASE 4.3 - Office365 - Passed according to expected (no dialog asking if I want to navigate to another URL)

TEST CASE 5 - SAML (Okta) - https://rctesting.reddogsofwar.com/login is set up for log in with GitLab so I did not perform this test.

**Comment by jasonblais** [comment]
^FYI @yuya-oc

**Comment by yuya-oc** [comment]
@jasonblais 

Test cases from 2 to 4:
> /api/v4/config/client?format=old doesn't contain neither of AuthEndpoint, TokenEndpoint, UserApiEndpoint. So the app can't know trusted URLs. And I couldn't find other parameters which I can use.

[As I wrote before](https://github.com/mattermost/desktop/pull/611#issuecomment-341975570), the servers don't contain trusted origins in the config. So tests failed.
We can add some built-in trusted origins such as gitlab.com to the app, however that can't cover the cases when admins want to use their own domain for SSO. For example, their own GitLab CE/EE instances.

TEST CASE 4.2 - SAML (ADFS)
I can't open the ADFS page due to timeout even when using Chrome. I feel something is wrong in the server config.

**Comment by lindalumitchell** [comment]
@jasonblais @yuya-oc Same behavior on OSX as LI saw on Windows. Office 365 was the only one where I did not see a dialog. But sounds like that's known at this point. Some extra details below, but overall, Mac OS was same as Windows.

Additional notes:
2. GitLab: The first time I entered my GitLab credentials, I saw the dialog, and entered my GitLab credentials, but then it hung on a GitLab spinner, and on refresh I saw the Mattermost login page again. I clicked to log in with GitLab again, and then Town Square displayed
3.2: SAML (OneLogin): Once I had entered my credentials once, if I logged out and back in, I didn't see the dialog again
3.3: Google SSO: Saw a second dialog when using MFA
4.2: ADSF: Connected VPN and did see a dialog but then got a Mattermost error page (I think that was my error, and now it's stuck in that loop. But I did see the dialog)
4.3: Office 365: No dialog, logged in successfully
5. OKTA: Uploaded a license to the server and OKTA was there (I may have inadvertently removed the license before, while testing, or it was lost in one of the builds). Saw the dialog, then logged in successfully

**Comment by yuya-oc** [comment]
@lindalumitchell Once a server is accepted, it's treated as trusted until the app finishes. So you didn't see the dialog when you logged out and back in. In that meaning, the new feature is working well.

> 3.3: Google SSO: Saw a second dialog when using MFA

Possibly Google uses another domain when using MFA. If it's true, the dialog would appear.

**Comment by jasonblais** [comment]
Thanks for all the testing! 

@yuya-oc I'm a little worried that we see the dialog for each sign in method (except Office365 and Google unless MFA is enabled).

For GitLab, we could ask the server team if exposing the AuthEndpoint, TokenEndpoint and UserApiEndpoint in the client config API call would be fine (if so, we could submit a change to the API). But it would only apply for servers v4.5+, and doesn't resolve it for SAML.

Do you know if other Electron apps limit untrusted origins the way we plan to? E.g. Slack doesn't seem to

**Comment by yuya-oc** [comment]
@jasonblais I have never seen this limitation on other Electron app. Accurately, I have never seen any Electron apps which need to access to untrusted origins.
Slack should have this kind of issue because SSO is supported. But I’m not using it on Slack.

**Comment by jasonblais** [comment]
@yuya-oc Should we then ask the Mattermost security team whether completely blocking/limiting untrusted origins is required? Or if there's an alternative approach to consider?

I tested Slack's Google SSO and SAML-Okta SSO and neither gave a dialog. But given they're a SAAS product, they might be able to automatically whitelist the URLs (given you configure them on the workspace settings).

**Comment by jasonblais** [comment]
I'm just worried about the user experience, particularly intitial on-boarding of users, since every new account would see the dialog.

**Comment by yuya-oc** [comment]
@jasonblais Probably yes. To use this feature, we need to know ALL trusted origins before a user logs in. Like our original idea, admins would be able to add desired origins to their server config. But it's probably hard for them to completely know necessary origins (for example, the case of MFA in our tests).

**Comment by jasonblais** [comment]
@yuya-oc Sounds good, I'll post on Monday and cc you so that you can follow the conversation.

**Comment by jasonblais** [comment]
@yuya-oc I've moved this to v4.1 since it requires more investigation as per the thread here: https://pre-release.mattermost.com/core/pl/fitazfu6ci8d5msojytxq5tz3h

**Comment by jasonblais** [comment]
@yuya-oc Your latest note from a few weeks ago was

> ...I can get the information via API. But probably a few days are needed for proper implementation.

> When using cookies as credentials in fetch(), `X-Requested-With: XMLHttpRequest` header is needed.

Wondering if there is enough here to implement and finish this PR?

**Comment by yuya-oc** [comment]
@jasonblais Sorry for dropping this. For now, I could get the response from `/api/v4/config/client?format=old` at https://rctesting.reddogsofwar.com (v4.8.0). But it doesn't contain any of AuthEndpoint, TokenEndpoint and UserApiEndpoint as well as before.

**Comment by jasonblais** [comment]
Ah, I see. So we'd have the same issue then.

Is there much we can do here unless the API returns those endpoints?

**Comment by yuya-oc** [comment]
Just for now, no ideas. Possibly we can get the URL from login button, but probably it's not reliable.

**Comment by jasonblais** [comment]
@yuya-oc Okay, no worries. Let's leave it open for now and come back to this one later.

**Comment by jasonblais** [comment]
I'll close this for now and we can track via https://mattermost.atlassian.net/browse/PLT-7457

**Pull request closed without merging**
