### PR TITLE
Fixed typo in settings (task icon)

### PR DESCRIPTION
**Pull request by Razzeee**
As mentioned in
https://github.com/mattermost/desktop/issues/193#issuecomment-231553779

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @Razzeee, propose updating the help text to

`When a new message is received, flash the taskbar icon`

instead? 

It helps convey to users what the setting does a little better, by having the condition `when a new message ...` before the result `flash the taskbar icon`

**Comment by jasonblais** [comment]
Thanks @Razzeee, propose updating the help text to

`Flash the taskbar icon when a new message is received`

instead, to have the setting conveyed more concisely

**Comment by Razzeee** [comment]
Changed. Also added a commit to align the casing on some settings.

**Comment by jasonblais** [comment]
+1 from me, propose we merge this change for v1.3

**Pull request merged**
