### PR TITLE
Upgrade Electron to 1.7.9

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade Electron 1.7.8 -> 1.7.9

I could not find significant changes excepting minor bug or security fixes.

**Issue link**
N/A

**Test Cases**
General use cases

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/417#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks! Downloaded the artifact and will use it for the next couple of days.

The builds for the PRs keep failing, wondering if we should look into resolving them?

**Comment by yuya-oc** [comment]
Yeah, but I have tried many times to resolve the problem of CI though, I could never solved. Troublingly, recently the test is failing on my Windows. Possibly it would be hard for now.

**Comment by jasonblais** [comment]
Didn't find any issues, this is good to merge @yuya-oc

**Comment by yuya-oc** [comment]
Thanks @jasonblais

**Pull request merged**
