### PR TITLE
[MM-18137] Add an MSI installer job

### PR DESCRIPTION
**Pull request by Willyfrog**
Before submitting, please confirm you've
 - [X] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [X] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [X] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

Added a new job for building an MSI installer for mattermost desktop app on windows.

**Issue link**
[MM-18137](https://mattermost.atlassian.net/browse/MM-18137)

**Test Cases**

after successful run on circle, go to the artifacts tab and download one of the `.msi` files according to your architecture.

**Additional Notes**

- fixed version of wixtools, latest one didn't install on circle servers
- there is room for improvement. Future tickets can be:
  - reuse of windows artifacts from previous build
  - generate another job with .dmg for mac
  - upload of artifacts to another place (s3? @cpanato )
  - generate msi only on release tags

### CODE REVIEW

**Comment by lieut-data** [comment]
@Willyfrog, I confess I don't have the context needed to review this one. Deferring to @cpanato and @deanwhillier.

**Comment by Willyfrog** [comment]
changed base to msi-installer
@deanwhillier are you ok with this? I don't think it was ready for master

**Comment by jasonblais** [comment]
cc @Willyfrog @deanwhillier

**Comment by Willyfrog** [comment]
changes are part of https://github.com/mattermost/desktop/pull/1037 no need to keep this open

**Pull request closed without merging**
