### PR TITLE
[MM-48079] Dont show server login when GPO has preconfigured servers

### PR DESCRIPTION
**Pull request by tboulis**
#### Summary
Show onboarding server login screen only when there are no servers configured (Config.teams.length === 0)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48079

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by m1lt0n — APPROVED** [review]
LGTM!

**Review by devinbinnie — CHANGES_REQUESTED** [review]
I'm still seeing the Getting Started window when GPO servers are configured:
image

Also possibly unrelated, but apparently I can edit/delete my GPO server?
image

**Comment by amyblais** [comment]
> Do you think we could do a hotfix release for this?

Yes, this is queued for a dot release.

**Review by devinbinnie — APPROVED** [review]
Tested and LGTM!

**Pull request merged**
