### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
@esethna @deanwhillier @Willyfrog Can you help merge this as a priority?

The [desktop changelog](https://github.com/mattermost/desktop/blob/master/CHANGELOG.md) is out of date because this PR is still open: https://github.com/mattermost/desktop/pull/1081.

The [desktop changelog in the documentation site](https://docs.mattermost.com/help/apps/desktop-changelog.html) is up-to-date and is easier to maintain.

**Comment by esethna** [comment]
@deanwhillier or @Willyfrog please help merge

**Comment by Willyfrog** [comment]
does this need cherry picking on 4.3?

**Comment by amyblais** [comment]
@Willyfrog Honestly I don't know if it needs to be cherry-picked or not.

**Comment by Willyfrog** [comment]
I guess not, but I'd love confirmation. Anyways it should be easy if the need arises.

**Pull request merged**
