### PR TITLE
[MM-59823] Migrate `BrowserView` to `WebContentsView`

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
A while back, Electron implemented `BrowserView` as an experimental way of nesting sandboxed Chromium views inside of a main windows, replacing `webview`. However, for the longest time that functionality remained experimental and not fully supported.

This PR migrates us over to the new `WebContentsView`, introduced in Electron 30 which should be more stable and supported. It should also simplify resizing logic.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-59823

```release-note
NONE
```

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]

**Review by pvev — APPROVED** [review]
LGTM! nice change @devinbinnie 👍

**Comment by enahum** [comment]
> @enahum Gentle ping for review :) let me know if I need to re-assign

Sorry was not in my radar, I can give it a review in about 12h or so

**Review by enahum — APPROVED** [review]
Sorry for the delay. lgtm

**Pull request merged**
