### PR TITLE
Proposed release process for desktop app

### PR DESCRIPTION
**Pull request by jasonblais**
Proposed release process for desktop app, a subset of what's used by the Mattermost core team for server releases.

This will help smooth out the release process, and help everyone monitor how the release is progressing (each checklist will be posted in the Desktop App channel on their respective dates)

### CODE REVIEW

**Comment by yuya-oc** [comment]
It might not be written in this document though, how would the code completion date be announced?

**Comment by jasonblais** [comment]
I was thinking that each one would be posted in Desktop App channel as we work through the release.

Once we've locked on a release date, anyone can then check from this release process when each step would occur, as we give the generic dates for each (e.g. T-minus 10).

That being said, another option is having it in the mattermost/docs repo.

**Comment by yuya-oc** [comment]
I see. Just I wanted to know that because the doc doesn't say about the code completion date. Thanks!

**Comment by jasonblais** [comment]
> I see. Just I wanted to know that because the doc doesn't say about the code completion date. Thanks!

Can you help me understand more? Want to make sure your concern is addressed

**Comment by yuya-oc** [comment]
I felt that if the code completion date is previously announced as a part of release process, contributors can consider their schedule to submit codes.

**Comment by jasonblais** [comment]
Ah interesting. Maybe we can open a GitHub issue earlier for the release, say 2 weeks before code complete?

The issue could include a shortlist of issues left for the release + planned code complete and release dates.

I actually did so for last couple of releases, and it worked pretty well.

**Comment by yuya-oc** [comment]
Yeah, surely it seems enough. It was forgotten probably because it was not done in upcoming release.

**Pull request merged**
