### PR TITLE
test:MM-T824/MM-T825 Minimize/Close in the Menu Bar

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
MM-T824/MM-T825 Minimize/Close in the Menu Bar

#### Ticket Link
Fixes https://github.com/mattermost/desktop/issues/1903

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting
- [ ] 

```release-note
NONE
```

### CODE REVIEW

**Comment by srkgupta** [comment]
Hi @devinbinnie 

For some reason, this test is not working on the CircleCI and is failing. However when I run this locally on linux, it works fine. Can you please let me know what I might be missing here? 

image

This is what is shown when tests run on CircleCI:

image

**Comment by devinbinnie** [comment]
@srkgupta Thanks for the PR :)
Looks like CircleCI is simply having issues with these particular tests, it probably can't (for some reason) detect if the window is minimized or closed correctly, so what I've done for now is added `.skip` onto the tests so they won't be run in CI.

I've verified that they work on Windows though and you've verified on Linux so I think we can still merge this.

**Review by devinbinnie — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by devinbinnie** [comment]
@srkgupta Can you fix the small lint error? Then I can merge this :)

**Comment by hmhealey** [comment]
That was me. Looks like GitHub's merge conflict resolver leaves those

**Comment by srkgupta** [comment]
Thank you @hmhealey @devinbinnie for all the help.

**Pull request merged**
