### PR TITLE
[MM-38530] Update build to generate universal binaries

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Add universal binaries for Mac users that don't specifically know which architecture they're using.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38530

#### Release Note
```release-note
Added Universal binaries for Mac users
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
Will need to change the mattermod configuration as well for this.

**Review by jwilander — APPROVED** [review]

**Review by Willyfrog — COMMENTED** [review]
will this prevent from building the separate builds? or does generate the three of them?

for the webpage I suggested the universal one, as people won't have to think twice to get a working one, but if people go to github/releases they should have a choice of only the one for their system

**Comment by devinbinnie** [comment]
> will this prevent from building the separate builds? or does generate the three of them?
> 
> for the webpage I suggested the universal one, as people won't have to think twice to get a working one, but if people go to github/releases they should have a choice of only the one for their system

This will generate all 3 of them, so we might need to update the script to pick which one we serve up to mattermost.com. Was going to chat with DevOps about that since we'll also need to update mattermod to make sure the `Build Apps for PR` label still works.

**Review by Willyfrog — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Comment by cpanato** [comment]
i will test cherry pick please ignore :)

/cherry-pick release-5.0

**Comment by devinbinnie** [comment]
> @devinbinnie - Any outstanding documentation work needed for this PR from your perspective?

Nope, backend change

**Pull request merged**
