### PR TITLE
Add eslint-plugin-eslint-comments

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Add eslint-plugin-eslint-comments. It prevents abuse of `eslint-disable` directive.

See https://mysticatea.github.io/eslint-plugin-eslint-comments/ for detail.

**Issue link**
N/A

**Test Cases**
Add unwanted `/* eslint-disable */` comments, then execute `npm run lint:js`. It should report errors.

**Additional Notes**
N/A

### CODE REVIEW

**Comment by esethna** [comment]
Thanks @yuya-oc is this for v4.2?

**Comment by yuya-oc** [comment]
@esethna Not only for v4.2. This doesn’t affect application behavior.

**Comment by hanzei** [comment]
Hey @yuya-oc,

Is this still something we want? If so, would you please merge `master` into your branch?

**Comment by yuya-oc** [comment]
@hanzei Thanks for checking. This still would be an improvement for lint in our reviewing. I'll rebase then merge this.

**Pull request merged**
