### PR TITLE
Improve settings UI

### PR DESCRIPTION
**Pull request by yuya-oc**
For #3. I felt that alignment of the header and "Add new team" is difficult for me.

The current screenshot is here.

### CODE REVIEW

**Comment by jasonblais** [comment]
Fantastic work @yuya-oc! Just tested and works great!

I'll check with @asaadmahmood whether he would have time looking at the CSS for header and "Add new team" placement on the settings page.

Wonderful work!

**Comment by Razzeee** [comment]
This might be a good moment to change the placeholder here https://github.com/yuya-oc/desktop/blob/7f23c496a2ba62b3f6f03f87eceed209af8a1c83/src/browser/settings.jsx#L464 to include `/channels/channelname`
Feeling mixed, about the need to do, but it's nice to choose your default channel and skip the team selection screen

**Comment by jasonblais** [comment]
@Razzeee What does the placeholder value affect? 

Currently if you input `https://pre-release.mattermost.com/core/channels/desktop-app` or something similar as the team URL, the tab will then open up in that channel.

**Comment by Razzeee** [comment]
Exactly

**Comment by yuya-oc** [comment]
Updated with @asaadmahmood's code. https://circleci.com/gh/yuya-oc/desktop/15#artifacts



Some test was failed, so I tested them manually on Windows 10.

I feel the channel URL is a little long to let users input it. Just for avoiding the team selection screen, the team URL is enough. Any thoughts?

**Comment by asaadmahmood** [comment]
We are planning to move towards a modal for the edit/add screens, which would resolve that issue and the styling issue on that last row for add/edit.

**Comment by jasonblais** [comment]
The UI looks excellent! Thank you @asaadmahmood and @yuya-oc!

@Razzeee At the moment it works if a user wants to add `https://pre-release.mattermost.com/core/channels/desktop-app` as the team URL. So I think what we have now is good for this release.

Any testers for OS X and we'll get the last PR for 1.4 merged :tada:

**Comment by yangchen1** [comment]
+1 :) Great work!

**Comment by yuya-oc** [comment]
Thanks all!

**Comment by Razzeee** [comment]
Some small things, I would love to have the X in the top right corner. As shown in the mock in #3 
I still get confused by me having to hit cancel to get back out from channels.

If you're adding a new server the "Add" button will change to "Save" as soon as you type something into the URL. Not sure if that is how it should be.

**Comment by Razzeee** [comment]
It might also need some more padding (?) at the bottom.

electron_2016-09-13_16-39-31

**Comment by jasonblais** [comment]
Thanks @Razzeee! 

1. Agree we should have the "x" to close the settings menu. It was more work to get it in for v1.4/3.4 so it was pushed back. Something we should add for the next version though (I'll create a new issue for us to track)
2. The behaviour to add and edit a team will likely change; we're considering having a modal open up when the action is taken as [mentioned above](https://github.com/mattermost/desktop/pull/278#issuecomment-246411761).
3. Good catch on the padding! @yuya-oc let us know if that would be something easy to fix for v1.4?

**Comment by asaadmahmood** [comment]
3. That would be an easy one to do.

**Comment by yuya-oc** [comment]
Yes, I will add 'padding-bottom: 70px' in further commit.

**Comment by jasonblais** [comment]
Love the teamwork here, great work everyone :)

**Pull request merged**
