### PR TITLE
Fix alignment for 'Add new server' button

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Fix alignment for 'Add new server' button. (+)

v3.7.0 on Mac:
v3 7 0

PR on Mac:
proposal

It looks `Button` component makes the alignment difficult. So I stopped using `Button`. And '+' is a plain text font, so I think it's difficult to layout at "complete center".
Please see the actual alignment.

**Issue link**
https://github.com/mattermost/desktop/pull/540#issuecomment-303734982

**Test Cases**
1. Add two servers at least.
2. Open the main page.
3. See tab bar.
4. The '+' button should work as expected.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/264#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @yuya-oc! 

It's slightly off-center for me on Windows 10 Home

image

Should we also test this on Mac?

**Comment by yuya-oc** [comment]
Not necessary. Screenshots I posted are the result.

I think the font itself for '+' is off-center in English lettering. For example, '+' is slightly off-center on pre-release server (Chrome, Windows 10).

plus-font

**Comment by jasonblais** [comment]
The "+" sign next to the tab bar is noticeably off-center though -- it's almost centered on the channel sidebar

**Comment by yuya-oc** [comment]
https://circleci.com/gh/yuya-oc/desktop/265#artifacts

I used [the glyphicon of bootstrap](http://getbootstrap.com/components/#glyphicons). It's an icon, so probably it would be center-aligned. How about this?

glyphicon-plus

**Comment by jasonblais** [comment]
Looks great, thanks @yuya-oc! 

image

**Comment by yuya-oc** [comment]
Thanks for feedback!

**Pull request merged**
