### PR TITLE
[MM-18007] macOS app reopens closed window on Cmd+Tab

### PR DESCRIPTION
**Pull request by hunterlester**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

On macOS, closed window reopens on Cmd+Tab

**Issue link**

Fixes https://github.com/mattermost/desktop/issues/1068

**Test Cases**
Unfortunately, my test case is skipped until Chromedriver on Mac issue is addressed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3023#c2
Maybe I'm mistaken though, please advise if there's an alternative.
Possibly able to run this kind of test using TestCafe.

**Additional Notes**
For changelog message, do I need conventional commit format? Such as `FEAT:`, `FIX:`?

### CODE REVIEW

**Comment by hanzei** [comment]
@deanwhillier Gentle reminder to review the PR.

**Comment by deanwhillier** [comment]
Thanks @hanzei! There's actually a question on the issue for this PR that needs answering first. @esethna, @andrewbrown00, can you guys please take a look here when you have a minute: https://github.com/mattermost/desktop/issues/1068#issuecomment-559601915?

**Comment by andrewbrown00** [comment]
> Thanks @hanzei! There's actually a question on the issue for this PR that needs answering first. @esethna, @andrewbrown00, can you guys please take a look here when you have a minute: #1068

Added a comment to https://github.com/mattermost/desktop/issues/1068

**Comment by esethna** [comment]
@andrewbrown00 can you help text this to make sure it matches the behavior you defined here? https://github.com/mattermost/desktop/issues/1068#issuecomment-564117499

**Comment by andrewbrown00** [comment]
@hunterlester or @deanwhillier where do I access the build to test this? I checked in **Checks** but I don't see the `store_artifacts` link to download the zips.

**Comment by hunterlester** [comment]
@andrewbrown00 it's in Artifacts tab: https://circleci.com/gh/mattermost/desktop/4405#artifacts/containers/0

**Comment by esethna** [comment]
Reassigning @adamjclarkson for PM review

**Comment by adamjclarkson** [comment]
FWIW - when trying to install [this build](https://4405-43964563-gh.circle-artifacts.com/0/packages/mattermost-desktop-4.3.0-develop-mac.zip) on Mac OS Catalina 10.15.2 I kept getting error message "The Application "Mattermost" can't be opened" after trying to open the unzipped app. 

cant open modal

Just an ok button and no other options. Weird.

Tried checking my security and permissions preferences, no luck. Tried chmod'ing file, no luck. Eventually I found a message board where someone figured out that the Mac Archive Utility caused the problem. They recommended Unarchive utility instead, which I downloaded and installed. And it worked.

**Pull request merged**
