### PR TITLE
WIP MM 13906 - Integrates electron spellckecker

### PR DESCRIPTION
**Pull request by deanwhillier**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
WIP. This PR replaces existing spell checker with electron spell checker that uses native node modules to provide native spell checking.

**Issue link**
[MM-13906](https://mattermost.atlassian.net/browse/MM-13906)

**Test Cases**

**Additional Notes**
Implementing this change properly requires investigation into building native node modules on all supported platforms. Possible solution may involve pre-building native node modules for each platform and including in the repo. An additional ticket will be created and linked here.

Currently builds, packages and runs successfully on latest Mac OS and Ubuntu 64bit.

### CODE REVIEW

**Comment by deanwhillier** [comment]
Ticket to investigate building native node modules on all platforms: [MM-14528](https://mattermost.atlassian.net/browse/MM-14528)

**Comment by svelle** [comment]
> Ticket to investigate building native node modules on all platforms: [MM-14528](https://mattermost.atlassian.net/browse/MM-14528)

To build the 32-bit modules on Fedora the following packages need to be installed:
```
libxkbfile-devel.i686
libX11-devel.i686
```

On Ubuntu 18.04 the following packages are needed:
```
libc6-dev-i386
libxkbfile-dev:i386
```

**Comment by jasonblais** [comment]
@deanwhillier Confirming this is a work in progress, queued for an upcoming sprint?

**Comment by deanwhillier** [comment]
It is, thanks for checking. Has some community involvement as well.

**Comment by deanwhillier** [comment]
Closing this for now. Will be revisited with a new PR in the near future.

**Pull request closed without merging**
