### PR TITLE
Add Mattermost Icon

### PR DESCRIPTION
**Pull request by shin-migami**
Added Icon to the README 💄

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you for the contribution @shin-migami!

Attached is how the README file would look like, and unfortunately the icon doesn't fit the title well.. We'd probably need to update the icon so it's better positioned with the "Mattermost Desktop" text.

While we really appreciate your contribution, we'll not be able to take the pull request at this time.

Please consider taking a look at other open issues on the repo, including [issues labeled for Hacktoberfest](https://github.com/mattermost/desktop/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest), and consider joining our [Desktop community channel](https://pre-release.mattermost.com/core/channels/desktop-app) to meet other contributors and discuss the future of the project.

image

**Comment by shin-migami** [comment]
Will it be alright if the title is included with the icon so that the whole thing is a icon and it's looks nice ??

**Comment by jasonblais** [comment]
Nice suggestion @shin-migami, let me check with the team to see if we'd have an icon that works.

**Comment by shin-migami** [comment]
Thank You @jasonblais for going through the trouble

**Comment by jasonblais** [comment]
Sorry for the delay @shin-migami, I've sent a question to our UX team and will get back here,

Thank you again for your interest!

**Comment by jasonblais** [comment]
Hey there @shin-migami, we can use an image from here: https://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal.png

We could change the README file to display the icon instead of having "Mattermost" text in the title. What do you think?

image

**Comment by yuya-oc** [comment]
@jasonblais The image looks nice, however I think it can't tell that the repository is for desktop app. Any thoughts?

**Comment by jasonblais** [comment]
@yuya-oc True, would your thought be adding the icon but keeping the "Mattermost Desktop" in the title?

Or should we hold off on adding a title for now?

**Comment by shin-migami** [comment]
@yuya-oc @jasonblais We can just add the "Desktop (beta)" as a subtitle to the title then it would serve all purpose. Please give your thoughts about this.

**Comment by shin-migami** [comment]
mattermost

@jasonblais Please share your thoughts on this

**Comment by shin-migami** [comment]
mattermost

@jasonblais Please share your thoughts on this

**Comment by jasonblais** [comment]
Hey @shin-migami, the [Mattermost branding guidelines](https://www.mattermost.org/brand-guidelines/) won't allow us to change the icon itself.

I checked other desktop apps and I generally didn't see an icon associated with them, at least for the ones I checked

**Comment by shin-migami** [comment]
I seem to have overlooked that. I think we should close this PR then.
Thanks for your time.

**Comment by jasonblais** [comment]
Hey @shin-migami and sorry for the back-and-forth here.

If you're not a member, please consider joining our [Desktop community channel](https://pre-release.mattermost.com/core/channels/desktop-app) to meet other contributors and discuss the future of the Desktop project.

**Pull request closed without merging**
