### PR TITLE
test:MM-T817/MM-T818/MM-T819 Zooming in the Menu Bar

### PR DESCRIPTION
**Pull request by codedsun**
#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1901

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
Thanks for the PR @codedsun, looks like the tests are failing in CircleCI. Can you have a look?

**Comment by devinbinnie** [comment]
@codedsun The tests aren't passing on my local instance either, it seems like you might need to wait for the page to be fully loaded before running the shortcut, as it looks like it hasn't loaded in time.

**Comment by codedsun** [comment]
@devinbinnie My text are fixed, but some other text are failing without any changes being done. Please check

**Comment by codedsun** [comment]
@BenCookie95 @devinbinnie Resolved the conflicts, please review when time allows.

**Review by BenCookie95 — APPROVED** [review]

**Comment by codedsun** [comment]
Thanks team 💯

**Pull request merged**
