### PR TITLE
Reset misspelled state after changing spelling language

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Reset misspelled state after changing spelling language.

**Issue link**
#524 

**Test Cases**
See #524. After the step 7, the highlight should be updated a moment later.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/241#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc It looks like the build succeeded but I don't see any download links in the artifacts

image

**Comment by yuya-oc** [comment]
Please expand `circle-artifacts.4SF1sfI/` below "Test Summary". It seems CircleCI behavior was changed.

**Comment by jasonblais** [comment]
Tested on Windows 10
 - spellchecker on/off
 - different languages
 - #524 fixed

All looks good, thanks @yuya-oc!

**Comment by yuya-oc** [comment]
Thanks for testing!

**Pull request merged**
