### PR TITLE
Implement basic autoupdate

### PR DESCRIPTION
**Pull request by Razzeee**
This will add autoupdate for windows and possibly osx via [electron-gh-releases](https://github.com/jenslind/electron-gh-releases)

I can't really work on the OSX side of things.

Windows is done and works, you just need to build an installer and upload them to the github releases. Like I did [here](https://github.com/Razzeee/desktop/releases)

OSX is missing the 'auto-updater.json' and probably the signing, see documentation [here](https://github.com/jenslind/electron-gh-releases/blob/master/docs/2.x/how-to.md#publishing-a-new-release-on-github)
There is also an package to simplify the osx part of the release: https://github.com/jenslind/electron-release

update

### CODE REVIEW

**Comment by it33** [comment]
HI @Razzeee, appreciate your thoughtfulness and your PR here. 

Auto-update is a feature that is definitely desired long term. Right now, we need to focus on code-signing, installers, documentation and a few higher priority fundamentals before auto-update is the top priority. 

Also, we want to be careful about not accepting PRs too early, before features have achieved the full vision of their contributors. 

Would you be open to maintaining a long-running fork of the repo with your auto-update work, so community members can try out the feature, share feedback, and mature the functionality before it's merged into master? 

While it's a little more work to maintain, in our minds it will lead to the highest quality outcome.

**Comment by Razzeee** [comment]
Hey @it33 

> Auto-update is a feature that is definitely desired long term. Right now, we need to focus on code-signing, installers, documentation and a few higher priority fundamentals before auto-update is the top priority.

Your probably refering to #137 
The problem is there is not much I can work on there:
1) needs jenkins access
2) probably can't do it because you need to offer the cert
3) no ftp access to your side
4) can do, but no code signing yet
5) again no ftp access or way to automate it without jenkins access
6) that's a platform feature and not for this repo

So well it seems like I'm out of luck. :( ;)

> Also, we want to be careful about not accepting PRs too early, before features have achieved the full vision of their contributors.

Not sure how this doesn't seem mature enough.  Other then the OSX version missing and the desktop version moving the releases away from github. Which would be nice, but somebody would need to setup a squirrel server for us. One of these servers: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#autoupdater

> Would you be open to maintaining a long-running fork of the repo with your auto-update work, so community members can try out the feature, share feedback, and mature the functionality before it's merged into master?

Can do, but it would be pretty worthless if you can get a server setup on your end. So if that is possible in a timely manner I would like to not do the fork. I'm a branded child regarding server admins getting servers going for open source... So I choose the way we could benefit right now in the PR.

**Comment by it33** [comment]
Thanks @Razzeee, 

Makes sense, 

Highly appreciate your patience, we're trying to get code signing and Jenkins up--we definitely want this. 

Also thanks for [continuing to build](https://github.com/mattermost/desktop/pull/180) as we try to get everything spun up.

**Comment by Razzeee** [comment]
@it33 So code signing and jenkins is done right?
Is there a ticket to install an auto update server?

**Comment by jasonblais** [comment]
Thanks @Razzeee,

We're still looking into [some updates with Windows code-signing](https://forum.mattermost.org/t/windows-desktop-app-v1-3-0/1940/2), and I'll post an update once we know more.

Thanks for your patience, as it will be a great improvement to have for the desktop apps.

**Comment by meilon** [comment]
Please make the auto updater optional. When this [feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/15221058-preprovision-native-client-apps) about adding admin configuration for software deployments in companies gets accepted, companies most likely don't want auto update. That is what software deployment is for. Also, in many companies the users don't have admin rights on their computers and an update would fail anyways on Windows with an installer.

Until the named feature is implemented, please at least add an option to the user config on if to enable the auto update feature.

**Comment by Razzeee** [comment]
There are setups that don't need to hae admin rights. See clickonce etc, haven't really checked how electron does it.

**Comment by meilon** [comment]
On a company computer I want it to be installed for all users on the machine. If it is stored at a location where the user can change the program files, they could also change the proposed way the admin config is set up etc. Another reason to disable auto update is that I don't want 300 clients downloading the same setup and clog our internet access. I know the setup isn't that big, but 50MB x 300 is 15GB that have to go through in the morning of the update. The next reason not to allow auto update: You want to test the update on a few limited machines first and then do the full roll out or continue in steps. 

There are many reasons why auto update should be an optional feature. I'm okay with it if it is there and turned on by default (it's a good thing for private machines), but the admin or end user should decide if it happens or not.

**Comment by jasonblais** [comment]
Hey @Razzeee, I think we've got the desktop app into a state where we can consider taking a pull request that let's users check for updates. Added to v3.5 tag.

We should first carefully consider the design and how it should work, such as whether to use automatic updates, whether to make it optional, and so on. 

Once we have the design nailed down including a clear vision of how it should work, we'd be ready to start on the implementation.

How would you feel about that?

**Comment by Razzeee** [comment]
Sounds good to me. Another thing you need to talk about is having a server,
that knows that there is an update.

**Comment by jasonblais** [comment]
FYI - here's an early draft of a plan for auto-updates if anyone is interested to take a look. https://docs.google.com/document/d/1ITm0ZsRdo0ER_nVcAB31aaBi5CvDXE52OOUGBXHBTx4/edit

If you have any feedback, feel free to add notes and comments on the document or in this thread.

Note that the spec is at an early stage and is subject to change.

**Comment by Razzeee** [comment]
The bot misfired here?

**Comment by jasonblais** [comment]
Sorry for the noise @Razzeee, we've been working on adding a bot to all the mattermost repos, which triggered a few unnecessary notifications

Hope you're doing well! :)

**Comment by Razzeee** [comment]
Doing fine. 
Just wondered what's going on :)

**Comment by jasonblais** [comment]
This PR is covered by #582 

//cc @yuya-oc

**Pull request closed without merging**
