### PR TITLE
fixes several typos

### PR DESCRIPTION
**Pull request by svelle**
**Summary**
This commit fixes several typos in comments and documentation as well as one typo in code for the electron webview spellchecker.

### CODE REVIEW

**Comment by jasonblais** [comment]
Thank you!

@yuya-oc are the build errors something we should worry about?

**Comment by yuya-oc** [comment]
@jasonblais No. Only `'set-spellcheker'` is that, but it's correctly modified.

@svelle Would you solve conflicts? Then it would be ready to merge!

**Comment by svelle** [comment]
@yuya-oc sure I'll do that! I'll post here when I'm done.

**Comment by yuya-oc** [comment]
Thanks!

**Pull request merged**
