### PR TITLE
Fix Digest Mismatch error on Enterprise Linux installations when FIPS…

### PR DESCRIPTION
**Pull request by jonathan-dove**
#### Summary
Added fpm argument to the package.json file to change the hashing algorithm from md5 to sha256. This fixes an issue introduced in RHEL8+ and/or clones where if FIPS mode is enabled rpm digests must be hashed with at minimum sha256 to be allowed to be installed without bypassing security measures put in place by the FIPS standards. 

#### Ticket Link
https://github.com/mattermost/desktop/issues/3190

#### Checklist

- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](https://mattermost.com/contribute/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: RHEL 8, RHEL 9, Rocky9, Rocky8

#### Release Note
```release-note
Modified rpm-digest to utilize sha256 instead of md5 to all for rpm installation on FIPS mode enabled Enterprise Linux systems.
```

### CODE REVIEW

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @jonathan-dove!

**Comment by devinbinnie** [comment]
@toninis Can you check to make sure this doesn't harm our RPM build process?

**Comment by toninis** [comment]
@devinbinnie I need to manually build a rpm package from this PR and test that so this needs to wait a bit . 
Alternatively we can merge and check the nightly builds . 
I might have capacity to test that locally on a box end of week if that's ok 😄

**Comment by devinbinnie** [comment]
> @devinbinnie I need to manually build a rpm package from this PR and test that so this needs to wait a bit . Alternatively we can merge and check the nightly builds . I might have capacity to test that locally on a box end of week if that's ok 😄

Yep we can test locally whenever you have time. Let's do that before we merge. If I can be of help let me know.

**Comment by devinbinnie** [comment]
@toninis Any progress on locally testing this?

**Comment by toninis** [comment]
@devinbinnie I tested the rpm locally and installs . This change only affects the checksum . Once merged we will also check the nightly build repo

**Comment by devinbinnie** [comment]
@toninis Feel free to approve if you think it's ready to merge.

**Review by toninis — APPROVED** [review]

**Pull request merged**
