### PR TITLE
Change window title to Mattermost Desktop (beta)

### LINKED ISSUE #77: Change window title to Mattermost Desktop (beta)
The application window still use 'electron-mattermost' as title yet the project was renamed 'Mattermost Desktop'

### PR DESCRIPTION
**Pull request by mikaoelitiana**
Signed-off-by: Mika Andrianarijaona <mika@tag-ip.com>

Fixes #77

### CODE REVIEW

**Comment by it33** [comment]
Hmm... wondering if this should be "Mattermost Desktop" or just "Mattermost"?

**Comment by it33** [comment]
Hi @mikaoelitiana, also, could we have your help completing a [Mattermost CLA agreement](http://www.mattermost.org/mattermost-contributor-agreement/) so we can add you the approved contributor's list? 

Doing this once will approve you to make PRs to any Mattermost project in future.

**Comment by mikaoelitiana** [comment]
@it33 I will complete the Mattermost CLA agreement first. For the name, I guess Mattermost is the best choice (other chat system don't have the "desktop" as well)

**Comment by yuya-oc** [comment]
@mikaoelitiana Changed window title is included in #79. Could you check also it?

**Comment by mikaoelitiana** [comment]
Ok it's fine with #79. Thanks

Le mer. 16 mars 2016 14:55, Yuya Ochiai <notifications@github.com> a écrit :

> @mikaoelitiana <https://github.com/mikaoelitiana> Changed window title is
> included in #79 <https://github.com/mattermost/desktop/pull/79>. Could
> you check also it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mattermost/desktop/pull/78#issuecomment-197281651>
>
-- 

Mika Andrianarijaona
+261340722394
http://mikaoelitiana.name

**Pull request closed without merging**
