### PR TITLE
Add show window option

### PR DESCRIPTION
**Pull request by kyoshidajp**
Hi.

I added an option to show and set focus to the window whether there are new messages or mention.

---
- [x] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] Execute `npm run prettify` to format codes
- [x] Write about environment which you tested
  - Tested on OS X 10.11.4

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @kyoshidajp for the contribution!!

Just to clarify: when the option is turned on and a user receives a new message or mention, the app will set focus to Mattermost Desktop regardless of which window is on focus at the moment?

Would this also happen if the application is only in the system tray?

**Comment by kyoshidajp** [comment]
@jasonblais Thank you for commenting.

I think so too. I changed not set focus when already set focus.

**Comment by jasonblais** [comment]
Thanks @kyoshidajp again!

Can you provide a little more information on the added option? Is it that Mattermost desktop would get focus whenever a new message or mention is received?

**Comment by kyoshidajp** [comment]
@jasonblais Yes. Mattermost desktop would get focus when a new message or mention is received and the window is not focused. The action would lead to get focus whenever a new message or mention is received.

**Comment by yuya-oc** [comment]
Tested on Win10, works as written.

@kyoshidajp As a whole of your changes, `showWindow` seems ambiguous. For example, how about `showWindowOnNewMessage`?
Then, please check [the agreement](http://www.mattermost.org/mattermost-contributor-agreement/) again. You have to [be listed](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) as an approved contributor.

**Comment by kyoshidajp** [comment]
@yuya-oc thank you for testing my branch.

I changed properties name from `showWindow` to `showWindowOnNewMessage`. And I was listed contributor's page.

**Comment by jasonblais** [comment]
Hi @kyoshidajp, and big thank you for the suggestion and submitting a pull request for it.

I'm not sure how many people would use the setting, and what the end vision for the feature would be.. Therefore, I'm proposing to have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests? 

Please include a link back to this GitHub Issue and feel free to have a link to the branch containing the code.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
[Thanks @kyoshidajp!!](https://mattermost.uservoice.com/forums/306457-general/suggestions/15102828-add-show-and-set-focus-to-the-window-option-on-new)

Again, appreciate the pull request and suggestion, will be interesting to see how others might feel about it

**Comment by jasonblais** [comment]
Thanks @kyoshidajp again for this pull request,

For now, we'll close this pull request and continue to follow the response in the [feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/15102828-add-show-and-set-focus-to-the-window-option-on-new) that you submitted.

Setting focus to the app window when a new message or mention is received is different from the normal app behaviour. Hence, we'd first like to confirm that this will be a useful option to have for many people

**Pull request closed without merging**
