### PR TITLE
Change the app publisher to Mattermost, Inc.

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Fix the app publisher was not changed to Mattermost, Inc.

**Issue link**
#542 

**Test Cases**
- Windows:
After installation, open "Apps and Features".
apps_and_features

- Mac:
Open "About Mattermost" in the menu bar.
about_dialog

- Linux:
Open deb packages with GDebi Package Installer.
deb_maintainer

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/278#artifacts

### CODE REVIEW

**Comment by yuya-oc** [comment]
Yeah, I know what we should do about `Update.exe`, but probably I need to modify `electron-builder` code.

**Comment by jasonblais** [comment]
Cool, do you think that will be a lot of work to try out?

**Comment by yuya-oc** [comment]
Unfortunately I'm not sure. I feel a few days are needed.
What I should do is to run `rcedit` when packaging Windows app. So if I could find the code in `electron-builder`, it would not so hard.

**Comment by jasonblais** [comment]
Okay cool, I'm okay merging this PR since it's ready otherwise, and creating another ticket for `Update`. Would that work?

**Comment by yuya-oc** [comment]
Helpful, thanks!

**Comment by jasonblais** [comment]
Closed #542 and opened a separate issue for `Update`: https://github.com/mattermost/desktop/issues/559

**Pull request merged**
