### PR TITLE
Align add server button in the tab bar vertically, fixes #460

### LINKED ISSUE #460: "+" icon in server tab bar isn't vertically centered
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
"+" icon in server tab bar isn't vertically centered

**Steps to reproduce**

Windows 10; Mattermost server v3.7.0; Mattermost Desktop App 3.6.0

image

### PR DESCRIPTION
**Pull request by jnugh**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Reiterate the new team modal PR. This simply aligns the plus button correctly (by moving it down).

### CODE REVIEW

**Comment by yuya-oc** [comment]
Looks correct.

add_server_button

**Comment by jasonblais** [comment]
@jnugh it looks like there's a build failure in CircleCI 
image

**Comment by jasonblais** [comment]
The PR itself looks good, nicely centered on Windows

image

**Comment by jnugh** [comment]
This makes no sense as I didn't change any JS code.
@yuya-oc can you trigger a retry? Guess this is a false positive.

**Comment by yuya-oc** [comment]
Unfortunately the retry also failed, but it's a false positive. It succeeded in my PC. At least this PR should not affect the tests, so I think it's ready to merge.

**Comment by jasonblais** [comment]
I'm fine to merge this PR since it's not directly related.

Should we fix the issue though? Perhaps through a separate ticket?

**Comment by yuya-oc** [comment]
I feel we don't have to open explicit issues. It's enough by execute tests in local machine when it happens.

**Comment by jasonblais** [comment]
Cool, sounds good

**Pull request merged**
