### PR TITLE
[MM-37661][MM-29878] Brand Updates for Desktop v5.0/MM v6.0

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Added new icons and changed the DMG background to reflect new branding for MM v6.0/Desktop v5.0.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29878
https://mattermost.atlassian.net/browse/MM-37661

#### Release Note
```release-note
Added new branding for Desktop v5.0
```

### CODE REVIEW

**Review by jwilander — APPROVED** [review]

**Comment by matthewbirtch** [comment]
Thanks @devinbinnie I'm sure I can approve this really quickly once I see a build. I didn't see a DMG file in the artifacts list though.

**Comment by devinbinnie** [comment]
> Thanks @devinbinnie I'm sure I can approve this really quickly once I see a build. I didn't see a DMG file in the artifacts list though.

Ahh, whoops. I forgot to do the thing. The thing has been done and a build should show up soon :)

**Review by hmhealey — APPROVED** [review]

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
hey @devinbinnie this is what I'm seeing for Mac:
1. Icons and text are not aligned with the white boxes 
2. There appears to be scrollbars on the window

Screen Shot 2021-08-11 at 12 26 32 PM

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@devinbinnie I just had a look at the mac installer in the latest build. Layout is much better, but I think the window height might be wrong - it's not centering content properly.

**Review by matthewbirtch — APPROVED** [review]
looks great @devinbinnie. Thanks!

**Pull request merged**
