### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Mattermost/mattermost-desktop](https://translate.mattermost.com/projects/mattermost/mattermost-desktop/).

Current translation status:

Weblate translation status
```release-note
NONE
```

### CODE REVIEW

**Review by Bangik — APPROVED** [review]

**Review by ctlaltdieliet — APPROVED** [review]
Removed en.json, shouldn't be in a Weblate PR
Fixed typos/translated Productnames
LGTM

**Comment by ctlaltdieliet** [comment]
Hi @devinbinnie 
any idea why the test is failing?
Also strange that en.json in part of this PR.
Thanks

**Comment by devinbinnie** [comment]
> Hi @devinbinnie any idea why the test is failing? Also strange that en.json in part of this PR. Thanks

Definitely weird about the `en.json` file. Looks like that's causing the test failure since it won't pass `mmjstool`
I'm not sure why the format changed, is there an issue in Weblate perhaps?

**Comment by devinbinnie** [comment]
@ctlaltdieliet Looks like you fixed it :)
Ping me if you need help merging.

**Comment by ctlaltdieliet** [comment]
Hi @devinbinnie,
I'm not authorized to merge. Can you merge this PR?
Thanks

**Pull request merged**
