### PR TITLE
Count for active channel only when window is not focused.

### PR DESCRIPTION
**Pull request by mid0111**
Make unread count of active channel disappear when the channel is focused. (issue #9)
Because I don't have test environment, I test only at Mac OSX.

### CODE REVIEW

**Comment by yuya-oc** [comment]
Why did you add `active` to the arg for `getElementsByClassName()` ?
I checked with Mattermost 1.4 RC2, but `active` class was not contained in the separator.

**Comment by mid0111** [comment]
Sorry, it's my mistake. I am ashamed of myself.

I fixed the mistake, and checked unread count of active channel appeared when it was not focused, and disappeared when it was focused.
But appeared again, after it was not focused again.

So, don't be care about previous commit.
I'll check this later ...

**Comment by yuya-oc** [comment]
JFYI, circleci failed because apt-get failed to download `zip` in `docker build`. It's not your mistake.

**Comment by yuya-oc** [comment]
If the app manages multiple teams, unread counts of active channel disappear at inactive tabs when it's focused.
I think we have to resolve this issue to add features of the PR.

**Comment by mid0111** [comment]
I agree with you.


I don't have any idea how to count unread title for active channel from DOM.

I'm trying to count unread title from notification event of active channel.
But, this approach will make the application complex.
I wonder if there is another good way.

**Comment by mid0111** [comment]
I changed to count unread message of active channel from the desktop notification event.

Then, check about belows at Mac OSX and windos 7.
* Active channel badge disappear when the active channel is focused.
* Active channel badge does not disappear when the another tab is focused.

**Comment by yuya-oc** [comment]
Thanks a lot, however I want to merge #18 first. Because this PR makes large changes for code structure.

**Comment by mid0111** [comment]
OK, I think so too.

**Comment by yuya-oc** [comment]
@mid0111 @ttyniwa Could you check whether app performs as you expect?

**Comment by ttyniwa** [comment]
ok. I'll check it.

**Comment by mid0111** [comment]
Thank you for marge PR.
The unread count is appeared I expected.

However it is not the interest on this issue, I’m worried about the mention count was not disappeared when clicking on the application.

**Comment by ttyniwa** [comment]
I fixed bugs, please see #12 for details.

**Pull request merged**
