### PR TITLE
Add simple validation for Name and URL in the settings page

### PR DESCRIPTION
**Pull request by yuya-oc**
For #181.

Tested on Windows 10. The appearance is below.

It's only for the appearance of html, so I think it's enough if we have one tester. Artifacts are available at https://circleci.com/gh/yuya-oc/desktop/7#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @yuya-oc!

During testing, I expected to be able to click on the 'Add' button, *after which* the error would be shown.

I actually didn't see the `Name is required` on my first read.

Not sure if others have thoughts?

image

**Comment by yuya-oc** [comment]
Ah, surely we didn't define the timing to show validation. I expected the user can't click 'Add' until all input fields are validated. The user can know what is wrong before clicking the button.

**Comment by jasonblais** [comment]
Thanks @yuya-oc, makes sense.

Showing the error message after a user attempts to add the team would be more consistent with the rest of the Mattermost experience.

Would it be a lot of work adding this change?

**Comment by yuya-oc** [comment]
@jasonblais Thanks for feedback. Probably it's not hard, so I'll try later.

**Comment by yuya-oc** [comment]
Updated. The artifacts are here. https://circleci.com/gh/yuya-oc/desktop/10#artifacts

**Comment by jasonblais** [comment]
Tested on Windows 10, looks great. Thank you @yuya-oc !

**Pull request merged**
