### PR TITLE
Upgrade electron-builder

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade electron-builder.

It has [an issue about Linux icon](https://github.com/electron-userland/electron-builder/issues/2577). As a workaround, macOS icon is also used for Linux in this PR.

**Issue link**
#702

**Test Cases**
Download artifacts. Then, check artifacts name, package name, publisher name and icons.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/736#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc Looks like only the Zip packages were uploaded on CircleCI: 
image

**Comment by yuya-oc** [comment]
@jasonblais Thanks to let me know. Artifacts name had been changed by electron-builder. Here is fixed version.

https://circleci.com/gh/yuya-oc/desktop/736#artifacts

**Comment by jasonblais** [comment]
@yuya-oc I'm getting an error when trying to launch the app (`Mattermost 24` is equivalent to `Mattermost`)

image

**Comment by yuya-oc** [comment]
@jasonblais Reproduced also on local build. Probably it's a bug of electron-builder. (similar issue: https://github.com/electron-userland/electron-builder/issues/784)

But possibly it's good time to move to zip (it works). And it's required for auto-updater.

**Comment by jasonblais** [comment]
@yuya-oc Will there be any side effects to the user?

Were we able to use the .dmg files for auto-updates, I forget? I think you mentioned the flow for .dmg files would be similar to Windows .zip files? https://github.com/mattermost/desktop/pull/588

**Comment by yuya-oc** [comment]
@jasonblais I think there are nothing other than filename (of course we should test though).

For mac, dmg and zip are almost same, but they have different purpose in auto-updater context.
- dmg: For initial installation.
- zip: Downloaded and applied by updater. It also can be used manually as well as our tar.gz.

**Comment by jasonblais** [comment]
@yuya-oc So would auto-updates work for .dmg? Or would the user download .dmg initially (if desired), but then .zip files for updates?

**Comment by jasonblais** [comment]
As for using tar.gz or zip files, I'm okay moving to .zip files if there are no changes to the user. Especially since we'll be changing to it anyways soon.

**Comment by yuya-oc** [comment]
auto-updater would work for both of zip and dmg. But they check whether .zip exists on the server. So their difference is just file format (and some extra pictures for appearance of dmg). I'll prepare zip version.

**Comment by yuya-oc** [comment]
https://circleci.com/gh/yuya-oc/desktop/740#artifacts

**Comment by jasonblais** [comment]
@yuya-oc Have confirmed on Mac, no issues found.

@amyblais Please help confirm on Windows?

**Comment by yuya-oc** [comment]
Tested on Ubuntu 16.04. No issue found, and icons are correctly included.

**Comment by jasonblais** [comment]
Thanks all! @yuya-oc we should be good to merge this one.

**Pull request merged**
