### PR TITLE
Enable context isolation for release-4.2.x

### PR DESCRIPTION
**Pull request by deanwhillier**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
This PR turns on Context Isolation for increased security between the loaded MM Webapp and the users underlying OS.

**Issue link**
https://mattermost.atlassian.net/browse/MM-13609

**Test Cases**
Mac: A local build (`yarn run build`) on a Mac is sufficient to test this PR.
Windows: A package needs to be generated locally (`yarn run package:windows`) and then installed from the resulting `./releases/squirrel-windows` (64-bit) folder for notifications to work properly.

Once running:
* make sure you are logged into the same mm server with two different users, one within the running Desktop app.
* with the user not running in the Desktop app, at-mention the user running in the Desktop app in a team/channel other than the one currently open in the Desktop app.

Expected: an OS-level notification popup should show and when clicked, should focus the Desktop app if not already focused and take you to the team/channel the at-mention was posted in.

**Additional Notes**
To verify context isolation is on:
* from the `View` menu, choose `Toggle Developer Tools` to open up the developer tools panel.
* in the `Console` tab of the developer tool panel, copy and paste `document.getElementById("mattermostView0").openDevTools();` next to the blue caret (see pic below) and hit enter. This will open up another developer tools window representing the loaded webapp
* in the `Console` tab of the new developer tools panel, click on the dropdown near the top left of the panel that says `top`. You should see a second item called `Electron Isolated Context`, indicating that context isolation is on (see pic below).

image

image

### CODE REVIEW

**Comment by crspeller** [comment]
@deanwhillier Where are the other changes from the first PR?

**Comment by deanwhillier** [comment]
> @deanwhillier Where are the other changes from the first PR?

* [main.js ln 356](https://github.com/mattermost/desktop/blob/d6829fbdaa96156e1adaab31f0d9b80c1f089079/src/main.js#L356): this was added following 4.2 release and as is technically redundant, happy to backport if preferred.
* [mainWindow.js ln 46](https://github.com/mattermost/desktop/blob/d6829fbdaa96156e1adaab31f0d9b80c1f089079/src/main/mainWindow.js#L46): `webPreferences` was added for Electron 5 upgrade because the defaults changed in that version. Though not needed, I can also backport if preferred.

**Comment by crspeller** [comment]
@deanwhillier Ah... I see somehow we still have not released a new desktop app version with my initial security improvements from 6 months ago. So those are not on this branch.

**Comment by deanwhillier** [comment]
Rebased this PR from `release-4.2` branch to inherit the work from the other PR merged this morning, including fixed tests. @crspeller, @hmhealey, please feel free to re-review.

**Pull request merged**
