### PR TITLE
[MM-38325] Polished up some of the UI elements

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Fixed up some of the UI elements as a few things were misaligned or needed some colours changed.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-38325

```release-note
NONE
```

### CODE REVIEW

**Comment by devinbinnie** [comment]
@matthewbirtch Tried to cover everything listed in the tickets, these are my notes:
- The dropdown icons that I fixed were the little drag handles and the plus button, the other ones all looked fine.
- I did the alignment changes on the mention badges you requested, but it feels like they're sitting too low now.
- I still can't really do anything about the number inside of the badge for the reasons you mentioned, I'm open to ideas about how to fix that if you or anyone else has an idea.
- I'm pretty sure I updated the styles for the badges to be mostly the same now so they should be virtually identical.

**Review by michelengelen — APPROVED** [review]
LGTM!

**Comment by matthewbirtch** [comment]
Nice work @devinbinnie. It's looking good

> The dropdown icons that I fixed were the little drag handles and the plus button, the other ones all looked fine.

Hmm, this still looks a little off to me. If I measure it, the server icon and the drag icon are sitting 1px too low. The other elements in the row seem fine. The plus icon in the Add server row also seems to be 1px too low.

image
image

> I did the alignment changes on the mention badges you requested, but it feels like they're sitting too low now.

I just played with this a bit in the inspector and the only way I could get the number to sit vertically centered is the change `font-size: 9px` instead of 10px. This actually seems to look better and because it's bolder now, it shouldn't be too small. Can we try that on both the tab and dropdown button badges?

**A couple new items I hadn't noticed:**
1. What is dictating the width of the servers dropdown? Is that a fixed width or is it based on the content. The main reason I ask is that it's quite a bit wider than it needs to be.
2/ In dark mode, the unread badges don't have the same color. It looks like the badge color in the tabs and the dropdown button need to be updated to the color that is used in the menu row
image
3. For the unread badge on the dropdown button, it needs to be nudged down by 1px and to the left by 1px. The mention badge position is fine as-is though

**Comment by devinbinnie** [comment]
> Nice work @devinbinnie. It's looking better - a few more things
> 
> > The dropdown icons that I fixed were the little drag handles and the plus button, the other ones all looked fine.
> 
> Hmm, this still looks a little off to me. If I measure it, the server icon and the drag icon are sitting 1px too low. The other elements in the row seem fine. The plus icon in the Add server row also seems to be 1px too low.

Fixed!

> I just played with this a bit in the inspector and the only way I could get the number to sit vertically centered is the change `font-size: 9px` instead of 10px. This actually seems to look better and because it's bolder now, it shouldn't be too small. Can we try that on both the tab and dropdown button badges?

Done!

> 1. What is dictating the width of the servers dropdown? Is that a fixed width or is it based on the content. The main reason I ask is that it's quite a bit wider than it needs to be.

I had a `min-width` of `354px` set on the dropdown. I've removed that and forced a margin between the buttons and the server name on each dropdown menu item of 36px, which should reduce the width while still making sure we have good spacing. Let me know if this works for you.

>    2/ In dark mode, the unread badges don't have the same color. It looks like the badge color in the tabs and the dropdown button need to be updated to the color that is used in the menu row

Done!

> 2. For the unread badge on the dropdown button, it needs to be nudged down by 1px and to the left by 1px. The mention badge position is fine as-is though

Done!

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by matthewbirtch** [comment]
Thanks for resolving most of the issues @devinbinnie!
> Hmm, this still looks a little off to me. If I measure it, the server icon and the drag icon are sitting 1px too low. The other elements in the row seem fine. The plus icon in the Add server row also seems to be 1px too low.

It looks like the checkmark icon might need an adjustment too - it still feels like it's sitting low to me.

image

Also, it looks like the styling of the server dropdown button mention badge and the tab mention bade aren't quite matching. Can we update the server dropdown badge to use `-webkit-font-smoothing: auto;` and adjust so it vertically sits centered like it does on the tab badge? I'm not sure what the cause is but there is something inconsistent between the two.

image

**Review by BenCookie95 — APPROVED** [review]

**Comment by devinbinnie** [comment]
@matthewbirtch Okay I fixed the checkmark thing, as for the badges I made changes to make sure that the CSS is identical, but I still see some positioning issues between the two. I looked at the CSS generated and nothing that I changed made any difference. This is the CSS for each of the badge classes, which are now identical except for positioning requirements.
image
image

**Comment by matthewbirtch** [comment]
> @matthewbirtch Okay I fixed the checkmark thing, as for the badges I made changes to make sure that the CSS is identical, but I still see some positioning issues between the two. I looked at the CSS generated and nothing that I changed made any difference. This is the CSS for each of the badge classes, which are now identical except for positioning requirements.
> image
> image

I have a feeling it's related to line-heights set on parent elements. There are no line-heights being set on the badge span tag itself so there may be something inconsistent inheriting here.

**Comment by devinbinnie** [comment]
> > @matthewbirtch Okay I fixed the checkmark thing, as for the badges I made changes to make sure that the CSS is identical, but I still see some positioning issues between the two. I looked at the CSS generated and nothing that I changed made any difference. This is the CSS for each of the badge classes, which are now identical except for positioning requirements.
> > image
> > image
> 
> I have a feeling it's related to line-heights set on parent elements. There are no line-heights being set on the badge span tag itself so there may be something inconsistent inheriting here.

@matthewbirtch There is a difference, one is using 13.5px and one is using 18px, but I changed them both to 18px and nothing changed. Don't know if it changes for you, I'm working on Windows with no zoom level set.

**Comment by matthewbirtch** [comment]
@also @devinbinnie the `span` itself has pretty different styles applied based on what's in the inspector.

**Dropdown badge span**
```css
.TeamDropdownButton__badge-count > span {
    color: white;
    font-size: 9px;
    padding: 0px 5px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: "Open Sans", sans-serif;
    font-weight: bold;
    letter-spacing: normal;
    -webkit-font-smoothing: antialiased;
}
```

**Tab badge span**
```css
.TabBar .teamTabItem span {
    flex: 0 1 auto;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    text-align: center;
    -webkit-font-smoothing: auto;
}
```

**Comment by matthewbirtch** [comment]
> @matthewbirtch There is a difference, one is using 13.5px and one is using 18px, but I changed them both to 18px and nothing changed. Don't know if it changes for you, I'm working on Windows with no zoom level set.

The `line-height` should be 12px, but it sounds like it's not making a difference for you

**Comment by matthewbirtch** [comment]
@devinbinnie I just removed all styling on the `span` tag and applied the following and it seems to resolve:

```css
.TeamDropdownButton__badge-count {
    background: #F74343;
    border-radius: 8px;
    display: flex;
    align-items: center;
    flex: 0 0 auto;
    padding: 0px 5px;
    color: white;
    font-size: 9px;
    position: absolute;
    top: -4px;
    right: -2px;
    border: 2px solid #efefef;
    height: 12px;
    font-family: 'Open Sans', sans-serif;
    font-weight: bold;
    -webkit-font-smoothing: auto;
    line-height: 12px;
    box-sizing: unset;
}
```

I think the problem was `box-sizing` was getting set by something

**Comment by devinbinnie** [comment]
> @devinbinnie I just removed all styling on the `span` tag and applied the following and it seems to resolve:
> 
> ```css
> .TeamDropdownButton__badge-count {
>     background: #F74343;
>     border-radius: 8px;
>     display: flex;
>     align-items: center;
>     flex: 0 0 auto;
>     padding: 0px 5px;
>     color: white;
>     font-size: 9px;
>     position: absolute;
>     top: -4px;
>     right: -2px;
>     border: 2px solid #efefef;
>     height: 12px;
>     font-family: 'Open Sans', sans-serif;
>     font-weight: bold;
>     -webkit-font-smoothing: auto;
>     line-height: 12px;
>     box-sizing: unset;
> }
> ```
> 
> I think the problem was `box-sizing` was getting set by something

Thanks @matthewbirtch, should be all good now.

**Review by matthewbirtch — APPROVED** [review]
Looks good now @devinbinnie!

**Pull request merged**
