### PR TITLE
WIP: GH-623 Rename variables team(s) to server(s)

### PR DESCRIPTION
**Pull request by thepill**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Rename variables from "team" to "server" in source code. see #623 

**Issue link**
https://github.com/mattermost/desktop/issues/623

**Additional Notes**
Tested on macOS 10.14.2 against mattermost server version 5.6.1

### CODE REVIEW

**Comment by thepill** [comment]
Im unsure about the file `src/browser/webview/mattermost.js` and all the documentation/other files wich includes the phrase "team".
Should they also be updated?

**Comment by thepill** [comment]
@yuya-oc I updated the config migration functions and replaced `team/s` with `server/s` in `src/browser/webview/mattermost.js`. 
As part of update the documentation i had the feeling to leaf this to someone who knows more about the documentation and could better decided what have to be updated in terms of team/s -> server/s

**Comment by thepill** [comment]
@yuya-oc some tests are failing because of the config files wich are generated on test run. Could you check this? Do i have to create new test-config-files?

**Comment by yuya-oc** [comment]
@thepill Sorry, I had a mistake. We don't have to change `src/browser/webview/mattermost.js` because its `teams` is based on webapp's DOM.

Generally you don't have to create a new config file. In this case, there are some problem in the migration function. Would you try to add tests about `upgradeV1toV2()` in `test/specs/settings_test.js`?

**Comment by yuya-oc** [comment]
There were some error in migration functions. That caused failing tests such as "should show index.html when there is config file".

So I added tests for them, would you check that?

**Comment by yuya-oc** [comment]
In Mocha.js, using `describe.only()` instead of `describe()` allow us to execute only a desired test case.

By using it, would you check whether `describe.only('common/settings.js')` passes? Once the test case passes, I believe that other tests would be also fixed.

**Comment by thepill** [comment]
> In Mocha.js, using `describe.only()` instead of `describe()` allow us to execute only a desired test case.
> 
> By using it, would you check whether `describe.only('common/settings.js')` passes? Once the test case passes, I believe that other tests would be also fixed.

Fails with:

```js
  common/settings.js
    1) should upgrade v0 config file to v1 config file
    2) should upgrade v1 config file to v2 config file
    ✓ should merge servers with buildConfig.defaultServers


  1 passing (60ms)
  2 failing

  1) common/settings.js
       should upgrade v0 config file to v1 config file:
     Error: pastDefaultPreferences['1'].version is not equal to 1
      at upgradeV0toV1 (src/common/config/upgradePreferences.js:13:11)
      at Context.it (test/specs/settings_test.js:15:22)
      at process.topLevelDomainCallback (domain.js:121:23)

  2) common/settings.js
       should upgrade v1 config file to v2 config file:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.equal (test/specs/settings_test.js:62:34)
      at process.topLevelDomainCallback (domain.js:121:23)

```

**Comment by hanzei** [comment]
@thepill Would you please merge `master` into your branch? Then we can see if the test pass.

**Comment by thepill** [comment]
> @thepill Would you please merge `master` into your branch? Then we can see if the test pass.

@hanzei tests are failing even with master merged on my local environment

**Comment by hanzei** [comment]
Would you just push your local changes? Then we are all on the same page.

**Comment by thepill** [comment]
@hanzei pushed

**Comment by yuya-oc** [comment]
@thepill After calling `upgradeV1ToV2()`, I think the generated v2 config discarded other parameters of existing config. By merging the latest master,  now you can use a debugger task, "Mocha Tests" in VSCode.

**Comment by thepill** [comment]
@yuya-oc with master merged much more tests are failing (like `should show index.html when there is config file`). I think it would be better if some who has more experience than me to take a lot at the errors. Currently i cant really say when what function is called/used and needs wich test-config

**Comment by yuya-oc** [comment]
@thepill In my investigation, those tests are failing due to `upgradeV1toV2()` implementation. First, would you consider to pass test cases of `settings_test.js`? It's okay to ignore other test files for now.

**Comment by thepill** [comment]
@yuya-oc even `upgradeV0toV1` is failing because the settings object has just a `url` property and nothing more, but the test `should upgrade v0 config file to v1 config file` checks even more properties than just the url - currently i would have to change a lot on how the preferences are converted to the newer versions, but this cant be the right way...

**Comment by esethna** [comment]
@deanwhillier how did you want to handle this PR?

**Comment by deanwhillier** [comment]
@esethna, I'll take a closer look and get back. :)

**Comment by deanwhillier** [comment]
Update: Just getting the MSI/GPO stuff out the door as a fair amount of related code is getting tweaked to support it.

**Comment by hanzei** [comment]
Hey @deanwhillier,

Can you please provide some next steps for this? The amount of merge conflicts accumulate.

**Comment by deanwhillier** [comment]
@thepill, sincere apologies for the delay in getting back to this. We had to do a ton of work to upgrade Electron, implement some additional security hardening and add in a few additional key features for the v4.3 release. A fair amount has changed since you did the initial PR for this effort. I'm wondering if you are still interested in looking into this? It would likely need a new pass given all the changes, but I can then help with figuring out the final pieces.

Please let us know either way and then we can figure out next steps! Thanks for your initial contribution and again, apologies for the delay!

**Comment by esethna** [comment]
@thepill hope youre doing well. If you're interested in finishing off this PR let us know, otherwise we can close it. cc// @hanzei

**Comment by deanwhillier** [comment]
Again, thanks @thepill! I'm going to close this PR as a lot has changed since this was initially worked on, so it's probably simpler to start over. I'll set the original issue as up for grabs, so please feel free to pick it up again if you'd still like to work on this!

**Pull request closed without merging**
