### PR TITLE
Add GPO Template for controlling the upcoming Auto Updater

### PR DESCRIPTION
**Pull request by JtheBAB**
Before submitting, please confirm you've
 - [X] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [X] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [ ] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
This GPO template allows Windows Domain Administrators to control the upcoming Auto Updater feature. Pull requested by @wget 

Now as new branch and not the master branch of my fork.

**Issue link**
„Fixes“ #873

### CODE REVIEW

**Comment by yuya-oc** [comment]
Just curious, should we have a document about .adml and .admx? (Because I'm merely not familiar with Group Policy.)

**Comment by JtheBAB** [comment]
About the files --> see https://community.mattermost.com/core/pl/c34howw74frnpd6gkeoxg7eirw

I think it should be part of the docs.mattermost.com

**Comment by wget** [comment]
Link to the documentation: https://github.com/mattermost/docs/pull/2487

**Comment by esethna** [comment]
@yuya-oc @JtheBAB @wget are we blocked on anything to get this PR merged?

@yuya-oc what's involved in building the logic to support this?

**Comment by wget** [comment]
@esethna Actually, I wanted to port all the GPO features and have make a pull request with all of them in one shot instead, but that's okay, we can merge this one.

**Comment by JtheBAB** [comment]
I am not blocked :)

**Pull request merged**
