### PR TITLE
[MM-40233] Swap names for dark/light tray icons on Linux and Windows

### PR DESCRIPTION
**Pull request by tboulis**
#### Summary
Rename tray icon images so that `dark` theme has dark icon tray image and `light` theme has light tray image.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-40233

#### Checklist
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](https://mattermost.com/contribute/)
- [x] executed `npm run lint:js` for proper code formatting (does not apply)

#### Device Information
This PR was tested on:
- PC, Ubuntu 22
- Macbook pro, Macos 12.4

Screenshot from 2022-06-30 20-53-42
Screenshot from 2022-06-30 20-54-33

> Windows
light
dark

#### Release Note
```release-note
Swap dark and light theme tray icons on Linux and Windows
```

### CODE REVIEW

**Review by devinbinnie — CHANGES_REQUESTED** [review]
Thanks @tboulis.

One issue that came up is that now using the "System default" option causes the icons to be inverse to what they should be.

We'll need to make a change to ensure that the "System default" option uses the correct icon (ie. if the system is in dark mode it should use the light icon and vice-versa)

**Review by nevyangelova — APPROVED** [review]
LGTM, tested locally and worked as expected.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @tboulis!

**Pull request merged**
