### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by JeffResc**
Before submitting, please confirm you've
 - [X] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [X] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [ ] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

This pull request optimizes the images found in the repository using lossless compression. This means that the image quality will not be degraded. This will mean less space taken up by images along with faster loading times when viewing them. The overall file size has been reduced by around 45%.

**Issue link**

N/A

**Test Cases**
N/A

**Additional Notes**
N/A

### CODE REVIEW

**Comment by Willyfrog** [comment]
@andrewbrown00 you probably have a better 'eye' for this than I do

**Comment by andrewbrown00** [comment]
> @andrewbrown00 you probably have a better 'eye' for this than I do

Will do @Willyfrog, is there a `test server` for this PR? I don't see the label to add it...

**Comment by Willyfrog** [comment]
> > @andrewbrown00 you probably have a better 'eye' for this than I do
> 
> Will do @Willyfrog, is there a `test server` for this PR? I don't see the label to add it...

on desktop there is no test server as such, but you can grab the built version from circleci, I've restarted the job as it failed for a flaky test, but once it passes should be here: https://app.circleci.com/pipelines/github/mattermost/desktop/1472/workflows/7e322c65-f059-45ff-8849-3f171e7f640c
in the `store_artifacts` block and there you click on artifacts, let me know if you can't find it and I'll send a build your way.

**Comment by jasonblais** [comment]
As noted in https://github.com/mattermost/desktop/pull/1392 and https://github.com/mattermost/docs/pull/4007, we'll close the PRs due to complexities found during the reviews:
- The changes are undone every time the images are edited. A more efficient approach would be to include image optimization as part of our build process. Something we may look at long term
- We don't unfortunately have a good way to evaluate the changes, other than reviewing the images one by one

For pull requests greater than 20 lines of code, a Help Wanted ticket is recommended to increase the likelihood of it getting merged into the core product. More on the process can be found here: https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/

If you have any questions or suggestions about the contribution process, let us know! We are always looking to improve.

Jason

**Pull request closed without merging**
