### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade dependencies.

**Issue link**
#805 

**Test Cases**
a. General usecases of React UI (Almost covered by CircleCI)
b. Modal to add a new server (Almost covered by CircleCI)
c. Spellchecker
d. Animation (Hovering URL, "Saving..." indicators of Settings Page)

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/901#artifacts

### CODE REVIEW

**Comment by yuya-oc** [comment]
For now, I haven't seen significant issues on Windows 10.

@jasonblais @esethna Wondering if you could take a little look.

**Comment by jasonblais** [comment]
I've downloaded this on my Mac now, looks good so far. Will post here if I find any issues.

**Comment by yuya-oc** [comment]
@jasonblais @esethna For now, I think we didn't get significant issues on this. If there is missed problem, we can get later. How about?

**Comment by jasonblais** [comment]
Works well for me. @esethna can you help sign off as well if you haven't seen issues?

**Comment by esethna** [comment]
Looks good on my windows machine

**Comment by yuya-oc** [comment]
Thanks all!

**Pull request merged**
