### PR TITLE
Update NOTICE.txt

### PR DESCRIPTION
**Pull request by danmaas**
(this is the automated NOTICE.txt update for April 2019)

- Copyright info updates

### CODE REVIEW

**Comment by hanzei** [comment]
@amyblais Is this ready to merge?

**Comment by jasonblais** [comment]
Merging

**Comment by jasonblais** [comment]
Actually, I no longer have merge permissions on this repo, @hanzei can you help merge?

**Comment by hanzei** [comment]
Nope. I don't have the permission either. I've asked Chris to grant me the permission.

**Comment by hanzei** [comment]
@jasonblais Figured out why we where not able to merge. PR in this repository require two approvals to be merged. :man_facepalming:

**Pull request merged**
