### PR TITLE
test: Added test for back and forward in history menu

### PR DESCRIPTION
**Pull request by codedsun**
#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1892

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [ ] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [ ] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE

```

### CODE REVIEW

**Comment by codedsun** [comment]
image

Finally....


@M-ZubairAhmed @devinbinnie need shortcuts to open the history menu item as I am on mac os I can't figure out

**Comment by codedsun** [comment]
Ok this will not pass as teams and channels are not setup in CI.

**Comment by devinbinnie** [comment]
@codedsun Looks like we have a couple lint errors to fix, I've updated the branch so that the MM server should exist in CI, but these need to pass first:
```
/root/mattermost-desktop/e2e/specs/menu_bar/history_menu.test.js
  44:80  error  Expected parentheses around arrow function argument  arrow-parens
  47:76  error  Expected parentheses around arrow function argument  arrow-parens
```

**Comment by codedsun** [comment]
@devinbinnie Updating in a minute

**Comment by codedsun** [comment]
Finally @devinbinnie 
image

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @codedsun!

**Comment by codedsun** [comment]
@Willyfrog please review when time allows. Thanks

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks!

**Comment by codedsun** [comment]
Thanks team 💯

**Pull request merged**
