### PR TITLE
integrating WIP languages

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Integrating the WIP-translations
#### Checklist
- [X] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [X] completed [Mattermost Contributor Agreement](https://mattermost.com/contribute/)
#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by ctlaltdieliet** [comment]
cc @lieut-data

**Review by lieut-data — APPROVED** [review]
I need to double check that the desktop app only lists supported languages. @devinbinnie, do you know if this is the case already?

**Comment by devinbinnie** [comment]
> I need to double check that the desktop app only lists supported languages. @devinbinnie, do you know if this is the case already?

Yes, we have a supported languages list here: https://github.com/mattermost/desktop/blob/master/i18n/i18n.ts
Do we want to add the new ones we've added to that list?

**Comment by lieut-data** [comment]
> > I need to double check that the desktop app only lists supported languages. @devinbinnie, do you know if this is the case already?
> 
> Yes, we have a supported languages list here: https://github.com/mattermost/desktop/blob/master/i18n/i18n.ts Do we want to add the new ones we've added to that list?

No need to update: we're going to start committing the WIP languages to the desktop app, but we wanted to avoid these showing up in the UI. Thanks!

**Review by devinbinnie — APPROVED** [review]
Thanks for the work on this guys :)

**Pull request merged**
