### PR TITLE
[MM-30713] Stop Linux and Windows app from minimizing/hiding without user warning

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Many Linux users have reported that the app doesn't obey closing rules as they would normally expect, so we've refined the way the app closes on Linux and added some dialog boxes to inform the user of what happens when they close the main window:

- Upon pressing X, if the 'Leave app running in notification area when application window is closed' is checked, a dialog box will pop up telling the user that the app will still be running even if the window is closed. If 'Don't show again' is checked (it is by default) then the user will not see that message again.
image

- If the above setting is NOT checked, the user will see a dialog box asking them whether they really want to close the app permanently. If they reply 'Yes', the app is quit. If they reply 'No', nothing happens. If the 'Don't ask again' box is check and the user replies yes, they will not see the dialog again.
image

Additionally, the 'Leave app running in notification area when application window is closed' checkbox is now false by default on Linux, so it will need to be enabled before minimizing to tray will work correctly.

I've also mimicked the same behavior on Windows to give users the option to turn that on.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30713

#### Release Note
```release-note
Updated Linux closing behaviour to allow the app to close complely when pressing X.
Changed the default setting for 'Leave app running in notification area when application window is closed' on Linux to 'false'
```

### CODE REVIEW

**Comment by esethna** [comment]
@devinbinnie is there a need for the dialog/user prompt at all? Can't we just default the "Leave app running in notification area when application window is closed" to false on Linux so the app quits with the "x", and let the user change that setting if they so desire? We don't have this prompt on windows so I'm not sure why it might be needed here? 

Also, wondering if the other scenarios of quitting the app were fixed in this PR?
image

**Comment by devinbinnie** [comment]
@esethna I've added the dialog box just as a safeguard for anyone who might not be aware of the settings. It appears that some users were not aware that the app was still running in the background so I wanted to make sure that users were aware almost 100% of the time. It used to be a pretty common practice to show a box like that even on Windows, so I don't really think it's too invasive.

All the cases above are captured either by the dialog box, or will ensure the app is quit.

**Comment by esethna** [comment]
Thanks @devinbinnie, glad we captured all those cases. My opinion would be that we probably don't need the dialog box, or at least in the case of the new default setting (app quits) we don't need the dialog box. @matthewbirtch any thoughts from your end?

**Comment by devinbinnie** [comment]
> Thanks @devinbinnie, glad we captured all those cases. My opinion would be that we probably don't need the dialog boxes, or at least in the case of the new default setting (app quits) we don't need the dialog box. @matthewbirtch any thoughts from your end?

I think that's a good reason for needing the dialog box, since users may not immediately expect the new behaviour. 2/5 personally.

**Comment by matthewbirtch** [comment]
> Thanks @devinbinnie, glad we captured all those cases. My opinion would be that we probably don't need the dialog box, or at least in the case of the new default setting (app quits) we don't need the dialog box. @matthewbirtch any thoughts from your end?

I don't have a strong opinion either way. It's definitely not something as common anymore. Having said that Adobe does do something similar on Mac with their creative cloud since it just sits in the menubar (not in the doc).

image

Out of curiosity, is it only Linux users who have brought this up? Just wondering why we're proposing it only on Linux.

**Comment by devinbinnie** [comment]
> > Thanks @devinbinnie, glad we captured all those cases. My opinion would be that we probably don't need the dialog box, or at least in the case of the new default setting (app quits) we don't need the dialog box. @matthewbirtch any thoughts from your end?
> 
> I don't have a strong opinion either way. It's definitely not something as common anymore. Having said that Adobe does do something similar on Mac with their creative cloud since it just sits in the menubar (not in the doc).
> 
> 
> 
> Out of curiosity, is it only Linux users who have brought this up? Just wondering why we're proposing it only on Linux. Is this because it is a deviation from the default Linux behavior for closing apps?

It's on Windows as well.

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by devinbinnie** [comment]
@esethna @matthewbirtch Are we good to merge or did you want additional changes?

**Comment by matthewbirtch** [comment]
@devinbinnie is there anything we can do to clean the dialogs up a bit? They look a bit rough to me. The message content in the dialog looks to be too close to the top and needs some padding. Not sure if this is just using native OS dialogs though.

Also, comparing the two provided screenshots, one of them has a bold 4-line title with a centered line of text under it. Is it possible to avoid the bold title?

image

image

Maybe we can also adjust the messages so we don't need a title and a detail:

`Upon closing the Mattermost window, it will continue to run in the system tray. This can be disabled in the Settings.`

`Are you sure you would like to close Mattermost? You will no longer receive notifications for messages. If you wish to minimize to the system tray instead, you can enable this in the Settings.`

**Comment by devinbinnie** [comment]
> @devinbinnie is there anything we can do to clean the dialogs up a bit? They look a bit rough to me. The message content in the dialog looks to be too close to the top and needs some padding. Not sure if this is just using native OS dialogs though.
> 
> Also, comparing the two provided screenshots, one of them has a bold 4-line title with a centered line of text under it. Is it possible to avoid the bold title?
> 
> image
> 
> image
> 
> Maybe we can also adjust the messages so we don't need a title and a detail:
> 
> `Upon closing the Mattermost window, it will continue to run in the system tray. This can be disabled in the Settings.`
> 
> `Are you sure you would like to close Mattermost? You will no longer receive notifications for messages. If you wish to minimize to the system tray instead, you can enable this in the Settings.`

@matthewbirtch The look and feel of the dialogs I can't do anything about, those are native OS dialogs for Kubuntu, so they all look like that :P

I can, however, update the messages.

**Comment by esethna** [comment]
@devinbinnie just to confirm, what OS's will see this?

+1 to avoiding the bold title or if we are stuck with native styling, can we rejigging the text in the various fields/leave some fields blank so the bolding doesn't occur? 

For the first one, let's update text to: "Mattermost will continue to run in the system tray. This can be disabled in the Settings."

For the second one: "Are you sure you want to quit? You will no longer receive notifications for messages. If you want to leave Mattermost running system tray, you can enable this in the Settings." and then get rid of the "Are you sure you would like to close Mattermost" line

**Comment by devinbinnie** [comment]
> > Thing is that if we change it on one OS, another one could have a different styling. I think we should keep the positioning of message and description as they are to be in line with what Electron expect. Each Linux WM is going to look different, so I don't want to change things to satisfy one of them. 3/5 on this.
> 
> That's fair @devinbinnie. Can you share an updated screenshot of Windows for UX and PM review?

I'll generate some builds so you can play with the functionality and see how it looks on your local machine.

**Review by esethna — CHANGES_REQUESTED** [review]
Thanks Devin. 

1. It looks like the default on Windows is to quit on the close button? I don't think we should change that default on Windows, just on Linux.

image

2. The checkbox above ^ is greyed out (in a disabled state) so I can't click it

3. Also notice some UI oddities:
- check mark is squiggly
- "Close Application" header is not aligned (could just say "Mattermost")
- Don't ask again text is not aligned with checkbox

image

**Comment by devinbinnie** [comment]
> 1. It looks like the default on Windows is to quit on the close button? I don't think we should change that default on Windows, just on Linux.
> 2. The checkbox above ^ is greyed out (in a disabled state) so I can't click it

This is definitely not the default, I just blew out my configuration and it correctly made sure the checkbox wasn't checked.

> 3. Also notice some UI oddities:
> 
> * check mark is squiggly
> * "Close Application" header is not aligned (could just say "Mattermost")
> * Don't ask again text is not aligned with checkbox
> 
> image

Unfortunately these are all Electron issues. I can change the header to Mattermost but everything else is managed using Electron's `dialog` library, which I guess they haven't tested thoroughly on Windows 11 yet.

**Comment by esethna** [comment]
@devinbinnie I'm still seeing the issue where the app doesn't seem to be running in the taskbar if I close it with the "x" (even though it's running in the tray), see Slack as an example: 
image

Did we have a separate ticket for this? ^

Looks good otherwise ✅

**Pull request merged**
