### PR TITLE
Show uncaughtException as an internal error and quit the app

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
When an uncaught error occurred, the error log is saved to `AppData\Roaming\Mattermost\uncaughtException-*.txt`. Then a dialog would pop up to notice it.

error_dialog

When the user click "Show detail", the file is opened in the default text editor.

```sample.txt
Application: Mattermost 3.7.1
Platform: Windows_NT 10.0.15063 x64
Error: test error
    at Timeout.setTimeout [as _onTimeout] (C:\Users\yuya-oc\git\mattermost-desktop\src\main_bundle.js:7781:11)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

Usually the error is unrecoverable, so the application should finish soon.
https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly

**Issue link**
#625 

**Test Cases**
- General use cases. The error should NOT appear.
- Check text messages.

**Additional Notes**
CircleCI is delaying...

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc Do you want me to test something here? Also, do we currently show this error dialog, or is this adding it?

**Comment by yuya-oc** [comment]
@jasonblais Like Electron upgrading, please use for several days. The dialog should not appear frequently. https://circleci.com/gh/yuya-oc/desktop/438#artifacts

Currently the application shows such errors only in command line console. So users can't know them even when a critical error happens. Then the application continues to work at such bad situation without quitting.

**Comment by jasonblais** [comment]
Sounds good, I'll use the app and post here if there are any issues.

What, if any, can we change for the dialog design and text?

**Comment by yuya-oc** [comment]
We can change only texts, button labels and icon. The event handler must behave as a synchronous function. In this case, only [`dialog.showMessageBox()`](https://electron.atom.io/docs/api/dialog/#dialogshowmessageboxbrowserwindow-options-callback) and [`dialog.showErrorBox()`](https://electron.atom.io/docs/api/dialog/#dialogshowerrorboxtitle-content) are applicable.

**Comment by jasonblais** [comment]
@MusikPolice Yeah, we'll have Asaad's help with UI mockups for this, #609 and #611

**Comment by yuya-oc** [comment]
Thanks for reviewing. Electron's `dialog.showMessageBox()` uses native modal dialog for each platform. Samples are below.

macOS:
macos

Ubuntu 16.04
ubuntu1604

**Comment by MusikPolice** [comment]
@yuya-oc the native modal looks perfect.

**Comment by yuya-oc** [comment]
@jasonblais Are there any feedback?

**Comment by jasonblais** [comment]
@yuya-oc is there a way for the user to reopen the app via this dialog? E.g. something like attached

image

**Comment by yuya-oc** [comment]
1. A whitespace exists after `\n\n`. Is it intended?
2. Yes.
3. (O) is added by Electron, so I think it's standard. I will check other apps.
4. Possible.

Unfortunately I found an important issue for this. On Windows, it seems the app can't show the dialog when a problem actually happens. However strangely, the app is launched from command line, the dialog properly appears. So I couldn't notice the problem. I need to inspect Electron.

**Comment by jasonblais** [comment]
@yuya-oc 

1 - Unintentional. Should read `The Mattermost app quit unexpectedly. Click “Show Details” to learn more.\n\n Internal error: {error}`

4 - Let me know and I can create a ticket for later

> Unfortunately I found an important issue for this. On Windows, it seems the app can't show the dialog when a problem actually happens. However strangely, if the app is launched from command line, the dialog properly appears. So I couldn't notice the problem in dev mode. I need to inspect Electron.

I see. We can also create a separate ticket for Windows for later.

**Comment by yuya-oc** [comment]
@jasonblais Updated texts. https://circleci.com/gh/yuya-oc/desktop/467#artifacts

3. I checked Gedit, the default text editor of Ubuntu desktop. It shows brackets for each button. Unfortunately Electron doesn't do that automatically.

4. It's easy by calling `app.relaunch()` when the button is pressed.

I didn't write in the previous comment though, the problem means that the app silently finishes if a problem actually happened. Is it acceptable? Of course, the report file is written in the data directory.

**Comment by jasonblais** [comment]
1/2: Great! Thanks Yuya
3: Okay. I think this is okay for now, since fewer people use Linux.
4: > It's easy by calling app.relaunch() when the button is pressed.

Is this something we want to consider for this PR, or do I create an improvement ticket for later? 

----

> I didn't write in the previous comment though, the problem means that the app silently finishes if a problem actually happened. Is it acceptable? Of course, the report file is written in the data directory.

Will the user see the dialog?

**Comment by yuya-oc** [comment]
@jasonblais 
4. We can consider it in this PR. However in that case, we need to consider the order of buttons. For example, `Show detail, OK, Reopen` like macOS?

> I didn't write in the previous comment though, the problem means that the app silently finishes if a problem actually happened. Is it acceptable? Of course, the report file is written in the data directory.

It was my misunderstanding. The actual problem was to call `fs.writeFileSync(2)`. So I removed that statement. Now this PR works on all platforms.

**Comment by jasonblais** [comment]
@yuya-oc 
4. Yeah, that would be great. Agree on order, let's have it `Show Details / OK / Reopen`. (Note that both words in `Show Details` should be capitalized.)

If we add it, propose we modify the text to `The Mattermost app quit unexpectedly. Click “Show Details” to learn more or "Reopen" to open the application again.\n\n Internal error: {error}`

**Comment by yuya-oc** [comment]
Updated: https://circleci.com/gh/yuya-oc/desktop/477#artifacts

Test build: https://circleci.com/gh/yuya-oc/desktop/480#artifacts This build shows a test error 10 seconds later.

macOS:
osx-error

Ubuntu:
ubuntu-error

**Pull request merged**
