### PR TITLE
MM-31882 - Add CodeQL check

### PR DESCRIPTION
**Pull request by srkgupta**
**Summary**
Added step to run automated CodeQL checks. Once this file is merged, the codeql checks will automatically be performed on new pull requests to master branch.

**Issue link**
https://mattermost.atlassian.net/browse/MM-31882

**Test Cases**
N/A

**Additional Notes**
None

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
It is great to have tools like this!

**Review by devinbinnie — APPROVED** [review]

**Comment by deanwhillier** [comment]
@srkgupta, should this also be reviewed by someone else on the security team?

**Comment by srkgupta** [comment]
Hi @deanwhillier

Yes. I got it reviewed from Juho on mattermost-server repo. Please check this pull request :

https://github.com/mattermost/mattermost-server/pull/16661

I am just implementing the same changes across different repos. Hence I did not ask for security review on each and every PR

**Review by deanwhillier — APPROVED** [review]

**Pull request merged**
