### PR TITLE
check the system activity and send activity messages to webapp

### PR DESCRIPTION
**Pull request by granovsky**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Monitor system activity and keep user online 

**Issue link**
https://github.com/mattermost/mattermost-server/issues/7721

**Test Cases**

**Additional Notes**
required wabapp support (https://github.com/mattermost/mattermost-webapp/pull/2512) and server fix (https://github.com/mattermost/mattermost-server/pull/10458)

### CODE REVIEW

**Comment by esethna** [comment]
Hi @granovsky, highly appreciate you submitting this PR,

For context: an internal effort for this feature was recently started and is near completion - the `Up for grabs` label was unfortunately not removed due to oversight on our part. 

After reviewing you work in depth and discussing internally we have identified some issues with the approach taken here that we are attempting to solve in the PRs we have open (currently work in progess): https://github.com/mattermost/desktop/pull/945

Specifically:
- Pushing updates from the main process to the renderer process allows for more flexible updates to the renderer process for relevant user activity outside the defined update interval.
- We are using this ticket to introduce a Desktop <-> Webapp communication bridge to open the door for more direct, controlled interaction between both vs. the existing passive monitoring of the Webapp by the Desktop App.
- To address performance concerns, we have decided to utilize the existing websocket connection for communicating user activity to the server with less frequency instead of using existing REST API endpoints. 

Given the above, we are going to close your PRs for this feature. We really appreciate the work you did and we'll be reaching out via email to send you some Mattermost swag. We hope you're still keen on picking up [more Help Wanted tickets](https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+help+wanted+label%3A%22Up+For+Grabs%22) in the future.

If you'd like to discuss further you can reach out to me on our https://community.mattermost.com/contributors team at @eric

**Comment by granovsky** [comment]
Hey @esethna, thanks for reply. Got it. Looking forward for the away status issue fixed.

**Comment by granovsky** [comment]
Hey @esethna @deanwhillier!
More than a month passed since you closed this PR in favor of not so simple but proper solution. I see that all works according the problem are frozen and we continue to suffer from the incorrect status issue. Is there an ETA when we could expect it to be fixed? Or maybe it's possible to make a quick temporary fix for that?
Thanks.

**Comment by esethna** [comment]
@granovsky we are getting back to this this week. It was stalled as we were focusing on pushing out the MSI installer for desktop, this is next on the queue.

**Comment by granovsky** [comment]
@esethna Thanks a lot for update. We are waiting for this fix very much.

**Comment by j5ingh** [comment]
@esethna Any update on this issue?

**Pull request closed without merging**
