### PR TITLE
Bundle LICENSE and NOTICE.txt into packaged apps

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
In my understanding, `NOTICE.txt` should be shipped with application.

On Windows, appropriate text editor is necessary to read them due to LF line encoding.

**Issue link**
#488 

**Test Cases**
1. Download and extract artifacts.
2. `LICENSE` and `NOTICE.txt` should be included.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/227#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
I can see both

image

I'm wondering if `LICENSE` should be changed to `LICENSE.txt` so it's more easily accessible.

**Comment by yuya-oc** [comment]
Updated. New artifacts would be available later. https://circleci.com/gh/yuya-oc/desktop/228#artifacts

**Comment by jasonblais** [comment]
+1

image

**Comment by yuya-oc** [comment]
Also found in Mac app and Linux tar.gz. Thanks!

Mac:
mac

Linux:
linux

**Pull request merged**
