### PR TITLE
Use eslint to format codes

### LINKED ISSUE #266: Use eslint to enforce/help with common errors
See discussion in: https://github.com/mattermost/desktop/pull/265

About eslint: http://eslint.org/

### PR DESCRIPTION
**Pull request by yuya-oc**
- [x] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] Update `CHANGELOG.md` and/or `doc/*.md` if it's necessary.
- [x] Write about environment which you tested
  - Operating system: Windows 10 Pro 64bit
---

This PR makes huge changes for existing codes, but it should not change any behavior of the application.

By merging this as the first step of refactoring, more clarified style is applied to format codes compared to former `npm run prettify` command. And the style is based on one of /platform repository, so we can use common style across repositories.

Close #266.

### CODE REVIEW

**Comment by yuya-oc** [comment]
The artifacts are available at https://circleci.com/gh/yuya-oc/desktop/79#artifacts

**Comment by jasonblais** [comment]
Thanks @yuya-oc, @Razzeee! 

I've downloaded the 64-bit Windows artifact and will test + use it for next couple of days.

Any help from the community would be really, really appreciated here. This is a big pull request and could introduce unexpected bugs.

**Comment by yangchen1** [comment]
Same, will do on macOS as well. :)

**Comment by jasonblais** [comment]
Alright, have been testing this for a few days now without issues. Giving sign-off on Windows.

**Comment by yangchen1** [comment]
No issues on macOS, great work! :) 👍

**Comment by yuya-oc** [comment]
Tested on Ubuntu 16.04 with Unity. No issues, but I'm not sure whether the tray icon works well because I don't know the correct way to show tray icons on Unity.

**Comment by jasonblais** [comment]
@jnugh Would you know what the correct behavior of tray icons is on Unity?

**Comment by jnugh** [comment]
Well, you need to have libnotify installed: http://electron.atom.io/docs/tutorial/desktop-environment-integration/#linux everything else should work as it does no Mac and Windows.

**Comment by yuya-oc** [comment]
@jnugh What I meant is the tray icon: http://electron.atom.io/docs/api/tray/ and libappindicator1 is already installed.

**Comment by yuya-oc** [comment]
Tested on Linux Mint 18 Cinnamon (System Settings -> General -> Enable support for indicators). The tray icon is working. But the icon png doesn't appear, and the blank space appears instead. It seems the problem is introduced by #339.
For now, I merge this PR as no problem, then create another issue to solve the problem.

Thanks all!

**Pull request merged**
