### PR TITLE
Fixing link to GIF in README

### PR DESCRIPTION
**Pull request by it33**
I accidentally linked it to the branch in the first PR :p

### CODE REVIEW

**Comment by yuya-oc** [comment]
I had overlooked, too. How about using relative path?

**Comment by it33** [comment]
I'm not sure if relative path will work with embedded image files because we need to reference the raw version?

**Comment by yuya-oc** [comment]
9d5b1a8f986e0f86c849f06f10e2ed8956bce96d looks fine. It can be also previewed by atom editor.

**Comment by it33** [comment]
Thanks @yuya-oc. It does work, I've updated the link. Thanks for the tip!

**Comment by yuya-oc** [comment]
The test looks still unstable...

**Pull request merged**
