### PR TITLE
test:MM-T808 Redo in the Menu Bar

### PR DESCRIPTION
**Pull request by codedsun**
#### Summary

test:MM-T808 Redo in the Menu Bar
#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1897
#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by codedsun** [comment]
@devinbinnie Please review.

**Comment by hmhealey** [comment]
@codedsun Could you update this branch to the latest master and resolve the conflict it's having?

**Comment by codedsun** [comment]
@hmhealey sure, on it 👨‍💻

**Comment by codedsun** [comment]
Thanks team 💯

**Pull request merged**
