### PR TITLE
[MM-22552] Remove permission request everytime a notification needs to be shown

### PR DESCRIPTION
**Pull request by Willyfrog**
Before submitting, please confirm you've
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

Remove asking for permission each time a notification appears and only ask if the user never choose an option.

**Issue link**

[MM-22552](https://mattermost.atlassian.net/browse/MM-22552)

### CODE REVIEW

**Comment by Willyfrog** [comment]
I'm still waiting for Pauls' comments on if it helped the users, but I still feel it's an improvement. so it might go in anyway

**Comment by amyblais** [comment]
@Willyfrog I'm wondering if this can also be cherry-picked to v4.4 as it has been reported by customers, as long as it's not risky.

**Comment by Willyfrog** [comment]
@amyblais it can be cherrypicked to 4.4 adding the version now

**Comment by Willyfrog** [comment]
@devinbinnie @nevyangelova I have to update this to match master now that we changed where notification code is, can you do a quick re-review?

**Pull request merged**
