### PR TITLE
test:MM-T812 Select All in the Menu Bar

### PR DESCRIPTION
**Pull request by codedsun**
#### Summary

test:MM-T812 Select All in the Menu Bar

#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1899

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by codedsun** [comment]
@devinbinnie 3 dot menu make this work too...Please review.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @codedsun!

**Comment by codedsun** [comment]
@Willyfrog Please review when time allows!

**Comment by codedsun** [comment]
@devinbinnie Review this

**Review by Willyfrog — APPROVED** [review]

**Pull request merged**
