### PR TITLE
[MM-56873]: Updated Svg's and styling for welcome page

### PR DESCRIPTION
**Pull request by Rajat-Dabade**
This PR Update the
- Titles
- Sub-titles
- Svg's
For welcome pages. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56873

#### Checklist
N/A

#### Device Information
N/A

#### Screenshots
N/A

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Review by harshilsharma63 — APPROVED** [review]
LGTM!

**Review by yasserfaraazkhan — APPROVED** [review]
tested the onboarding flow on the desktop. Images rendered as expected.

**Review by abhijit-singh — APPROVED** [review]
Looks good @Rajat-Dabade. Just one quick change request - the titles seem to have the font size of 80px whereas it should ideally be 64px based on the [design here](https://www.figma.com/design/6ZtxugLEj6wWRIZDLw1LPX/Desktop-App-FTUX?node-id=2202-43297&t=FAAIejesfI6C3N02-4).
image

**Pull request merged**
