### PR TITLE
Upgrade devDependencies - babel

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade babel stack and introduce `babel-preset-env`. It generates more optimized codes for Electron and brings latest JavaScript features to us.

**Issue link**
#702 

**Test Cases**
General use cases.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/596#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc I approved, let me know if there's anything specific I should test.

**Comment by yuya-oc** [comment]
@jasonblais Basically none. But generated codes should be changed, so we'd be happy to use it for a moment.

**Comment by jasonblais** [comment]
@yuya-oc Sounds good, I'll test it out this week 👍

**Comment by jasonblais** [comment]
@yuya-oc Haven't seen any issues so this is okay to merge.

I'll keep using it for the next day or two and raise issues if I find any.

**Comment by yuya-oc** [comment]
@jasonblais I see. Thanks!

**Pull request merged**
