### PR TITLE
[MM-40009] Add servers dropdown shortcut to menu

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
We were missing a menu item for the Servers menu and instead used a globalShortcut. This PR adds the menu item and the correct keyboard shortcut, as well as a reference to the shortcut in the menu itself.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-40009

#### Release Note
```release-note
Added menu item to open the dropdown menu called 'Show Servers' under 'Window'
```

### CODE REVIEW

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by Willyfrog — APPROVED** [review]

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks for this @devinbinnie.

Looks like we have the shortcut showing inconsistently for Mac (Windows seems to be ok).
- In the Servers Menu it is showing as `^⌘S`, but that shortcut doesn't actually work. It's showing as `⇧⌘S` in the Mac OS menu and that is the shortcut that actually works. I believe the correct shortcut was supposed to be `^⌘S` though
- Also, the `^` character displays weirdly with this font. I'm wondering if we change the font for the shortcut to `sans-serif` to just default to the OS font for these shortcut characters - that way they will display as they do in the OS. Thoughts?

image

image

**Comment by devinbinnie** [comment]
@matthewbirtch Fixed the shortcut issue in the menu, it should now be Cmd+Ctrl+S (I always confuse the ^ for Shift)

As for the font on the menu, I think it looks fine, 0/5 on if we change it.

**Comment by matthewbirtch** [comment]
> @matthewbirtch Fixed the shortcut issue in the menu, it should now be Cmd+Ctrl+S (I always confuse the ^ for Shift)

Thanks @devinbinnie

> As for the font on the menu, I think it looks fine, 0/5 on if we change it.

I worry that it would be confused with the `^` character (which would be `Shift 6`) though.

**Comment by devinbinnie** [comment]
> > @matthewbirtch Fixed the shortcut issue in the menu, it should now be Cmd+Ctrl+S (I always confuse the ^ for Shift)
> 
> Thanks @devinbinnie
> 
> > As for the font on the menu, I think it looks fine, 0/5 on if we change it.
> 
> I worry that it would be confused with the `^` character (which would be `Shift 6`) though.

I didn't even realize it was a different character XD
I can make the change if needed.

**Comment by matthewbirtch** [comment]
Thanks @devinbinnie is there a new build?

**Comment by devinbinnie** [comment]
> Thanks @devinbinnie is there a new build?

@matthewbirtch Generating one now

**Review by matthewbirtch — APPROVED** [review]
Looks great @devinbinnie. Thanks!

**Pull request merged**
