### PR TITLE
test:MM-T1308 Check that external links dont open in the app

### PR DESCRIPTION
**Pull request by codedsun**
test:MM-T1308 Check that external links dont open in the app
#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1906

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by codedsun** [comment]
@devinbinnie Please review

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @codedsun!

**Review by jwilander — APPROVED** [review]
LGTM - thanks @codedsun !

**Comment by codedsun** [comment]
Thanks team 💯

**Pull request merged**
