### PR TITLE
Enable zoom-in on CommandOrctrl +

### PR DESCRIPTION
**Pull request by akashnimare**
First of all, please read `CONTRIBUTING.md`

---

- [x] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] Execute `npm run prettify` to format codes
- [x] Write about environment which you tested
  - Tested on OS X 10.11.6

### CODE REVIEW

**Comment by Razzeee** [comment]
Would be much better solved by using the new default roles introduced in electron 1.3.3.
See: https://github.com/electron/electron/pull/6777
Practically the same as I've done here: https://github.com/mattermost/desktop/pull/187

**Comment by Razzeee** [comment]
Btw, my idea above doesn't solve what this PR is trying to address.

**Comment by akashnimare** [comment]
@Razzeee yeah. I'll see what I could do to implement zooming in a proper way.

**Comment by Razzeee** [comment]
@akashnimare 
Please see https://github.com/mattermost/desktop/pull/240
And also this bug: https://github.com/electron/electron/issues/6731

**Comment by jasonblais** [comment]
@akashnimare It would be great if you had time to take a look! Not sure if the electron issue @Razzeee is referencing would need to be fixed first. Any thoughts @akashnimare? 

Ideally, it would be great to have the following for zoom in/out:
```
Zoom in:
 - CTRL+PLUS
 - CTRL+=
 - CTRL+SHIFT+= [already works]

Zoom out:
 - CTRL+MINUS [already works]
 - CTRL+SHIFT+MINUS
```
^Mac-equivalent shortcuts replaces `CTRL` with `CMD`.

**Comment by yuya-oc** [comment]
In master branch, both of `CMD+=` and `CMD+SHIFT+=` properly work on OS X. Then, this PR breaks the latter and shows the shortcut as `CMD+=` instead of `CMD+Plus`.
Assuming electron/electron#6731, the fix should be applied for Windows and Linux.

JFYI, in JP keyboard, `Plus` is `SHIFT+;`. But this PR somehow works on Windows 10. So we have to remember this is a hacky way.

**Comment by akashnimare** [comment]
@yuya-oc @jasonblais I'm into other things for few days. I'll see what I could do here later.

**Comment by jasonblais** [comment]
Thanks @akashnimare, much appreciated! 

We'd also like to welcome you to join our [Desktop community channel](https://pre-release.mattermost.com/core/channels/desktop-app). It's a place where the community can discuss issues and give suggestions on how to improve things.

Would love to see you there once you're back, if you'd like.

**Comment by yuya-oc** [comment]
Possibly you can use `visible` flag to add hidden accelerator, `CmdOrCtrl+=`.

**Comment by jasonblais** [comment]
Hey @akashnimare, saw a note from you. Curious to know if you'd have time to take a look at the note from @yuya-oc.

Thanks again for your work here!

**Comment by yuya-oc** [comment]
Added the hidden acelerator at https://github.com/yuya-oc/desktop/commit/1317d27328ee3d3e711151d4d75c48d63da40f69 . `=` will be changed depending on user's keyboard layout, so I didn't write about `Ctrl+=` in docs. Would you check this? Artifacts are here. https://circleci.com/gh/yuya-oc/desktop/3#artifacts

**Comment by jasonblais** [comment]
Thanks @yuya-oc, tested the following on Windows 10:

Zoom in:
 - CTRL+SHIFT+=; CTRL+= 
Zoom out:
 - CTRL+MINUS

and the above cases worked. 

@Razzeee @yangchen1, would you like to test in on your end to add coverage of this pull request?

**Comment by Razzeee** [comment]
Working:
- CTRL+SHIFT+=
- CTRL+MINUS
- CTRL+0

Not working:
- CTRL+= Zoom out:

Might be the german keyboard layout

**Comment by yuya-oc** [comment]
Just for reference, my result in the Japanese keyboard layout is below.

Zoom in: (In JP kbd, `Plus` is assigned to `SHIFT+;`)
- CTRL+SHIFT+;
- CTRL+;

Zoom out:
- CTRL+MINUS

@Razzeee Just curious, how do you input `=` in the German keyboard layout?

**Comment by Razzeee** [comment]
@yuya-oc 
German keyboard has the `=` on the same button as `0` is. So it's pretty obvious why it's not working, should have probably mentiond that :)

See:
https://www.smartkeyboardsolutions.com/images/German_10029_zoom.gif

**Comment by yuya-oc** [comment]
@Razzeee Thanks! But I feel my question was wrong. I should have heard below.

- What accelerator does the app show for `Zoom In`? Please check the item in menu.
- How to input `+`. In the gif, it seems you can input `+` without any modifiers, is it right?

Just looking the German keyboard layout, I feel `CTRL+=` is handled  as `CTRL+0: Reset`. Would you check whether `CTRL+=` works as Zoom out again?

**Comment by Razzeee** [comment]
1) It shows CTRL+Shift++
2) I think I may have screwed up on the last test, + seems to work either without Shift or with Shift
3) Yes, CTRL+= resets the view, doesn't work as zoom out.

**Comment by jasonblais** [comment]
Just to confirm @Razzeee, it sounds like it might be working as expected?

**Comment by Razzeee** [comment]
Yep, it's fine

**Comment by jasonblais** [comment]
Thanks!

Could we get someone help test the PR on OS X?

Artifact can be found here: https://circleci.com/gh/yuya-oc/desktop/3#artifacts

When testing, please make sure the following cases work as expected: 

**Zoom in: (Increase font size)**

CMD+SHIFT+PLUS
CMD+PLUS

**Zoom out: (Decrease font size)**

CMD+MINUS

**Reset font size**

CMD+0

**Comment by yangchen1** [comment]
Tested on OS X. +1.

**Comment by jasonblais** [comment]
Thanks! 

@yuya-oc ready to merge

**Comment by yuya-oc** [comment]
Thanks all!

**Pull request merged**
