### PR TITLE
[MM-31626] bypass gitlab browser-check for oauth login

### PR DESCRIPTION
**Pull request by Willyfrog**
Please provide the following information:

**Summary**
remove chrome from user agent if we detect we are in gitlab. (see ticket for details on why)
prevent crash when going back after too many redirects.

**Issue link**
[MM-31626](https://mattermost.atlassian.net/browse/MM-31626)

**Test Cases**
go to prev.test.mattermost.com and use the gitlab login as authentication method.
Expected: after a page saying that it is checking your browser, you can access the gitlab page
any requests contain the overridden UA as well as electron and mattermost tags
 
**Additional Notes**
changing the user agent might have unnexpected consecuences: use this with care.

Needs documentation.

~~Currently the pipeline is failing, I'll submit a separate PR to fix it, in the meantime it can be reviewed.~~ Submitted PR here: https://github.com/mattermost/desktop/pull/1440

### CODE REVIEW

**Comment by Willyfrog** [comment]
ready for review

**Comment by amyblais** [comment]
@deanwhillier @Willyfrog Kind note to review for a dot release.

**Comment by amyblais** [comment]
Meant to ping @hmhealey in my previous comment.

**Review by deanwhillier — APPROVED** [review]

**Review by hmhealey — APPROVED** [review]

**Comment by jgilliam17** [comment]
Thanks @Willyfrog
On my first try I was stuck on  `Checking your browser screen` indefinitely. Tested on Windows 10, win64.zip build
I tried refreshing, but could not get app to move from that screen.
Quitting the app and restarting allowed me to move forward from this screen and enter my gitlab creds.
Not being logged in, redirect link is not valid.
Screenshot 2021-01-20 153821

**Comment by jgilliam17** [comment]
Actually, disregard the previous comment for now.  I need to investigate this further as I'm getting the same error on browser using prev.test

**Review by jgilliam17 — APPROVED** [review]
Thanks @Willyfrog 
Tested, looks good to merge.
- Verified able to login using GitLab on desktop app. (tested PR build using RC cloud server with OAuth configured).

**Pull request merged**
