### PR TITLE
 Use a Mattermost animation icon when loading a page in the app

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Use a Mattermost animation icon when loading a page in the app.

It seems huge changes are needed to locate the icon at the vertical center for me. So I simply used 64px margin from the top of content area.

loading

**Issue link**
#490

**Test Cases**
Normal case:
1. Open the app.
2. The animation icon should appear until the page has been loaded.

Error case:
1. Open the app.
2. Unplug LAN cable or disconnect from Wi-Fi.
3. Reload the app (Ctrl+Shift+R).
4. The error should appear.
5. Recover the internet connection.
6. The animation icon should appear on next reloading.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/456#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
@yuya-oc I get a broken image when I try it out 

image

**Comment by yuya-oc** [comment]
Sorry, that's my mistake. The gif was not included in the commit.

https://circleci.com/gh/yuya-oc/desktop/462#artifacts

**Comment by jasonblais** [comment]
Thanks @yuya-oc! Currently there seems to be four stages of loading screens.

The last three also occur on the webapp. Does this mean subsequent changes for the loading screen(s) should be made on the webapp/server-side?

image
image
image
image

**Comment by yuya-oc** [comment]
Or, possibly we can wait until [・・・] and gray screen disappears.

**Comment by jasonblais** [comment]
> Or, possibly we can wait until [・・・] and gray screen disappears.

@yuya-oc If we did the above, does this mean we'll show the Mattermost animation icon until either login page is shown or when the post list is being loaded on the fourth screen above?

**Comment by jasonblais** [comment]
Have also checked with UX team if the position and size of the icon are okay. Will let you know on Monday if any changes are needed.

**Comment by yuya-oc** [comment]
@jasonblais Yes, so the user would see the first and fourth of your screenshots. The second and third will be covered with the first screen.

**Comment by jasonblais** [comment]
@yuya-oc Let's do that. I think that would be great, as you'd see the Mattermost icon, then have the channel loading.

Just minor feedback from our UX designer:

> It can be centered vertically via a table view, or just through absolute positioning. I think it should be centered if possible.

Not sure if you tried that?

He also proposed reducing the opacity of the icon to 0.5. But otherwise it looks great 👍

**Comment by yuya-oc** [comment]
Updated: https://circleci.com/gh/yuya-oc/desktop/482#artifacts

The loading icon is located at center and has the opacity of 0.5.

**Comment by jasonblais** [comment]
@yuya-oc Looks great, let's ship with this. Thanks!

**Comment by yuya-oc** [comment]
Rebased to update the changelog. Thanks for many feedback!

**Pull request merged**
