### PR TITLE
Update icon for Linux menus to use an SVG icon

### LINKED ISSUE #507: Make Application Icon use SVG
taskswitch

Compared to other Icons the Mattermost icon looks pretty pixely in the Gnome 3 application switcher. It also does so in the dock. This is propably due to a poor scaling algorithm of the [PNG](https://github.com/mattermost/desktop/blob/master/src/assets/appicon.png) used as the application icon.

So this is a feature request to use SVG for the application icon at least on capable operating systems.

### PR DESCRIPTION
**Pull request by j1mc**
Replace mattermost-desktop PNG icon (icon.png) with an SVG version
(icon.svg). This will improve icon appearance on Linux desktops.
Update icon references in electron-builder.json and
create_desktop_file.sh to point to the new SVG icon.
Update CHANGELOG.MD
Fixes #507

Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

Use SVG icon for Linux application menus in place of PNG icon

**Issue link**
https://github.com/mattermost/desktop/issues/507

**Test Cases**

**Additional Notes**
I retrieved this SVG from the web, so I am not 100% certain if it meets your branding requirements in terms of colors used.
Also, I included an update to the CHANGELOG.md file as part of the pull request.

### CODE REVIEW

**Comment by j1mc** [comment]
Is the "all checks have failed" notice something to be concerned about?

**Comment by yuya-oc** [comment]
You don’t have to take care it. Still there is some problem in our jenkins.

**Comment by jasonblais** [comment]
@yuya-oc Good point - does the icon follow the branding guidelines? https://www.mattermost.org/brand-guidelines/

**Comment by j1mc** [comment]
I found the SVG on the web just by searching for "mattermost svg logo" or something similar. I can re-submit the request (if needed) if someone gives me a different SVG. If this one works for you all, that is okay, too.

**Comment by yuya-oc** [comment]
The SVG is exactly same. http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/mattermost-icon.html

@jasonblais It's licensed under GPLv3, so I think we should not accept the SVG. Probably we need to prepare a new SVG for this purpose.

**Comment by jasonblais** [comment]
I've touched base with our design team to see if we'd have an existing SVG.

**Comment by yuya-oc** [comment]
Hi @j1mc, please use this SVG. It might not be ideal, but would make better.

https://pre-release.mattermost.com/files/tu99xp8gptgdicw1w7kow1mtey/public?h=n_K69622PLNfTb_SH3EPZUTf1ne1ZF-bzb5gmkHBCv8

**Comment by j1mc** [comment]
Hi @yuya-oc, I've made that update, and have pushed the updated pull request.  Thanks for your help.

**Comment by j1mc** [comment]
Apologies - this should be updated now.

**Pull request merged**
