### PR TITLE
Separate artifact names since we merged the nightly builds for consistency

### PR DESCRIPTION
**Pull request by toninis**
#### Summary

- We need clear separation of the packages not to override one another since reusable workflows were using the same artifact name

Tested [here](https://github.com/toninis/test-actions/actions/runs/4423779890)

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [ ] completed [Mattermost Contributor Agreement](https://mattermost.com/contribute/)
- [ ] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note

```

### CODE REVIEW

**Review by phoinixgrr — COMMENTED** [review]
:shipit:

**Review by phoinixgrr — APPROVED** [review]

**Review by devinbinnie — COMMENTED** [review]
Hate to nitpick, but the "browser-view" naming scheme isn't really accurate anymore. That came from when we started doing nightlies for the BrowserView architecture that Guillermo put together.

0/5 on what we actually name it, but if we're going to fix the naming I suggest we don't continue the "browser-view" naming anymore.

**Comment by toninis** [comment]
> Hate to nitpick, but the "browser-view" naming scheme isn't really accurate anymore. That came from when we started doing nightlies for the BrowserView architecture that Guillermo put together.
> 
> 0/5 on what we actually name it, but if we're going to fix the naming I suggest we don't continue the "browser-view" naming anymore.

Cool by me . We can pick a name and change it

**Comment by devinbinnie** [comment]
> > Hate to nitpick, but the "browser-view" naming scheme isn't really accurate anymore. That came from when we started doing nightlies for the BrowserView architecture that Guillermo put together.
> > 0/5 on what we actually name it, but if we're going to fix the naming I suggest we don't continue the "browser-view" naming anymore.
> 
> Cool by me . We can pick a name and change it

I'm good with just `nightly-build` or something like that. Dealers choice :)

**Review by devinbinnie — APPROVED** [review]

**Pull request merged**
