### PR TITLE
test:MM-T816 Toggle Full Screen in the Menu Bar

### PR DESCRIPTION
**Pull request by codedsun**
test:MM-T816 Toggle Full Screen in the Menu Bar

#### Ticket Link

  Fixes https://github.com/mattermost/desktop/issues/1900

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by codedsun** [comment]
@devinbinnie When I perform the toggle full screen, the `window.outerWidth` changes but here in CI it's not showing, can you please check that the shortcut is working for you?

**Comment by devinbinnie** [comment]
@codedsun Yes this one runs fine for me in CI. I would see if there's another way you can try to detect fullscreen mode that will work in CI (and locally), but if not, we can add `.skip` to this test so that it doesn't run in CI and we will have to run in manually.

**Comment by codedsun** [comment]
@devinbinnie Let me know if I should skip this on CI?

**Comment by devinbinnie** [comment]
> @devinbinnie Let me know if I should skip this on CI?

Yes go for it.

**Comment by codedsun** [comment]
@devinbinnie Done the changes, please review.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @codedsun!

**Review by jwilander — APPROVED** [review]
Thanks!

**Comment by codedsun** [comment]
Thanks team 💯

**Pull request merged**
