### PR TITLE
[MM-T2637] Double-Clicking on the header should minimize/maximize the app

### PR DESCRIPTION
**Pull request by gohyinhao**
#### Summary

e2e test to check minimize/maximize of app when double clicking on header

#### Ticket Link

Fixes https://github.com/mattermost/desktop/issues/1914

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: Ubuntu 20.04.3

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by gohyinhao** [comment]
i been able to get the test to work as intended in my local env but it seems to always fail in circle ci. let me continue to take a look

**Comment by devinbinnie** [comment]
@gohyinhao Did you manage to find out why the test wouldn't pass in CircleCI?

**Comment by gohyinhao** [comment]
hi @devinbinnie originally, i thought there was something wrong with my implementation so i tried various implementations but they all had similar results (pass in local linux env, but fail in CircleCI). i noticed that other tests relating to minimizing/maximizing the app (#1976 #1975) face similar issues where the app does not seem to be minimized/maximized in CircleCI, so i tried looking for the problem outside of the test implementation.

so far, what I found out is that when i run the test using xvfb locally, the test fails. when i log the window bounds using the playwright methods, it seems like the app does not get maximized/minimized at all. however, i am still unable to ascertain whether the issue lies with xvfb itself, or if it is an issue specific to xvfb with electron apps, or possibly even xvfb with playwright with electron. as such, I'm sorry but I have yet to find a solution for this.

by any chance, are you familiar with such issues or have any insights pertaining to this issue?

**Comment by devinbinnie** [comment]
> 



> hi @devinbinnie originally, i thought there was something wrong with my implementation so i tried various implementations but they all had similar results (pass in local linux env, but fail in CircleCI). i noticed that other tests relating to minimizing/maximizing the app (#1976 #1975) face similar issues where the app does not seem to be minimized/maximized in CircleCI, so i tried looking for the problem outside of the test implementation.
> 
> so far, what I found out is that when i run the test using xvfb locally, the test fails. when i log the window bounds using the playwright methods, it seems like the app does not get maximized/minimized at all. however, i am still unable to ascertain whether the issue lies with xvfb itself, or if it is an issue specific to xvfb with electron apps, or possibly even xvfb with playwright with electron. as such, I'm sorry but I have yet to find a solution for this.
> 
> by any chance, are you familiar with such issues or have any insights pertaining to this issue?

@gohyinhao I have noticed similar things happening with tests that attempt to minimize/maximize the Desktop App, it appears your test is also affected. I just ran it on my local machine and it passed just fine so I think we can say that it's good to merge. 

I'm going to look into removing the check for PRs since a lot of these tests are kind of flaky, but I will merge this one once reviews are complete. Thanks for the hard work :)

**Review by M-ZubairAhmed — APPROVED** [review]
🆗  It looks good to me. Thank you

**Comment by gohyinhao** [comment]
thanks both, for taking the time to review

**Pull request merged**
