### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jcomack**
Updated the `README.md` based on suggestions from @it33 in https://github.com/mattermost/desktop/issues/311

### CODE REVIEW

**Comment by jasonblais** [comment]
Many thanks @jcomack!

If this is your first time contributing to a Mattermost project, please consider signing the [Mattermost contribution license agreement](https://www.mattermost.org/mattermost-contributor-agreement/)?

This is a standard procedure for many open source projects, and helps us guarantee your contribution is properly credited. If you include your address, we'd love to send you a small thank you gift as well,

Thank you again!

**Comment by it33** [comment]
Sweet, thanks @jcomack!!

**Comment by jcomack** [comment]
@jasonblais Done :)
@it33 You're welcome :)

**Comment by jasonblais** [comment]
Thank you again! 

Please also consider joining our [Desktop community channel](https://pre-release.mattermost.com/core/channels/desktop-app) to meet other contributors and to discuss the future of the project.

**Pull request merged**
