### PR TITLE
[MM-19510][MM-19511] Remove ToastActivatorCLSID from Start Menu shortcut on Windows

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
The shortcut produced by the MSI installer was malformed and was causing an issue when clicking on a notification that wouldn't open the application. I've removed the offending line that doesn't need to be there.

Thanks a bunch to @zpersichetti for finding this for us! :)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19510
https://mattermost.atlassian.net/browse/MM-19511
https://github.com/mattermost/desktop/issues/1523

#### Release Note
```release-note
Fixed an issue with the MSI build that caused notifications when clicked, to not open the application and navigate to the correct channel.
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
seems like the store artifact was only waiting for the no installer one, which is sensibly faster than the msi one. added a commit to change that and hopefully we can start testing it :)

**Comment by devinbinnie** [comment]
Something in `master` is causing the MSI to build incorrectly. When rebased against `release-4.7` the build runs fine.

**Comment by Willyfrog** [comment]
I tested the build from circle from that other branch and it worked in my machine. 🎉 🎉

**Review by Willyfrog — APPROVED** [review]

**Comment by devinbinnie** [comment]
Tested and confirmed working on Windows 7 :)

**Comment by devinbinnie** [comment]
@deanwhillier This is ready for review

**Review by deanwhillier — APPROVED** [review]
Interesting.

**Pull request merged**
