### PR TITLE
[MM-43941] Optimize app resizing on Windows/Linux by waiting for the viewport to resize

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Resizing the BrowserView that holds the webapp has been very slow and caused some weird UI glitches (eg. on macOS, if you resize rapidly enough, it will keep resizing the BrowserView over and over for a few seconds).

In order to try and mitigate the amount of resizes that actually happen when resizing the app, I've implemented a callback from the web process to check if the viewport has resizes, and to prevent any further resize events until that has happened.

These changes only work for Windows and macOS, since Linux doesn't support the `will-resize` event.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43941

```release-note
Improved performance during resizing.
```

### CODE REVIEW

**Comment by zefhemel** [comment]
CleanShot 2022-07-20 at 09 57 50

With the test build linked, I still see this behavior on my m1 mac.

**Comment by zefhemel** [comment]
Ok, I just reinstalled the build and maybe it was just me. It seems ok now. Ignore my last GIF.

**Review by hmhealey — APPROVED** [review]

**Review by streamer45 — APPROVED** [review]
Looks good :+1:

**Comment by devinbinnie** [comment]
@jgilliam17 Adding you as reviewer in case you wanted to have a look. Feel free to defer.

**Pull request merged**
