### PR TITLE
Improve tray menu

### PR DESCRIPTION
**Pull request by Razzeee**
- [ x ] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [ x ] Execute `npm run prettify` to format codes
- [ x ] Write about environment which you tested
  - Tested with windows 10, works fine

Also aligned the changelog, but could not find anything in the docs folder about it.

Looks like this:
unbenannt

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @Razzeee, great addition! 

Could I also have your help posting the latest artifacts on circleci.com, so we can have others in the community help test it?

**Comment by Razzeee** [comment]
https://circleci.com/gh/mattermost/desktop/459#artifacts

**Comment by yuya-oc** [comment]
Looks nice! Could you update the menu when the config is updated? `update-config` is emitted to `ipcMain` when `Save` is clicked on settings UI, so you can use this. The application menu is already updated by this event.

**Comment by yuya-oc** [comment]
Ah, `update-menu` is better for that.

**Comment by Razzeee** [comment]
@yuya-oc 
Updated

**Comment by yuya-oc** [comment]
Tested with Win10 and OS X 10.11.5, work fine.

**Comment by yuya-oc** [comment]
@Razzeee Could you check `src/main/menus/tray.js` is prettified?

**Comment by Razzeee** [comment]
Will check again, but I'm pretty sure it is.

**Comment by Razzeee** [comment]
Seems like I screwed up the rebase. CircleCi is now green, should now work fine.

**Comment by yuya-oc** [comment]
Thanks!

**Pull request merged**
