### PR TITLE
 Add pl-PL as spellchecker

### PR DESCRIPTION
**Pull request by JtheBAB**
This pull request adds pl-PL as available spellchecker within the DesktopApp.

Needs prior #938 to merge.

### CODE REVIEW

**Comment by wget** [comment]
As [discussed](https://community.mattermost.com/core/pl/kt98u458zigfzrcd85b76h9kac), we will be using `electron-spellchecker` instead. We need to get the new CI merged first.

If this PR needs to get merged, #938 needs to be merged first.

**Comment by esethna** [comment]
@wget @JtheBAB are these PRs still valid if we are moving to electron-spellchecker?

**Comment by JtheBAB** [comment]
No. This is for the current spellchecker.

**Comment by JtheBAB** [comment]
@esethna

As there is a 4.2.1, you could add this.

**Comment by hanzei** [comment]
@wget @svelle @deanwhillier Same questions here

**Comment by svelle** [comment]
> @wget @svelle @deanwhillier Same questions here

answered on #939

**Comment by esethna** [comment]
Adding the "Pending" label as we are coming back to this PR in the very near future: https://github.com/mattermost/desktop/pull/948

**Comment by deanwhillier** [comment]
Going to close this one in favour of https://github.com/mattermost/desktop/pull/1139 as the changes are the same, but the other one is made on top of more recent code that has the updated CircleCI code. @JtheBAB, appreciate your contribution, apologies this took so long to get to!

**Comment by deanwhillier** [comment]
Hah, wrong one! @JtheBAB, would you be able to apply your changes on top of a new master and or try merge to get the newer CircleCI config.

**Comment by toojazzy** [comment]
I'm amazed how understaffed and incompetent the mattermost team must be to have such a big problem adding, or more precisely, just merging this simple feature. Judging from my other mattermost issue experience it must be a disaster there.

**Comment by JtheBAB** [comment]
Closing this for the new request 
https://github.com/mattermost/desktop/pull/1155

**Pull request closed without merging**
