### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by yuya-oc**
Please refer to https://blog.github.com/2018-05-02-issue-template-improvements/ for detail. We would be able to have multiple options when creating a issue.

### CODE REVIEW

**Comment by jasonblais** [comment]
Very interesting. Is the goal that when the user chooses a "troubleshooting question", they would see the link to the forums and report it there?

**Comment by yuya-oc** [comment]
Yes if they actually read messages when choosing a template. Currently [the messages are commented out](https://github.com/mattermost/desktop/commit/abcbd2c10a2ba31424a7e2c97629a1bba4e5f826#diff-f274ea7efd2db61335df518871fd3fdcR7) in "troubleshooting question". It's just a URL text, not a link. Possibly should we uncomment it?

**Comment by jasonblais** [comment]
Yeah, let's uncomment it so it's visible to the user right away.

**Comment by yuya-oc** [comment]
Updated.

**Comment by yuya-oc** [comment]
Thanks! Looks good to me.

**Pull request merged**
