### PR TITLE
Add MSI installers for Windows

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Add MSI installers for Windows

**Issue link**
https://mattermost.atlassian.net/browse/MM-11305

**Test Cases**
Installation / Uninstallation

Need to check installed location and start menu shortcut.

**Additional Notes**
https://circleci.com/gh/yuya-oc/desktop/949#artifacts

### CODE REVIEW

**Comment by jasonblais** [comment]
For anyone interested testing, here are the links to our test builds for MSI installers:
 - 64-bit: https://949-67276967-gh.circle-artifacts.com/0/packages/mattermost-desktop-4.2.0-develop-win-x64.msi
 - 32-bit: https://949-67276967-gh.circle-artifacts.com/0/packages/mattermost-desktop-4.2.0-develop-win-ia32.msi

**Comment by wget** [comment]
I studied the whole process of the msi generated with electron-builder. This is a pure joke. Electron has integrated this just to mimick the behavior of an msi file but their version isn't answering the needs of sysadmins at all.

What we want is the ability to install the electron app as a system application. Right now, if we want to install it, sysadmins cannot use the current installer (nor the aforementioned msi) because the app is still being installed in the user directory.

[From here](https://www.npmjs.com/package/electron-wix-msi#should-i-use-this):
> If you are however developing enterprise software, you might find that IT departments don't want automatically updating software. They want controlled rollouts and detailed control over the installation. This is true for universities, hospitals, the military, and many other organizations that have a managed IT infrastructure. Their administrators will expect a "classic" installer - the same way they would install Microsoft Office, Node.js, Photoshop, or any other software. If you see your app being used in those environments, you should push the self-updating package, but have a traditional MSI in your pocket. Bear in mind however that you will need to find a way to get updates to your users without relying on Electron's auto updater.

-> By using an msi, we are saying goodbye to the electron auto updater thing and I think this is a good thing.

What I basically started to do: rewrite a proper msi. Since making it by hand is way unmaintainable on the long term (dedicated VisualStudio project, build depencies ,etc.), I decided to use the small wrapper called WIX toolset (used and developed by Microsoft employees and used in the Office installer for example). I'm currently mastering it to have a fully automated build process. msi installers indeed require to list all files of the final application. I succeeded to make a PowerShell script to automate this. @jasonblais Do you have an AppVeyor account for chocolatey? How is the release process organized? Who is building the final exe? You or @yuya-oc, on his very own machine? Who hold the keyring for the exe signature (if any? I haven't checked?)

This is just an update of my work. This will take some time (let's say by the end of the week) as real msi do have an uninstall process/repair tool and I need to make further tests in this regard.

This looks however (and IHMO) promising:

screenshot_20180916_220825

**Comment by wget** [comment]
And also, since the steps to make msi installers have been initiated, @jasonblais you can already check if Mattermost has a developer account on the Microsoft Store? If not, could you please register a company account here: https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees?
When done, if possible, I would like to make some appx publication tests. But since the account validation requires some time for a company, you can already proceed to that step now ;)

**Comment by yuya-oc** [comment]
> What we want is the ability to install the electron app as a system application. Right now, if we want to install it, sysadmins cannot use the current installer (nor the aforementioned msi) because the app is still being installed in the user directory.

Our new NSIS installer would be able to install the app as a system application via electron-builder configuration (`oneClick: false`, `perMachine: true` and `allowToChangeInstallationDirectory: true`). Just curious, is this enough for you?

https://www.electron.build/configuration/nsis

per-machine-installer
finish

I have heard requests of msi many times, but anyone has never explained the reason why msi is needed. So still I'm not sure why msi is technically needed.

----

> Do you have an AppVeyor account at Mattermost (since if this initiative is accepted we will need one)?

As far as I know, there is no account on AppVeyor.

> How is the current release process organized? Who is building the final exe?

Organized by our Jenkins. Currently the final exe are built on a linux node of the Jenkins.

> Who hold the keyring for the exe signature (if any? I haven't checked?)

In my understanding, files related to code-signing are stored on the internal file server. At least I have never held them.

**Comment by yuya-oc** [comment]
About appx, would you migrate discussion into another issue if it's possible? For example, there is #492 for Windows Store and Mac App Store.

**Comment by wget** [comment]
@yuya-oc When my msi version will be done, I think we will be able to drop the NSIS completely and provide only one installer to rule them all for the Windows platform.

For the auto update feature we will be loosing, I'm investigating to reuse the Mozilla Update service to download an new msi installer and install it in the background.

And the reason why msi is needed for Windows sysadmins? Rather simple. msi are needed  in order to be able to deploy the application using WSUS (Windows Server Update Service). For large scale network (and even smaller ones), this comes in handy, trust me ;)

**Comment by yuya-oc** [comment]
@wget Thanks to reply. Please let me confirm:
- Will your proposal replace both of #582 and #841(this)? So should we stop testing them?
- Must we use Windows for CI? At least we will need to add Windows node to our Jenkins in order to build final exe.
- Just for reference, would you tell us the website/documentation of the Mozilla Update service?

**Comment by wget** [comment]
@yuya-oc 
* Yes my proposal will fix #841 (this). For #582 (update service) since I won't be able to run the electron updater (otherwise the msi will break at desinstallation since its file will be replaced), this will need further hacks and might not be available with this version, but rather with a next iteration. So maybe we will need to keep NSIS for the very near future, at least waiting for the auto updater to be sorted out. Sysadmin will need to be able to opt out of it :)
* Yes, it will require Windows. AppVeyor is fine for this. But I thought the Windows builds did already require Windows, am I right or am I missing something here?
* https://wiki.mozilla.org/Windows_Service_Silent_Update Thunderbird is making use of it and they have been studies at LibreOffice to use it as well (but I cannot find the details back, will let you know if I succeed).

**Comment by wget** [comment]
Yet another reason to choose msi installers: https://community.openvpn.net/openvpn/wiki/NSISBug1125

There is a vulnerability in NSIS allowing to hijack the NSIS install dll and execute code in privileged environment. There is currently no fix for Windows <8 users as there is not API to prevent this.

**Comment by yuya-oc** [comment]
Thanks! @jasonblais @esethna I think we should discuss about wgets' proposal.

>  But I thought the Windows builds did already require Windows, am I right or am I missing something here?

electron-builder can build Windows apps on Linux unless Node.js native module is not used. Some their internal tools are exe, but they can be executed by wine.

**Comment by jasonblais** [comment]
Thank you! Great discussion here. I'm not familiar enough with the details - @esethna wondering if it made sense to bring in someone from our dev team?

**Comment by crspeller** [comment]
@wget @yuya-oc I was asked to take a look at this by @esethna. I am wondering if we can copy what https://github.com/Microsoft/vscode does? They recently moved to a user directory installation, so maybe we should stick with that? Seems like having a system directory install would make the auto-update feature less smooth. 

They don't even seem to have MSI installers, so not sure how necessary those are. Seems like maybe the electron advice of "If you see your app being used in those environments, you should push the self-updating package, but have a traditional MSI in your pocket." would be useful.

**Comment by wget** [comment]
@crspeller For the first version of the msi I'll be proposing later today (system install/repair/uninstall supported), we will still need to keep the NSIS with autoupdater at hand, because the issue with the autoupdater will not be sorted out in time (IIRC you're planning a Mattermost Desktop release for Monday, right?).

The v2 of my msi package will feature a more beautiful user interface (actually the v2 msi will be run in the background with a WPF based interface running in the foreground communicating with the msi thanks to an IPC system; I know this is ugly, but the only solution for a real msi based and eye candy installer). The v2 of my msi will sort out the updater issue as well. I'm studying the ability to reuse the Mozilla Updater Service. This requires some research on my side, since most of the companies having invested in a solution like this keep themselves from open sourcing it. --> Even if I'll be open sourcing it, I'll keep intellectual property on this one; because I'll reuse it for a project I have with OpenVPN Inc, and I don't want to risk issues between both companies.

As for the VSCode example, this is a bad example, really. The electron autoupdater is highly criticized among Windows sysadmins. Actually, Windows sysadmins hate electron based app, like I do, even if I'm not a Windows sysadmin per se.

Why so much hate against electron install process you would say? Simple. Let's take Mattermost Desktop as an example. If sysadmins weren't repackaging it manually, for large organization on a remote Windows Server, this would mean 175 Mio (the size of the Mattermost Desktop install) / per user. Imagine if the org has 1K user... This is why even if we are providing NSIS based installs, they aren't of much use for a sysadmin. Electron apps are usually a burden on sysadmins. My goal: Let's avoid this with Mattermost!

**Comment by esethna** [comment]
Thanks @wget, will defer to @crspeller regarding most of your comments above. In terms of release timeline, we are holding off on releasing v4.2 until we can get MSI and autoupdater tested and merged. Hopefully releasing in the next couple weeks as we have many requests for these features.

If we take the v1 of your MSI installer for v4.2, are there any changes required to the PR from @yuya-oc for the [autoupdater](https://github.com/mattermost/desktop/pull/582)?

**Comment by wget** [comment]
@esethna Changes will be required depending on two factors: if you want to keep things clean and the way the electron updater works.

1. With msi installers, if you install/replace things manually, the Msi installer won't be quite happy about it. But replacing files are always possible manually although dirty.
2. Since we are now speaking about system installations, we have to know whether the autoupdater can run in elevated mode to apply the update and if the autoupdater can download a new msi for the update, since like I said first, msi installations must continue to be handled with msi.
3. Have the ability to disable the auto updater feature from the msi installer. @yuya-oc can your autoupdater be disabled using a registry key for example?

The progress I made for the msi installer, as you can see some things must be sorted out: https://github.com/wget/mattermost-desktop-msi-rd/issues

**Comment by wget** [comment]
@yuya-oc Would you mind implementing that feature and communicate to me the HKLM you want to use? On my side, for the MSI installer, here is the custom key I'm already using: [`HKLM\Software\Mattermost\Desktop\InstallLocation`](https://github.com/wget/mattermost-desktop-msi-rd/blob/2315b2a57a0aae05366f41f3ec69909c565ea371/installer.wxs#L84)

It would be fine if you could use the same hierarchy, for example: `HKLM\Software\Mattermost\Desktop\AutoUpdaterEnabled`.

**Comment by yuya-oc** [comment]
@wget Okay, now I can get the value of `HKLM\Software\Mattermost\Desktop\AutoUpdaterEnabled` via winreg. Right now I have no ideas about other registry values though, I'll tell you when it's necessary.

**Comment by esethna** [comment]
Thanks @wget, just to step back a bit and make sure we are all on the same page,

1. What are the advantages for systems admins that will install using your MSI installer vs the installer in this PR?
2. What is the difference to an end user, both ones that are installing the desktop app on their own machine via the Mattermost website download page, or end users in organizations that system admins have installed with MSI
3. How will the autoupdater work with MSI for system admins and end users? Both short term (v1) and long term (v2) based on your proposals above?

@yuya-oc what are your recommendations for moving forward given you submitted the MSI and autoupdater PRs already? We would like to ship MSI installer and autoupdater in the next release (ideally in 2-3 weeks).

**Comment by yuya-oc** [comment]
@esethna I think we can add auto-updater #582 apart from MSI. And by implementing @wget's suggestion (the registry key), we can prepare while waiting his MSI.

For clarification, what I do in auto-updater is merely to check the latest metadata via http. Once new version is found, it's handled by [electron-updater](https://www.npmjs.com/package/electron-updater). I think that it simply executes new installer as a detached process. So probably the elevation is handled by the installer itself (probably via application manifest, but I need to research).

**Comment by wget** [comment]
Answering @esethna.

1. The MSI installer provided by electron-builder installs to the user user location. By default, Mattermost is thus inaccessible in term of file permissions to other users. This means if an organization wants to deploy Mattermost, they will have to install it for all these users. If the Windows machine has X users. The Mattermost msi will have to be installed X times. -> Not good on disk nor on maintainability side.

2. To the end user: nothing, the app will we available to him like it was before. We need to check for the user data though if electron is smart enough to store them in the user folder rather than in a json file alongside the mattermost executable.

3. For v1: use the current electron autoupdater, but the latter *needs* to ask for privilege elevation when he detects a new version in order to write to Program Files, otherwise the installation will fail.

   For v2: a service running in the background will take care of the privilege issue and update the app automatically (like Firefox or Chrome on Windows)

   In all cases, the current apps needs to provide a way to disable the autoupdater provided by electron, because auto update is not something sysadmin like much.

**Comment by wget** [comment]
@yuya-oc If you can already share the details about the metadata check, this could be nice of you :)

**Comment by wget** [comment]
And for the record, the author of the Wix toolset (a Microsoft tool used to generate msi) is answering my questions in order to fix the issues I have. You can see the progress here: https://github.com/wget/mattermost-desktop-msi-rd/issues

**Comment by yuya-oc** [comment]
@wget Sadly the metadata spec is not documented. I merely call [`appUpdater.checkForUpdates()`](https://www.electron.build/auto-update#module_electron-updater.AppUpdater+checkForUpdates) at a certain interval. But you can see the metadata as artifacts: latest*.yml at https://circleci.com/gh/yuya-oc/desktop/502#artifacts.

> Wrt. the registry. What did you meant by I can get the value of. Do you mean you have been able to disable the autoupdater based on this registry key? If that's the case, that would be awesome news ;)

Yeah, so I should be able to do that. I don't call appUpdater.checkForUpdates() when the registry key has a value which indicates "disable".

**Comment by esethna** [comment]
Thanks @wget and @yuya-oc, so if I'm understanding correctly, it sounds like the proposal is to ship v4.2 with autoupdater and no MSI installer? @yuya-oc will there be any updates required on your [autoupdater PR](https://github.com/mattermost/desktop/pull/582) or can we continue testing? Once that's merged we can start release testing for the app.

**Comment by wget** [comment]
@esethna 
* Yes, 4.2 shipping with autoupdater *with ability to disable it*
* If ready, 4.2 with msi installer v1 (dedicated PR for DigitalOcean's Octoberfest :) )

**Comment by esethna** [comment]
Thanks @wget, if MSI is not ready we can ship 4.2 without it and include MSI v1 in 4.3. @yuya-oc are you on board with the plan proposed above ^? 

@wget when you say "ability to disable it" are you referring to a user setting? @yuya-oc what changes on the [existing PR](https://github.com/mattermost/desktop/pull/582) would be required to support this? Just want to make sure we are all on the same page about any proposed changes.

**Comment by yuya-oc** [comment]
If #582 test result is okay for us, what I need to do is to implement;

> I don't call appUpdater.checkForUpdates() when the registry key has a value which indicates "disable".

For that, we need to define the type and possible values for `HKLM\Software\Mattermost\Desktop\AutoUpdaterEnabled`.

**Comment by wget** [comment]
@esethna I meant the ability to disable the auto updater from the electron application itself. This setting will be reused/made accessible via the msi installer.

@yuya-oc For the values, I think an "Enabled/Disabled" is enough?

**Comment by ku-rt** [comment]
@wget Thank you for building this! What you've described for your v2 version of the .msi package is what I've been wanting for over a year now. Our company uses Mattermost and we have a large number of Service Desk agents with roaming profiles who switch computers often which leads to a lot of headaches using the desktop app on Windows.

I can't explain how much time this will save us being able to deploy a .msi package that installs on the machine rather than the user profile. So yes, what you explained is super valuable to sysadmins. :)

**Comment by wget** [comment]
@ku-rt Great to hear this :) Btw, now I know who I'll contact to test if the roaming is working properly for the msi project 😉

**Comment by wpayne** [comment]
Does the current version work? Need to install across desktops and don't want to wait until 4.3

**Comment by yuya-oc** [comment]
@wget Sounds good. It's a string, so we can add other values if we needed more options.

@esethna @wget Now #582 is a long-lived PR. To finalize its code, I would like to add another PR to implement the registry value behavior after merging #582. How about this?

**Comment by wget** [comment]
@yuya-oc Ok for merging #582 in order to avoid this branch from being outdated/digressing from master. :) Let's start clean with another PR if we want to have features modified.

**Comment by esethna** [comment]
Thanks guys, we'll wrap up testing on #582 and then and get it merged

**Comment by esethna** [comment]
@yuya-oc @wget what do you guys want to do with this PR given William's work on the new MSI installer? Should we close?

**Comment by yuya-oc** [comment]
@esethna Ah, we use @wget's MSI, so we don't use this PR, so it should be closed.

**Comment by wget** [comment]
@esethna As announced on the Installer and images channel, my msi is alive \o/. A new PR against this repo will be done within a day. Some issues need to be fixed with you guys first (msi signing, commits rights, appveyor accesses). More discussion happens on the Installer and images channel.
Closing :)

**Pull request closed without merging**
