### PR TITLE
plt-4174 - Improvements to the Settings UI

### PR DESCRIPTION
**Pull request by asaadmahmood**
- Added the cross icon in the header.
- Adjusted the padding for the settings grid and removed an unnecessary hr.

### CODE REVIEW

**Comment by jasonblais** [comment]
@asaadmahmood Looks like the build is failing

**Comment by asaadmahmood** [comment]
@Razzeee @yuya-oc any idea why the build is failing.

**Comment by Razzeee** [comment]
@asaadmahmood 
You have to run `npm run prettify`,commit and push

**Comment by asaadmahmood** [comment]
Just did it, lets see.

**Comment by yuya-oc** [comment]
There are something wrong in `npm run prettify`. It changes indent every time.

**Comment by asaadmahmood** [comment]
@yuya-oc Ready to merge.

**Comment by jasonblais** [comment]
Thanks @asaadmahmood, @yuya-oc! We'll test it out and we should be good for taking this in an RC after

**Comment by jasonblais** [comment]
@yuya-oc Has been tested both on Windows and Mac OS X. No issues, all works well.

Can we have your help merging this to the `release-3.4` branch?

**Comment by yuya-oc** [comment]
Thanks all! I have changed the base branch, so the PR is merged into `release-3.4`.

**Pull request merged**
