### PR TITLE
Create configuration guides

### PR DESCRIPTION
**Pull request by yuya-oc**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Create configuration guides for `buildConfig.js`

**Issue link**
#648 

**Test Cases**
N/A

**Additional Notes**
N/A

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @yuya-oc! I'll review this

**Comment by jasonblais** [comment]
@yuya-oc Sorry it took this long to review. I combined your work with my PR here, let me know your thoughts? https://github.com/mattermost/docs/pull/1779

We have other admin documentation at docs.mattermost.com, including mobile apps, so I thought it might be appropriate to include there.

**Comment by yuya-oc** [comment]
@jasonblais I see. I'll review it next week.

**Comment by jasonblais** [comment]
Doc PR merged now, we can merge this as well @yuya-oc 

https://github.com/mattermost/docs/pull/1779

**Pull request merged**
