### PR TITLE
Minor tweaks to v1.3 changelog

### PR DESCRIPTION
**Pull request by jasonblais**
Minor tweaks to v1.3 changelog, also added a list of contributors for v1.2 and v1.3

- [X] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [X] Execute `npm run prettify` to format codes
- [X] Write about environment which you tested
  - Not applicable

### CODE REVIEW

**Comment by yuya-oc** [comment]
Would you change the base branch to `release-1.3.0`?

**Comment by jasonblais** [comment]
Hey @yuya-oc, I think it's fine to merge it to the `master` branch -- @jwilander is already working on cutting the final builds,

**Comment by Razzeee** [comment]
Master already moved on to version 1.4.0
Both branches will need this changes. But you also need to rebase now.

**Comment by jasonblais** [comment]
I will close this one and submit a new PR

**Pull request closed without merging**
