### PR TITLE
[MM-16516] Add a "don't trust" option for certificates

### PR DESCRIPTION
**Pull request by jtwillis92**
#### Summary

Adds a checkbox to the `More Details` screen of the certificate warning thrown on Mattermost Desktop that when checked and a user clicks `Cancel Connection` will store a `dontTrust` value of true with the certificate in the user store. This value will then be checked in future requests and the certificate will be immediately rejected if true.

#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/16516

#### Checklist

- [x] Has UI changes
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 

Manjaro Linux 21.1.2
Node v14.17.0

#### Screenshots

mm-cert-update-1
mm-cert-update-2
Screenshot from 2021-09-10 17-27-32
Screenshot from 2021-09-10 17-27-50

#### Release Note

```release-note
Added a checkbox to certificate error modal that allows a user to permanently distrust a certificate.
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
Thanks for submitting this PR!!

LGTM

**Comment by Willyfrog** [comment]
Fixes https://github.com/mattermost/mattermost-server/issues/16516

**Comment by Willyfrog** [comment]
fixes https://github.com/mattermost/desktop/issues/1352

**Review by devinbinnie — APPROVED** [review]
Looks great! Thanks @jtwillis92!

**Review by esethna — APPROVED** [review]

**Comment by esethna** [comment]
@jtwillis92, does this also work the other way around, ie stores a "trusted" value?

**Comment by jtwillis92** [comment]
> @jtwillis92, does this also work the other way around, ie stores a "trusted" value if that option is selected?

Yes, although most of that part of the functionality was pre-existing without the checkbox. The only difference now is that in the case where it is trusted `dontTrust` will get set to False. In retrospect, it may make more sense to name that field `isUntrusted` or something like that.

In the case of clicking the `Cancel Connection` button now, the `dontTrust` value gets set to True with the stored certificate (it was not stored in this path before). Then any time the certificate handler runs it will check that field first in the certificate store and not raise the modal if already untrusted.

**Pull request merged**
