### PR TITLE
Add pt-BR spell checker

### PR DESCRIPTION
**Pull request by rodcorsi**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Upgrade `simple-spellchecker` and add entry in menu to support pt-BR spell-checker

**Issue link**

**Test Cases**

**Additional Notes**

### CODE REVIEW

**Comment by yuya-oc** [comment]
Thanks @rodcorsi! Looks good to me.

Just curious, how did you prepare the word list to create the dictionary file in https://github.com/jfmdev/simple-spellchecker/pull/12?

**Comment by rodcorsi** [comment]
I got this file from github.com/erdavila/M-Tree and normalize it using the simple-spellchecker cli

**Comment by yuya-oc** [comment]
Thanks for information.

**Comment by jasonblais** [comment]
@rodcorsi You're awesome. Thank you so much for this great contribution 🎉

**Pull request merged**
