### PR TITLE
CTRL/CMD+F on Desktop app puts cursor in Mattermost search box filtered to channel

### PR DESCRIPTION
**Pull request by yuya-oc**
- [x] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] Execute `npm run prettify` to format codes
- [x] Write about environment which you tested
  - Operating system: OS X 10.11.6

----

For #229. `Ctrl/CMD+F` puts cursor in the search box and fill `in:[channel_handle] ` to filter with current channel.

This is not related to operating system, so only need testers.

### CODE REVIEW

**Comment by Razzeee** [comment]
Working as expected on win10 x64

Your missing the changelog part and deocumentation.
You might also want to squash this down to one commit, but totally optional.

**Comment by yuya-oc** [comment]
Thanks, updated docs.

Artifacts for testing is available at https://circleci.com/gh/mattermost/desktop/603#artifacts

**Comment by jnugh** [comment]
Does not put the cursor into the search field when I didn't click into the `WebView` after switching tabs or clicking somewhere into the Tab header.
However `in:town-square ` is being filled in still.

**Comment by yuya-oc** [comment]
@jnugh Thank you for testing! The problem should be tracked at #231 as jasonblais referenced.

**Pull request merged**
