### PR TITLE
[MM-20270] Upgrade to Electron 6

### PR DESCRIPTION
**Pull request by deanwhillier**
**Summary**
- Updates the Desktop App to use Electron v6.
- Updates electron-builder to v22.
- Minor update to depricated `powerMonitor.querySystemIdleTime`.

**Issue link**
https://mattermost.atlassian.net/browse/MM-20270

### CODE REVIEW

**Comment by devinbinnie** [comment]
> * there is a fix for detecting dark mode, not sure if that affects devin's change for tabs and dark mode

This might just excuse the need for that script that updates the Info.plist entry, but currently dark mode works on Catalina.

**Comment by hunterlester** [comment]
Can be bump up to version 7, especially for latest Chromium [security patches](https://chromereleases.googleblog.com/2019/10/stable-channel-update-for-desktop_22.html)?

[Breaking changes](https://electronjs.org/blog/electron-7-0#breaking-changes) aren't too bad:
```
Removed deprecated APIs:

    Callback-based versions of functions that now use Promises. #17907
    Tray.setHighlightMode() (macOS). #18981
    app.enableMixedSandbox() #17894
    app.getApplicationMenu(),
    app.setApplicationMenu(),
    powerMonitor.querySystemIdleState(),
    powerMonitor.querySystemIdleTime(),
    webFrame.setIsolatedWorldContentSecurityPolicy(),
    webFrame.setIsolatedWorldHumanReadableName(),
    webFrame.setIsolatedWorldSecurityOrigin() #18159

```

**Comment by deanwhillier** [comment]
@Willyfrog, agreed. I think we should create tickets to deal with following.

@devinbinnie, you've been using `yarn install`? `npm install` is the preferred as of a bit before I started working on the Desktop app. 🤷‍♂️

@hunterlester, our current policy is to remain one version behind the current stable release of Electron. Although v8 is imminent, today is cutoff for features for Desktop v4.4 and the current stable release of Electron is still v7 so we're updating to v6. We'll update to v7 for v4.5. :) Need some time to deal with the changes/deprications in v6.

**Comment by lindalumitchell** [comment]
Dean has done a basic smoke test, so QA will do more thorough testing after merge.

**Pull request merged**
