### PR TITLE
"Cannot connect to Mattermost" is now on top of the page

### LINKED ISSUE #299: Reduce whitespace in "Cannot connect to Mattermost" error page
#### Summary

For `Cannot connect to Mattermost` error page, reduce whitespace at the top, so that there is only `3em` worth of space between the team tab bar and the "Cannot connect to Mattermost" title.

At the moment the text is centered, which looks off on big screens.

image

### PR DESCRIPTION
**Pull request by magicmonty**
First of all, please read `CONTRIBUTING.md`

---

- [x] Complete [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] Execute `npm run prettify` to format codes
- [x] Write about environment which you tested
  - OS X 10.12.1

Should fix #299

### CODE REVIEW

**Comment by jasonblais** [comment]
You're awesome @magicmonty !! Highly appreciated

[Artifacts available here to download](https://circleci.com/gh/mattermost/desktop/729#artifacts), can we get community's help testing the pull request?

Original issue report can be found here: https://github.com/mattermost/desktop/issues/299

**Comment by jasonblais** [comment]
Confirmed on Windows 10 

image

Anyone would like to help with Mac or Linux? Below are the builds to download:
 - [Mac](https://729-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.gebyWLC/mattermost-desktop-osx.tar.gz)
 - [Linux i386.deb](https://729-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.gebyWLC/mattermost-3.4.1-ia32.deb)
 - [Linux amd64.deb](https://729-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.gebyWLC/mattermost-3.4.1-amd64.deb)
 - [Linux ia32.tar.gz](https://729-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.gebyWLC/mattermost-desktop-linux-ia32.tar.gz)
 - [Linux x64.tar.gz](https://729-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.gebyWLC/mattermost-desktop-linux-x64.tar.gz)

To test, you can follow these steps:
 1) Download one of the builds above and open the app
 2) Disconnect your Internet
 3) Refresh the page and observe the error message provided. The expected is a screenshot shown above, which should be at the top of the page, instead of the middle

**Comment by Razzeee** [comment]
This change should be platform agnostic, testing it like you did should cover all platforms.

**Comment by yuya-oc** [comment]
Sure, so if the appearance is proper for us, it's ready to merge.

**Comment by jasonblais** [comment]
We should try to have two testers regardless, even if the change applies to all platforms the same way.

I'm okay if both tests are on Windows, as long as there are two for review.

**Comment by yuya-oc** [comment]
Tested on macOS 10.12.

**Comment by jasonblais** [comment]
Thanks @yuya-oc! Good to merge

**Pull request merged**
