### PR TITLE
Move current search in channel function to Shift+CTRL+S

### PR DESCRIPTION
**Pull request by Razzeee**
This addresses #270 

Tested and working on win10

### CODE REVIEW

**Comment by jasonblais** [comment]
Wow, what a quick turnaround! Great work! Tested on Windows 10 as well, works nicely

I did find one UX defect which is related to the PR (but not caused by it): when doing `CTRL+SHIFT+S` in a DM channel, the search bar is filled with two confusing strings.

It's caused by the fact that DM channel handles/URLs are automatically constructed to be `[userid_1]_[userid_2]` in Mattermost, and this is what `CTRL+SHIFT+S` is picking up.

image

Should `CTRL+SHIFT+S` only work in public and private channels but not in DMs for now? Auto-complete search options for `in` only work for public and private channels in Mattermost web app too.

**Comment by jasonblais** [comment]
If anyone else would like to help with testing the PR, you can download a CircleCI artifact here: https://circleci.com/gh/Razzeee/desktop/11#artifacts

Test cases to consider:
 1. `CTRL+S` should set focus to the search bar
 2. `CTRL+SHIFT+S` should set focus to the search bar AND automatically add `in:[Channel URL]` to the search bar.
 3. `Menu Bar > Edit` should show two options: 
   - one for `Search in Team` which has equivalent behaviour to case 1
   - one for `Search in Channel` which has equivalent behaviour to case 2

Both of the above should allow you to perform search across public channels, private groups and direct messages.

**Comment by Razzeee** [comment]
From what I've tested it seemed like the search also worked for DMs, will have to recheck. But I feel like it's a small price to pay for being able to search DMs

**Comment by jasonblais** [comment]
Sorry @Razzeee, to clarify: DM search works, but the user experience for it is confusing.

I'm going to check with the platform team if there are any plans on handling DM search using the `in` modifier and respond back here

**Comment by jasonblais** [comment]
Found an old ticket that was planning to address this case with usernames: https://mattermost.atlassian.net/browse/PLT-91

@Razzeee Propose making one small update to the PR, which is that when you use `CTRL+SHIFT+S` for a DM channel, the text that auto-populates the search bar is: `in:{username}`.

That would make the user experience less confusing I think, while still keeping the functionality for DMs

**Comment by Razzeee** [comment]
Not easy to do in a sane way :/

**Comment by jasonblais** [comment]
Makes sense, we would probably need the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-91) fixed by the platform team first.

So I guess there's at least these options for v1.4:

1) have `CTRL+SHIFT+S` only work on public/private channels 
 - cons: loses ability to search in DMs, might make it feel like the shortcut is broken
2) have `CTRL+SHIFT+S` work on all channels, including DMs
 - cons: user experience for searching DMs is confusing and below Mattermost UX standards

**Comment by Razzeee** [comment]
1)
Cons no idea how to track if we're in a dm channel, in a sane way

**Comment by yangchen1** [comment]
Great work @Razzeee! Tests 1/2/3 passes for the general case. However if you switch tabs, and then try 1/2/3, focus is not set (the problem is being discussed/hopefully fixed in this PR https://github.com/mattermost/desktop/pull/262)

For all tests, searching within a channel for a direct message gives "in:ooze8mspijga3qufiap76i565r__x6sdh1ok1tyd9f4dgq4" or something similar. This should be changed to the username or display name.

**Comment by jasonblais** [comment]
Hey @Razzeee, 

Given the functionality is already in, we can merge this PR and test how searching DMs feels before we release v1.4.

However, wondering if you'd be interested to work on this open issue in Jira: https://mattermost.atlassian.net/browse/PLT-91

It won't likely be completed by the platform team in the near future and would an improvement to the user experience of searching in DMs.

**Comment by jasonblais** [comment]
@yuya-oc Tested in Windows and OS X, ready for code review and merge.

**Comment by yuya-oc** [comment]
Yup, I've tested it on Ubuntu 14.04. It looks enough for now.

**Comment by yuya-oc** [comment]
For DM issue, probably we can parse the username instead of URL when the active channel is DM. But the solution which is proposed in PLT-91 seems simple.

**Comment by Razzeee** [comment]
@jasonblais 
not sure if there is an documentation for building platform on windows, last time I checked there wasn't. So I can't really do builds/test/improvements.

**Comment by jasonblais** [comment]
Thanks @Razzeee, that makes sense

We have an install guide for Windows in progress, would love to have your help testing it once it's ready, if you'd like?

**Comment by Razzeee** [comment]
I'm not sure, I think I will shift my focus to some private projects soonish :)
So I will have to cut down on time I use for ther stuff.

**Pull request merged**
