### PR TITLE
[MM-T820][MM-T821] Toggle developer Tools in the Menu Bar

### LINKED ISSUE #1902: Desktop E2E Test: MM-T820/MM-T821 Toggle Developer Tools in the Menu Bar
This ticket is to create a test script to automate some testing for the Desktop App.

The testing framework makes use of a few frameworks to successfully automate Desktop App tasks:

  * Playwright: An E2E testing framework provided by Microsoft that currently has “experimental” support for Electron. Using Playwright, you can access individual `BrowserWindows` or `BrowserViews` and automate most functionality provided within those windows. You can also get access to the main Electron process and verify/check functionality in the main process. See here for docs: [https://playwright.dev/docs/api/class-electron](https://playwright.dev/docs/api/class-electron) 
  * RobotJS: A Node.JS Desktop Automation tool that allows us to arbitrary emulate mouse and keyboard inputs. This is used for automation around Electron keyboard shortcuts and the menu bar. It is useful to cover cases that aren’t automatable directly through Playwright (since the menu is not an HTML control). See here for docs: [http://robotjs.io/docs/syntax](http://robotjs.io/docs/syntax)

The test should be written in the file `e2e/specs/menu_bar/view_menu.test.js`
If the file doesn’t exist, feel free to create it.

If you’re looking for examples, see these PRs:
[https://github.com/mattermost/desktop/pull/1841](https://github.com/mattermost/desktop/pull/1841)
[https://github.com/mattermost/desktop/pull/1843](https://github.com/mattermost/desktop/pull/1843)
[https://github.com/mattermost/desktop/pull/1846](https://github.com/mattermost/desktop/pull/1846)

The test script for this ticket is as follows:

MM-T820

  1. Using the menu or a keyboard shortcut, go to View > Developer Tools for Application Wrapper

Expected:
Developer tools pointing to `index.html` appears

MM-T821

  1. Using the menu or a keyboard shortcut, go to View > Developer Tools for Current Tab

Expected:
Developer tools pointing to the current tab URL appears.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-39657

### PR DESCRIPTION
**Pull request by chris-nee**
#### Summary
e2e test to check if the Developer tools are toggled on successfully through the Menu Bar and using keyboard shortcuts.

#### Ticket Link

Fixes #1902

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
- [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
- [x] executed `npm run lint:js` for proper code formatting

#### Device Information
This PR was tested on: 
- macOS Big Sur v11.6.2
- Windows 10 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by chris-nee** [comment]
Hi @M-ZubairAhmed  @devinbinnie  , currently, the PR is still in draft status due to a blocker that I am currently facing. 


### What works 👍 

The dev tool window is triggered correctly, through keyboard shortcuts and through interacting with the settings menu. 


### Blocker 👎 

However, I am unable to identify where the dev tool is pointing towards. 


### Current Observation 💭 

By visual inspection of the windows, we can see that accessing `Developer Tools for Application Wrapper` and `Developer Tools for Current Server` triggers dev tools pointing to different things. ( we can refer to the images attached )

**`Developer Tools for Application Wrapper` -> `**/index.html`**
Screenshot 2022-02-03 at 10 50 38 PM

**`Developer Tools for Current Server` -> `active tab`**
Screenshot 2022-02-03 at 10 50 23 PM

However, when i try to access the `title` and the `url` of the dev tools page using Playwright apis (` page.title(), page.url() `). The information is not sufficient to identify which is which. 

**Developer Tools for Application Wrapper**
- Title - "DevTools"
- Url - "devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@68ac72c865595238656479c37c1b6e4c483f5b21/&can_dock=&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true"

**Developer Tools for Current Server**
- Title - "DevTools"
- Url - "devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@68ac72c865595238656479c37c1b6e4c483f5b21/&can_dock=&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true"

Both are identical somehow, even though they are different visually. May I check if you guys have any thoughts on how else we can approach this ?

**Comment by M-ZubairAhmed** [comment]
@chris-nee could you please resolve the conflict

**Comment by chris-nee** [comment]
Hi @M-ZubairAhmed  @devinbinnie  , I managed to find a way around it for now.

The process to find out where the dev tool is pointing to is as follows: 

1. After the dev tools console is loaded, we enter the console tab 
2. Register a window 'dialog' event listener to all the windows using `playwright` ( `dialog` event gets triggered, when the page experiences an alert event ) 
3. Using robotjs, we input the following command to the console `alert ( window.location.href )` and click enter
4. The page will receive the alert event, trigger our pre-registered listener
5. We can then retrieve the `window.location.href` value by reading the message value of the event
6. From the message we can then tell where the dev tool was pointing to 

This should satisfy check 😄 


The only downside is that, the loading of dev tools console is a bit arbitrary ( we cannot interact with the dev tool console using robotjs untill the arbitrary loading is completed ). So for now, I'm using a fixed constant timeout value to await for the dev tools to finish loading. Please let me know if you have any concerns with this implementation, thanks !

**Comment by Willyfrog** [comment]
if you can search within the devtools there are a few things you could try. One that comes to mind is going to the console and check that there is the log for mattermost initialization which looks like `Starting Mattermost v5.0.0-develop commit: a410222`

**Comment by devinbinnie** [comment]
@chris-nee I think your approach works. @Willyfrog's would work as well but it would only tell us that the view is a Mattermost view and not the specific URL (without modifying the preload script).

Let's go with yours @chris-nee and we can tweak that constant or look for other things to wait for later on. Thanks for the hard work :)

**Comment by chris-nee** [comment]
> @chris-nee its failing in ci as it uses linux environment

I see, let me fix that

**Comment by M-ZubairAhmed** [comment]
@chris-nee would you still be interested in making this pr till finish line 🥅

**Comment by chris-nee** [comment]
Hi @M-ZubairAhmed, yes, will try to finish this by this weekend

**Comment by chris-nee** [comment]
Hi @M-ZubairAhmed  , i've looked into the issue in the _circleci_ check. The test is able to run smoothly locally, but on CirclCI, the test is only able to run smoothly up till the point where we check for where the dev tools is pointing to. 

I have tried maxing out the timeout and also attempted to send different _alert_ messages through the dev tool console. The issue seems to be not being able to interact with the dev tool console on the CircleCI environment. Do you have any idea on what could affect this ? 

If there is no way around this, may i suggest that we divide the test case into 2 sub parts, 1 for checking dev tools is opened and 1 for checking where the dev tools is pointing to ? On top of this , during _CircleCI environment check_ we can skip the 2nd sub part and during _Local environment check_ we will run the full 2 sub parts ?

**Comment by devinbinnie** [comment]
> 

@chris-nee That sounds like a good idea to me, thanks for the investigation.

For the second, you can just add `it.skip` to the front of the test, that way it won't be run on CI. I'm thinking going forward that we will avoid running the tests on every PR since CircleCI's environment doesn't seem to be cooperative while running many of these tests.

**Comment by chris-nee** [comment]
Alright, let me make the required changes, thanks !

**Review by M-ZubairAhmed — APPROVED** [review]
Thanks @chris-nee i am going to approve it too. Since we can skip this test in the ci.

**Comment by chris-nee** [comment]
Hi @devinbinnie @M-ZubairAhmed , i've made the changes as discussed, the tests added for this PR are clearing now ( except for the skipped part ). 

There is 1 test that is currently failing from another test suite under _history_menu_ , is that expected ? 
Screenshot 2022-02-24 at 3 44 18 PM

**Comment by devinbinnie** [comment]
> Hi @devinbinnie @M-ZubairAhmed , i've made the changes as discussed, the tests added for this PR are clearing now ( except for the skipped part ).
> 
> There is 1 test that is currently failing from another test suite under _history_menu_ , is that expected ? Screenshot 2022-02-24 at 3 44 18 PM

@chris-nee Thanks! Yes that one is a little flaky, so if it's not affecting your test you can ignore it for now.

**Comment by chris-nee** [comment]
Thanks both for your help !

**Pull request merged**
