### PR TITLE
[MM-22102] upgrade to electron 7

### PR DESCRIPTION
**Pull request by Willyfrog**
Before submitting, please confirm you've
 - [X] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
upgraded dependency to electron-7

removed fix for darkmode
fixed deprecated code
fixed some extra errors and warnings

**Issue link**
[MM-22102](https://mattermost.atlassian.net/browse/MM-22102)

**Test Cases**

Everything should work as expected

### CODE REVIEW

**Comment by esethna** [comment]
@devinbinnie @Willyfrog can we auto dark mode based on OS theme for the tab bars with electron 7? If so do we need follow-up tickets to hook that up?

**Comment by Willyfrog** [comment]
I think it is possible per [documentation](https://www.electronjs.org/docs/tutorial/mojave-dark-mode-guide#automatically-updating-the-native-interfaces) but I'd file a separate ticket, migrating to electron 7 should be painless, but it is a big change by itself

**Comment by esethna** [comment]
Thanks, can you file a follow-up ticket for that?

**Comment by Willyfrog** [comment]
> Thanks, can you file a follow-up ticket for that?

https://mattermost.atlassian.net/browse/MM-24291 see if you want to add anything to the description.

**Comment by Willyfrog** [comment]
test passing on ci

**Comment by amyblais** [comment]
After this PR is merged it would be good to cut RC-1 for v4.5.0 for QA. Last time we upgraded the Electron version we started to see lot of bugs which made release testing quite messy and delayed the final release.

**Comment by Willyfrog** [comment]
@amyblais i'm planning to talk with the IS team this week in order to start producing nightly builds, which might help with this. Although I currently don't have a timeline for when would it be done.

**Pull request merged**
