### PR TITLE
Update macOS app icon for Big Sur

### PR DESCRIPTION
**Pull request by tdimeco**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [X] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [X] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**
Update macOS app icon for Big Sur

**Issue link**
https://github.com/mattermost/desktop/issues/1389

### CODE REVIEW

**Comment by Willyfrog** [comment]
hello @tdimeco 
thanks a lot for contributing a new icon!

can you please provide some screenshots of the icon in use?

**Comment by tdimeco** [comment]
Hi @Willyfrog,
Sure, you have some examples in the related issue: https://github.com/mattermost/desktop/issues/1389 ;)

**Comment by Willyfrog** [comment]
thanks @tdimeco 
fixes #1389

**Review by matthewbirtch — COMMENTED** [review]
@tdimeco thanks for the contribution and for being so on-the-ball with Big Sur updates. We are actually going to take this one internally as there are some other adjustments we're going to make to align with some of the latest branding updates.

**Comment by tdimeco** [comment]
@matthewbirtch You are welcome. I understand, I suspected it ;)

**Comment by matthewbirtch** [comment]
> @matthewbirtch @Willyfrog do we have a ticket to track the big sur icon updates? 

Yep. These two tickets:

https://mattermost.atlassian.net/browse/MM-30619

https://mattermost.atlassian.net/browse/MM-30619

**Pull request closed without merging**
