### PR TITLE
GH-1085 Replace simple-spellchecker with electron-spellchecker

### PR DESCRIPTION
**Pull request by keithcruz**
Before submitting, please confirm you've
 - [x] read and understood our [Contributing Guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md)
 - [x] completed [Mattermost Contributor Agreement](http://www.mattermost.org/mattermost-contributor-agreement/)
 - [x] executed `npm run lint:js` for proper code formatting

Please provide the following information:

**Summary**

This is a WIP that replaces simple-spellchecker with electron-spellchecker.

**Issue link**

[GH-1085](https://github.com/mattermost/desktop/issues/1085)
**Test Cases**

**Additional Notes**
Some initial findings:
1.  Language detection doesn’t seem to work on Mac.  I have tried by setting and not setting the initial language and then proceeding to type in Spanish and it never seems to switch or catch on.  I have found a few issues in the repo that indicate that this may be an ongoing issue. https://github.com/electron-userland/electron-spellchecker/issues/127 . In the current version of mattermost spellcheck you are able to switch language from the context menu.  Electron-spellcheck does not have this behavior built in.  Further investigation is required to determine if it would be possible to add this capability or if it would be better to just add to the settings an option to select a language if on mac.
2.  Electron-builder and electron-rebuild seem to have issues building native node modules with the two package.json structure.  It may be worthwhile to see if a single package.json structure will be better long term.  https://github.com/electron/electron-rebuild/issues/253#issuecomment-426833695

### CODE REVIEW

**Comment by keithcruz** [comment]
@deanwhillier Next step will be to see if adding language switching via context menu is possible or not too much of a hack 😁 .  If not would like to get input on whether or not the team would like to add language selection as a setting or to keep the current implementation with simple-spellchecker.  It seems being able to switch languages automatically is best, via context menu next best, and via a setting as the least desirable option but that is a personal opinion and would like feedback on whether the benefits of electron-spellcheck outweigh the slight regression.

**Comment by wget** [comment]
@keithcruz +1 for only one package.json data structure.

This has been discussed one year ago with yuya-oc who didn't have time to implement such a refactorisation. If you think this will help, *please* go for it =)

**Comment by keithcruz** [comment]
@deanwhillier @jasonblais apologies for the lack of activity, I will have an update on this soon.  Thanks.

**Comment by deanwhillier** [comment]
@keithcruz, I'm open to automatic language switching, but wonder if a backup setting would be good in case someone really wants a different language than their OS. I don't think language selection from the context menu is necessary at all! Open to others thoughts on this!

@devinbinnie, @Willyfrog, can you guys please take some time over the next bit to start reviewing this PR?

**Comment by Willyfrog** [comment]
@keithcruz let me know if you need clarification or any help with this

**Comment by deanwhillier** [comment]
@Willyfrog, given we are looking into the new Spellchecker that comes with Electron v8 (or v7, can't remember exactly off hand), should we wait to determine if it will work as we need before abandoning this approach?

**Comment by Willyfrog** [comment]
definitely, my initial tests shows that it works as basic spellchecker, but I have yet to test the "add new spelling" feature, which requires using browserview, as it is difficult to add to a webview tag.

**Comment by deanwhillier** [comment]
Closing as we are moving towards using the integrated spell checker in Electron 8.

**Pull request closed without merging**
